// lib/plantText.js — every word about utility plants in four languages: the
// portfolios list's projects card, the plant editor on a portfolio, its permit
// checklist (lib/plantPermits.js) and the plant pages of the report.
// Module-local, like lib/portfolioText.js. Installer copy speaks to the user
// as "tu" in Romanian. lib/plantText.test.js checks languages, placeholders
// and punctuation.

const T = {
  // ---- the portfolios list
  card_h: { en: "Large projects: wind, solar, storage", ro: "Proiecte mari: vânt, soare, stocare", ru: "Крупные проекты: ветер, солнце, накопители", uk: "Великі проєкти: вітер, сонце, накопичувачі" },
  card_p: {
    en: "A plant of several megawatts, financed on its own or next to your quotes. Its energy comes from public data until the wind or solar study arrives, then from the study.",
    ro: "O centrală de câțiva megawați, finanțată singură sau alături de ofertele tale. Producția vine din date publice până sosește studiul de vânt sau solar, apoi din studiu.",
    ru: "Станция мощностью в несколько мегаватт, финансируемая отдельно или вместе с вашими расчётами. Выработка берётся из открытых данных, пока нет исследования ветра или солнца, затем из исследования.",
    uk: "Станція потужністю в кілька мегаватів, що фінансується окремо або разом із вашими розрахунками. Генерація береться з відкритих даних, доки немає дослідження вітру чи сонця, потім із дослідження.",
  },
  sample_hybrid: { en: "Load the sample: hybrid park (wind, solar, storage)", ro: "Încarcă exemplul: parc hibrid (vânt, soare, stocare)", ru: "Загрузить пример: гибридный парк (ветер, солнце, накопители)", uk: "Завантажити приклад: гібридний парк (вітер, сонце, накопичувачі)" },
  sample_roofs: { en: "Load the sample: commercial rooftops", ro: "Încarcă exemplul: acoperișuri comerciale", ru: "Загрузить пример: коммерческие крыши", uk: "Завантажити приклад: комерційні дахи" },
  sample_wait: { en: "Loading a sample looks up the wind and the sun at each site; it can take up to a minute.", ro: "Încărcarea unui exemplu caută vântul și soarele pentru fiecare amplasament; poate dura până la un minut.", ru: "Загрузка примера запрашивает ветер и солнце для каждой площадки; это может занять до минуты.", uk: "Завантаження прикладу запитує вітер і сонце для кожного майданчика; це може тривати до хвилини." },
  new_plant: { en: "New plant project", ro: "Proiect nou de centrală", ru: "Новый проект станции", uk: "Новий проєкт станції" },
  new_plant_ph: { en: "Plant name", ro: "Numele centralei", ru: "Название станции", uk: "Назва станції" },
  err_failed: { en: "Could not create it. Try again.", ro: "Nu s-a putut crea. Încearcă din nou.", ru: "Не удалось создать. Повторите.", uk: "Не вдалося створити. Спробуйте ще." },
  err_rate_limited: { en: "Too many requests at once; try again in a minute.", ro: "Prea multe cereri deodată; încearcă din nou peste un minut.", ru: "Слишком много запросов; повторите через минуту.", uk: "Забагато запитів; спробуйте ще за хвилину." },
  n_plants: { en: "{n} plants", ro: "{n} centrale", ru: "станций: {n}", uk: "станцій: {n}" },
  n_plants_one: { en: "{n} plant", ro: "{n} centrală", ru: "станций: {n}", uk: "станцій: {n}" },

  // ---- the plants section of a portfolio
  sec_h: { en: "Plants", ro: "Centrale", ru: "Станции", uk: "Станції" },
  sec_p: {
    en: "Utility-scale plants in this portfolio: wind, solar and battery storage on one site, each with its energy, revenue, costs and permits.",
    ro: "Centralele mari din acest portofoliu: vânt, soare și stocare pe un amplasament, fiecare cu producția, venitul, costurile și autorizațiile ei.",
    ru: "Крупные станции этого портфеля: ветер, солнце и накопители на одной площадке, каждая со своей выработкой, выручкой, затратами и разрешениями.",
    uk: "Великі станції цього портфеля: вітер, сонце та накопичувачі на одному майданчику, кожна зі своєю генерацією, виручкою, витратами та дозволами.",
  },
  add_plant: { en: "Add a plant", ro: "Adaugă o centrală", ru: "Добавить станцию", uk: "Додати станцію" },
  remove_plant: { en: "Remove the plant", ro: "Elimină centrala", ru: "Удалить станцию", uk: "Видалити станцію" },
  remove_confirm: { en: "Remove {name} from this portfolio?", ro: "Elimini {name} din acest portofoliu?", ru: "Удалить {name} из портфеля?", uk: "Видалити {name} з портфеля?" },
  sample_badge: { en: "Sample data", ro: "Date exemplu", ru: "Пример данных", uk: "Приклад даних" },
  sample_note: {
    en: "Sample values for illustration: costs, prices, terms and permit statuses are assumptions, not quotes, offers or facts. The wind and sun at the site are real public data.",
    ro: "Valori exemplu, pentru ilustrare: costurile, prețurile, condițiile și stadiul autorizațiilor sunt ipoteze, nu oferte sau fapte. Vântul și soarele pe amplasament sunt date publice reale.",
    ru: "Примерные значения для иллюстрации: затраты, цены, условия и статусы разрешений являются допущениями, а не предложениями или фактами. Ветер и солнце на площадке являются реальными открытыми данными.",
    uk: "Приклад значень для ілюстрації: витрати, ціни, умови та статуси дозволів є припущеннями, а не пропозиціями чи фактами. Вітер і сонце на майданчику є реальними відкритими даними.",
  },
  f_name: { en: "Name", ro: "Nume", ru: "Название", uk: "Назва" },
  f_locality: { en: "Locality", ro: "Localitate", ru: "Населённый пункт", uk: "Населений пункт" },
  f_lat: { en: "Latitude", ro: "Latitudine", ru: "Широта", uk: "Широта" },
  f_lon: { en: "Longitude", ro: "Longitudine", ru: "Долгота", uk: "Довгота" },
  f_operator: { en: "Grid operator", ro: "Operatorul de rețea", ru: "Оператор сети", uk: "Оператор мережі" },
  f_need_site: { en: "Set the latitude and longitude to look up the wind and the sun.", ro: "Setează latitudinea și longitudinea ca să cauți vântul și soarele.", ru: "Укажите широту и долготу, чтобы запросить ветер и солнце.", uk: "Вкажіть широту й довготу, щоб запитати вітер і сонце." },

  // ---- the grid around the site (components/portfolio/GridPanel.jsx)
  grid_h: { en: "Grid connection", ro: "Racordarea la rețea", ru: "Подключение к сети", uk: "Підключення до мережі" },
  grid_word: { en: "grid", ro: "rețea", ru: "сеть", uk: "мережа" },
  grid_p: {
    en: "Where the power grid is around the site, from OpenStreetMap: substations in Moldova at 35 kV and above, and high-voltage lines. Choose the point you expect to connect to and estimate the line.",
    ro: "Unde este rețeaua electrică în jurul amplasamentului, din OpenStreetMap: stațiile din Moldova de 35 kV și peste, și liniile de înaltă tensiune. Alege punctul la care te aștepți să te racordezi și estimează linia.",
    ru: "Где проходит электросеть вокруг площадки, по OpenStreetMap: подстанции в Молдове от 35 кВ и линии высокого напряжения. Выберите ожидаемую точку подключения и оцените линию.",
    uk: "Де проходить електромережа навколо майданчика, за OpenStreetMap: підстанції в Молдові від 35 кВ і лінії високої напруги. Виберіть очікувану точку підключення та оцініть лінію.",
  },
  grid_find: { en: "Look up the grid nearby", ro: "Caută rețeaua din jur", ru: "Найти сеть рядом", uk: "Знайти мережу поруч" },
  grid_again: { en: "Look it up again", ro: "Caută din nou", ru: "Найти заново", uk: "Знайти знову" },
  grid_busy: { en: "Looking up the grid...", ro: "Se caută rețeaua...", ru: "Поиск сети...", uk: "Пошук мережі..." },
  grid_failed: { en: "The grid data did not answer; try again in a moment.", ro: "Datele despre rețea nu au răspuns; încearcă din nou peste puțin timp.", ru: "Данные о сети не ответили; повторите чуть позже.", uk: "Дані про мережу не відповіли; спробуйте трохи пізніше." },
  grid_none: {
    en: "OpenStreetMap shows no substation of 35 kV or more within 40 km and no high-voltage line within 20 km.",
    ro: "OpenStreetMap nu arată nicio stație de 35 kV sau mai mult pe o rază de 40 km și nicio linie de înaltă tensiune pe o rază de 20 km.",
    ru: "OpenStreetMap не показывает подстанций от 35 кВ в радиусе 40 км и линий высокого напряжения в радиусе 20 км.",
    uk: "OpenStreetMap не показує підстанцій від 35 кВ у радіусі 40 км і ліній високої напруги в радіусі 20 км.",
  },
  grid_moved: { en: "The grid was looked up for a point {km} km away: look it up again here.", ro: "Rețeaua a fost căutată pentru un punct aflat la {km} km: caut-o din nou aici.", ru: "Сеть искали для точки в {km} км: найдите заново здесь.", uk: "Мережу шукали для точки за {km} км: знайдіть знову тут." },
  grid_cls_hv: { en: "330 kV and above", ro: "330 kV și peste", ru: "330 кВ и выше", uk: "330 кВ і вище" },
  grid_cls_110: { en: "110 kV", ro: "110 kV", ru: "110 кВ", uk: "110 кВ" },
  grid_cls_35: { en: "35 kV", ro: "35 kV", ru: "35 кВ", uk: "35 кВ" },
  grid_col_point: { en: "Connection point", ro: "Punct de racordare", ru: "Точка подключения", uk: "Точка підключення" },
  grid_col_km: { en: "Distance, km", ro: "Distanța, km", ru: "Расстояние, км", uk: "Відстань, км" },
  grid_sub: { en: "Substation", ro: "Stație", ru: "Подстанция", uk: "Підстанція" },
  grid_line: { en: "Line (a tap into it)", ro: "Linie (derivație din ea)", ru: "Линия (отпайка)", uk: "Лінія (відгалуження)" },
  grid_near_place: { en: "near {x}", ro: "lângă {x}", ru: "около {x}", uk: "біля {x}" },
  ox_update: { en: "Update", ro: "Actualizează", ru: "Обновить", uk: "Оновити" },
  ox_stale: {
    en: "The route changed: the option in use now costs {cost}. Update it to carry the new cost and losses into the plant.",
    ro: "Traseul s-a schimbat: opțiunea folosită costă acum {cost}. Actualizeaz-o ca să treacă noul cost și noile pierderi în centrală.",
    ru: "Трасса изменилась: выбранный вариант теперь стоит {cost}. Обновите его, чтобы перенести новую стоимость и потери в станцию.",
    uk: "Траса змінилася: вибраний варіант тепер коштує {cost}. Оновіть його, щоб перенести нову вартість і втрати в станцію.",
  },
  grid_unnamed: { en: "unnamed in OpenStreetMap", ro: "fără nume în OpenStreetMap", ru: "без названия в OpenStreetMap", uk: "без назви в OpenStreetMap" },
  grid_pick: { en: "Connect here", ro: "Racordare aici", ru: "Подключение здесь", uk: "Підключення тут" },
  grid_caveat: {
    en: "OpenStreetMap shows where the grid is, not whether it has spare capacity or where the operator will let the plant connect: Moldelectrica or the distribution operator decides both, in the connection approval. Distances are straight lines.",
    ro: "OpenStreetMap arată unde este rețeaua, nu dacă are capacitate liberă sau unde va permite operatorul racordarea: Moldelectrica sau operatorul de distribuție decid ambele, în avizul de racordare. Distanțele sunt în linie dreaptă.",
    ru: "OpenStreetMap показывает, где проходит сеть, но не свободную мощность и не место, где оператор разрешит подключение: оба вопроса решает Moldelectrica или оператор распределения в разрешении на подключение. Расстояния указаны по прямой.",
    uk: "OpenStreetMap показує, де проходить мережа, але не вільну потужність і не місце, де оператор дозволить підключення: обидва питання вирішує Moldelectrica або оператор розподілу в дозволі на підключення. Відстані вказано по прямій.",
  },
  grid_credit: { en: "Grid data © OpenStreetMap contributors (ODbL), looked up {date}.", ro: "Date despre rețea © contribuitorii OpenStreetMap (ODbL), căutate la {date}.", ru: "Данные о сети © участники OpenStreetMap (ODbL), получены {date}.", uk: "Дані про мережу © учасники OpenStreetMap (ODbL), отримано {date}." },
  grid_map: { en: "The grid around the site", ro: "Rețeaua din jurul amplasamentului", ru: "Сеть вокруг площадки", uk: "Мережа навколо майданчика" },
  est_route: { en: "Route factor (assumption)", ro: "Factor de traseu (ipoteză)", ru: "Коэффициент трассы (допущение)", uk: "Коефіцієнт траси (припущення)" },
  est_route_h: {
    en: "A line follows roads and land plots, so it runs longer than the straight line: 1.2 means 20% longer.",
    ro: "O linie urmează drumuri și terenuri, deci e mai lungă decât linia dreaptă: 1,2 înseamnă cu 20% mai lungă.",
    ru: "Линия идёт вдоль дорог и участков, поэтому длиннее прямой: 1,2 означает на 20% длиннее.",
    uk: "Лінія йде вздовж доріг і ділянок, тому довша за пряму: 1,2 означає на 20% довша.",
  },

  // ---- grid connection, second part: options, costs, route, crossings, shared points
  ox_h: { en: "Connection options compared", ro: "Opțiunile de racordare comparate", ru: "Сравнение вариантов подключения", uk: "Порівняння варіантів підключення" },
  ox_p: {
    en: "Each realistic point at its voltage: the route, whether one line can carry the plant, the energy it loses, what it costs from your figures, and what it does to the deal.",
    ro: "Fiecare punct realist, la tensiunea lui: traseul, dacă o linie poate duce centrala, energia pierdută, costul din cifrele tale și efectul asupra finanțării.",
    ru: "Каждая реальная точка на своём напряжении: трасса, выдержит ли одна линия станцию, потери энергии, стоимость по вашим цифрам и влияние на сделку.",
    uk: "Кожна реальна точка на своїй напрузі: траса, чи витримає одна лінія станцію, втрати енергії, вартість за вашими цифрами та вплив на угоду.",
  },
  ox_col_opt: { en: "Option", ro: "Opțiune", ru: "Вариант", uk: "Варіант" },
  ox_col_route: { en: "Route, km", ro: "Traseu, km", ru: "Трасса, км", uk: "Траса, км" },
  ox_col_carry: { en: "Carries the plant", ro: "Duce centrala", ru: "Выдержит станцию", uk: "Витримає станцію" },
  ox_col_loss: { en: "Losses a year", ro: "Pierderi pe an", ru: "Потери в год", uk: "Втрати на рік" },
  ox_col_cost: { en: "Cost", ro: "Cost", ru: "Стоимость", uk: "Вартість" },
  ox_col_effect: { en: "Lowest DSCR, IRR", ro: "DSCR minim, IRR", ru: "Мин. DSCR, IRR", uk: "Мін. DSCR, IRR" },
  ox_drawn: { en: "drawn", ro: "trasat", ru: "нарисована", uk: "намальована" },
  ox_straight: { en: "straight x {f}", ro: "în linie dreaptă x {f}", ru: "по прямой x {f}", uk: "по прямій x {f}" },
  ox_yes: { en: "yes, up to {cap} MW", ro: "da, până la {cap} MW", ru: "да, до {cap} МВт", uk: "так, до {cap} МВт" },
  ox_no: { en: "no: {mw} MW over {cap} MW", ro: "nu: {mw} MW peste {cap} MW", ru: "нет: {mw} МВт больше {cap} МВт", uk: "ні: {mw} МВт більше {cap} МВт" },
  ox_with: { en: "with the plants sharing it", ro: "cu centralele care îl folosesc", ru: "вместе с другими станциями", uk: "разом з іншими станціями" },
  ox_best: { en: "Best option", ro: "Cea mai bună", ru: "Лучший вариант", uk: "Найкращий варіант" },
  ox_use: { en: "Use this option", ro: "Folosește opțiunea", ru: "Выбрать вариант", uk: "Вибрати варіант" },
  ox_in_use: { en: "In use", ro: "Folosită", ru: "Выбран", uk: "Вибрано" },
  ox_used: {
    en: "In use: {opt}. Its cost, {cost}, is the plant's grid cost, and its losses, {loss}, come off the plant's energy.",
    ro: "Folosită: {opt}. Costul ei, {cost}, este costul racordării centralei, iar pierderile, {loss}, se scad din producția centralei.",
    ru: "Выбран: {opt}. Его стоимость, {cost}, стала стоимостью подключения станции, а потери, {loss}, вычитаются из её выработки.",
    uk: "Вибрано: {opt}. Його вартість, {cost}, стала вартістю підключення станції, а втрати, {loss}, віднімаються від її генерації.",
  },
  ox_need_costs: {
    en: "Enter your costs per voltage below to compare the costs and the effect on the deal.",
    ro: "Introdu mai jos costurile tale pe tensiune ca să compari costurile și efectul asupra finanțării.",
    ru: "Введите ниже ваши затраты по напряжениям, чтобы сравнить стоимость и влияние на сделку.",
    uk: "Введіть нижче ваші витрати за напругами, щоб порівняти вартість і вплив на угоду.",
  },
  ox_note: {
    en: "One circuit carries about sqrt(3) x kV x the conductor's rating x 0.95. Losses are three phases of I squared R at full output, spread over the year by the usual loss-load factor of the plant's capacity factor. The conductor ratings are typical tables for steel-aluminium conductors; pick yours per voltage. Estimates to take to the operator, not its answer.",
    ro: "O linie duce circa radical din 3 x kV x curentul admisibil al conductorului x 0,95. Pierderile sunt trei faze de I la pătrat ori R la putere maximă, repartizate pe an cu factorul obișnuit de pierderi din factorul de capacitate al centralei. Curenții admisibili sunt valori tipice din tabelele pentru conductoare oțel-aluminiu; alege-l pe al tău pentru fiecare tensiune. Sunt estimări de discutat cu operatorul, nu răspunsul lui.",
    ru: "Одна линия передаёт около корня из 3 x кВ x допустимый ток провода x 0,95. Потери: три фазы I в квадрате на R при полной мощности, распределённые на год обычным коэффициентом потерь от коэффициента использования станции. Допустимые токи взяты из типовых таблиц для сталеалюминиевых проводов; выберите свой для каждого напряжения. Это оценки для обсуждения с оператором, а не его ответ.",
    uk: "Одна лінія передає близько кореня з 3 x кВ x допустимий струм проводу x 0,95. Втрати: три фази I в квадраті на R при повній потужності, розподілені на рік звичайним коефіцієнтом втрат від коефіцієнта використання станції. Допустимі струми взято з типових таблиць для сталеалюмінієвих проводів; виберіть свій для кожної напруги. Це оцінки для обговорення з оператором, а не його відповідь.",
  },
  cs_h: { en: "Your costs per voltage", ro: "Costurile tale pe tensiune", ru: "Ваши затраты по напряжениям", uk: "Ваші витрати за напругами" },
  cs_perkm: { en: "Line, EUR per km", ro: "Linie, EUR pe km", ru: "Линия, EUR за км", uk: "Лінія, EUR за км" },
  cs_sub: { en: "Bay at a substation, EUR", ro: "Celulă în stație, EUR", ru: "Ячейка на подстанции, EUR", uk: "Комірка на підстанції, EUR" },
  cs_tap: { en: "New station for a tap, EUR", ro: "Stație nouă pentru derivație, EUR", ru: "Новая станция для отпайки, EUR", uk: "Нова станція для відгалуження, EUR" },
  cs_cond: { en: "Conductor", ro: "Conductor", ru: "Провод", uk: "Провід" },
  rt_draw: { en: "Draw the route", ro: "Trasează traseul", ru: "Нарисовать трассу", uk: "Намалювати трасу" },
  rt_edit: { en: "Change the route", ro: "Modifică traseul", ru: "Изменить трассу", uk: "Змінити трасу" },
  rt_hint: {
    en: "Click along the way the line would run (roads, field edges, around villages); each click adds a bend and every bend can be dragged. The route runs from the plant to the chosen point.",
    ro: "Apasă de-a lungul drumului pe care ar merge linia (drumuri, margini de câmp, ocolind satele); fiecare clic adaugă un punct, iar fiecare punct poate fi tras. Traseul merge de la centrală la punctul ales.",
    ru: "Нажимайте вдоль пути линии (дороги, края полей, в обход сёл); каждый клик добавляет точку, каждую точку можно перетащить. Трасса идёт от станции к выбранной точке.",
    uk: "Натискайте вздовж шляху лінії (дороги, краї полів, в обхід сіл); кожен клік додає точку, кожну точку можна перетягнути. Траса йде від станції до вибраної точки.",
  },
  rt_undo: { en: "Undo the last bend", ro: "Anulează ultimul punct", ru: "Отменить последнюю точку", uk: "Скасувати останню точку" },
  rt_clear: { en: "Remove the route", ro: "Șterge traseul", ru: "Удалить трассу", uk: "Видалити трасу" },
  rt_done: { en: "Done", ro: "Gata", ru: "Готово", uk: "Готово" },
  rt_len: { en: "Route to {opt}: {km} km, {how}.", ro: "Traseul până la {opt}: {km} km, {how}.", ru: "Трасса до {opt}: {km} км, {how}.", uk: "Траса до {opt}: {km} км, {how}." },
  rt_drawn: { en: "drawn on the map", ro: "trasat pe hartă", ru: "нарисована на карте", uk: "намальована на карті" },
  rt_straight: { en: "the straight line x {f} until you draw it", ro: "linia dreaptă x {f} până îl trasezi", ru: "прямая x {f}, пока вы её не нарисуете", uk: "пряма x {f}, доки ви її не намалюєте" },
  mp_sat: { en: "Satellite", ro: "Satelit", ru: "Спутник", uk: "Супутник" },
  mp_plain: { en: "Map", ro: "Hartă", ru: "Карта", uk: "Карта" },
  mp_full: { en: "Full screen", ro: "Ecran complet", ru: "Во весь экран", uk: "На весь екран" },
  mp_exit: { en: "Exit full screen", ro: "Ieși din ecran complet", ru: "Выйти из полноэкранного режима", uk: "Вийти з повноекранного режиму" },
  mp_frame: { en: "Frame the site", ro: "Centrează amplasamentul", ru: "Показать площадку", uk: "Показати майданчик" },
  cx_h: { en: "What the route crosses", ro: "Ce traversează traseul", ru: "Что пересекает трасса", uk: "Що перетинає траса" },
  cx_btn: { en: "Check the route", ro: "Verifică traseul", ru: "Проверить трассу", uk: "Перевірити трасу" },
  cx_busy: { en: "Checking the route...", ro: "Se verifică traseul...", ru: "Проверка трассы...", uk: "Перевірка траси..." },
  cx_none: { en: "OpenStreetMap shows nothing the route crosses.", ro: "OpenStreetMap nu arată nimic din ce traversează traseul.", ru: "OpenStreetMap не показывает пересечений трассы.", uk: "OpenStreetMap не показує перетинів траси." },
  cx_old: { en: "The route changed after this check: check it again.", ro: "Traseul s-a schimbat după această verificare: verifică-l din nou.", ru: "Трасса изменилась после проверки: проверьте снова.", uk: "Траса змінилася після перевірки: перевірте знову." },
  cx_failed: { en: "The check did not answer; try again in a moment.", ro: "Verificarea nu a răspuns; încearcă din nou peste puțin timp.", ru: "Проверка не ответила; повторите чуть позже.", uk: "Перевірка не відповіла; спробуйте трохи пізніше." },
  cx_protected: { en: "Protected area", ro: "Arie protejată", ru: "Охраняемая территория", uk: "Охоронювана територія" },
  cx_river: { en: "River or canal", ro: "Râu sau canal", ru: "Река или канал", uk: "Річка або канал" },
  cx_rail: { en: "Railway", ro: "Cale ferată", ru: "Железная дорога", uk: "Залізниця" },
  cx_road: { en: "Road", ro: "Drum", ru: "Дорога", uk: "Дорога" },
  cx_power: { en: "Power line", ro: "Linie electrică", ru: "ЛЭП", uk: "ЛЕП" },
  cx_forest: { en: "Forest", ro: "Pădure", ru: "Лес", uk: "Ліс" },
  cx_built: { en: "Built-up area", ro: "Zonă construită", ru: "Застройка", uk: "Забудова" },
  cx_village: { en: "Village nearby", ro: "Localitate în apropiere", ru: "Населённый пункт рядом", uk: "Населений пункт поруч" },
  cx_unnamed: { en: "unnamed", ro: "fără nume", ru: "без названия", uk: "без назви" },
  cx_note: {
    en: "Each crossing usually needs an agreement or a permit of its own: a right of way, the road, rail or water authority's approval, an environmental assessment in a protected area. From OpenStreetMap: within 30 m of the route, villages within 1 km.",
    ro: "Fiecare traversare cere de obicei un acord sau o autorizație proprie: drept de servitute, avizul administratorului drumului, căii ferate sau apelor, evaluarea de mediu într-o arie protejată. Din OpenStreetMap: la cel mult 30 m de traseu, localitățile la cel mult 1 km.",
    ru: "Каждое пересечение обычно требует отдельного согласования или разрешения: сервитут, согласование владельца дороги, железной дороги или водного объекта, экологическая оценка в охраняемой зоне. По OpenStreetMap: в пределах 30 м от трассы, населённые пункты в пределах 1 км.",
    uk: "Кожен перетин зазвичай потребує окремого погодження або дозволу: сервітут, погодження власника дороги, залізниці чи водного об'єкта, екологічна оцінка в охоронюваній зоні. За OpenStreetMap: у межах 30 м від траси, населені пункти в межах 1 км.",
  },
  sh_h: { en: "Shared connection point", ro: "Punct de racordare comun", ru: "Общая точка подключения", uk: "Спільна точка підключення" },
  sh_p: { en: "{names} also connect at {point}: {mw} MW together.", ro: "{names} se racordează tot la {point}: împreună {mw} MW.", ru: "{names} тоже подключаются к {point}: вместе {mw} МВт.", uk: "{names} теж підключаються до {point}: разом {mw} МВт." },
  sh_over: { en: "That is more than one {kv} kV line carries (about {cap} MW): plan a second circuit or another point.", ro: "Este mai mult decât duce o linie de {kv} kV (circa {cap} MW): prevede un al doilea circuit sau alt punct.", ru: "Это больше, чем выдерживает одна линия {kv} кВ (около {cap} МВт): нужна вторая цепь или другая точка.", uk: "Це більше, ніж витримує одна лінія {kv} кВ (близько {cap} МВт): потрібне друге коло або інша точка." },
  sh_tick: { en: "Share one line and split its cost by MW", ro: "Folosiți o linie comună și împărțiți costul după MW", ru: "Общая линия, затраты делятся по МВт", uk: "Спільна лінія, витрати діляться за МВт" },
  sh_save: { en: "This plant's share: {x} instead of {y} alone.", ro: "Partea acestei centrale: {x} în loc de {y} singură.", ru: "Доля этой станции: {x} вместо {y} в одиночку.", uk: "Частка цієї станції: {x} замість {y} самостійно." },

  // ---- choosing the site on a map (components/portfolio/SitePicker.jsx)
  pick_btn: { en: "Choose on the map", ro: "Alege pe hartă", ru: "Выбрать на карте", uk: "Вибрати на карті" },
  pick_add: { en: "Add a plant on the map", ro: "Adaugă o centrală pe hartă", ru: "Добавить станцию на карте", uk: "Додати станцію на карті" },
  pick_h: { en: "Where the plant stands", ro: "Unde va fi centrala", ru: "Где будет станция", uk: "Де буде станція" },
  pick_hint: {
    en: "Click the map where the plant will stand, or drag the pin. Your portfolio's other assets show as grey dots.",
    ro: "Apasă pe hartă unde va fi centrala sau trage marcajul. Celelalte active din portofoliu apar ca puncte gri.",
    ru: "Нажмите на карте, где будет станция, или перетащите метку. Остальные активы портфеля показаны серыми точками.",
    uk: "Натисніть на карті, де буде станція, або перетягніть мітку. Інші активи портфеля показано сірими точками.",
  },
  pick_search: { en: "Find a village, or paste coordinates", ro: "Caută o localitate sau lipește coordonate", ru: "Найти населённый пункт или вставить координаты", uk: "Знайти населений пункт або вставити координати" },
  pick_go: { en: "Find", ro: "Caută", ru: "Найти", uk: "Знайти" },
  pick_noplace: { en: "Nothing found for {q} in Moldova.", ro: "Nu s-a găsit {q} în Moldova.", ru: "В Молдове не найдено: {q}.", uk: "У Молдові не знайдено: {q}." },
  pick_geofail: { en: "The place search did not answer; try again in a moment.", ro: "Căutarea locurilor nu a răspuns; încearcă din nou peste puțin timp.", ru: "Поиск мест не ответил; повторите чуть позже.", uk: "Пошук місць не відповів; спробуйте трохи пізніше." },
  pick_map: { en: "Map", ro: "Hartă", ru: "Карта", uk: "Карта" },
  pick_sat: { en: "Satellite", ro: "Satelit", ru: "Спутник", uk: "Супутник" },
  pick_none: { en: "No point chosen yet.", ro: "Încă nu ai ales un punct.", ru: "Точка ещё не выбрана.", uk: "Точку ще не вибрано." },
  pick_at: { en: "Chosen point: {pos}", ro: "Punctul ales: {pos}", ru: "Выбранная точка: {pos}", uk: "Вибрана точка: {pos}" },
  pick_near: { en: "{x}, {d}", ro: "{x}, {d}", ru: "{x}, {d}", uk: "{x}, {d}" },
  pick_looking: { en: "Looking up the place...", ro: "Se caută locul...", ru: "Поиск места...", uk: "Пошук місця..." },
  pick_outside: {
    en: "This point is outside Moldova. The plant is modelled with Moldova's market, tariffs and permits.",
    ro: "Punctul este în afara Moldovei. Centrala este modelată cu piața, tarifele și autorizațiile din Moldova.",
    ru: "Эта точка за пределами Молдовы. Станция моделируется по рынку, тарифам и разрешениям Молдовы.",
    uk: "Ця точка за межами Молдови. Станцію моделюється за ринком, тарифами та дозволами Молдови.",
  },
  pick_set_loc: { en: "Set the locality to {x}", ro: "Setează localitatea: {x}", ru: "Указать населённый пункт: {x}", uk: "Вказати населений пункт: {x}" },
  pick_rescreen: { en: "Look up the wind and the sun at this point", ro: "Caută vântul și soarele în acest punct", ru: "Запросить ветер и солнце в этой точке", uk: "Запитати вітер і сонце в цій точці" },
  pick_moved: { en: "{km} km from where the plant was", ro: "la {km} km de locul anterior", ru: "в {km} км от прежнего места", uk: "за {km} км від попереднього місця" },
  pick_use: { en: "Use this point", ro: "Folosește acest punct", ru: "Использовать эту точку", uk: "Використати цю точку" },
  pick_create: { en: "Add the plant here", ro: "Adaugă centrala aici", ru: "Добавить станцию здесь", uk: "Додати станцію тут" },
  pick_cancel: { en: "Cancel", ro: "Renunță", ru: "Отмена", uk: "Скасувати" },
  pick_looking_up: { en: "Looking up the wind and the sun at the new site...", ro: "Se caută vântul și soarele pe noul amplasament...", ru: "Запрашиваются ветер и солнце на новой площадке...", uk: "Запитуються вітер і сонце на новому майданчику..." },
  moved_wind: { en: "The wind screening is for a point {km} km away: screen it again here.", ro: "Estimarea vântului este pentru un punct aflat la {km} km: estimează din nou aici.", ru: "Оценка ветра сделана для точки в {km} км: оцените заново здесь.", uk: "Оцінку вітру зроблено для точки за {km} км: оцініть знову тут." },
  moved_solar: { en: "The PVGIS yield is for a point {km} km away: look it up again here.", ro: "Randamentul PVGIS este pentru un punct aflat la {km} km: caută-l din nou aici.", ru: "Выработка PVGIS для точки в {km} км: запросите заново здесь.", uk: "Генерацію PVGIS отримано для точки за {km} км: запитайте знову тут." },
  c_wind: { en: "Wind", ro: "Vânt", ru: "Ветер", uk: "Вітер" },
  c_solar: { en: "Solar", ro: "Solar", ru: "Солнце", uk: "Сонце" },
  c_bess: { en: "Battery storage", ro: "Stocare în baterii", ru: "Накопители", uk: "Накопичувачі" },
  c_add: { en: "Add {x}", ro: "Adaugă {x}", ru: "Добавить: {x}", uk: "Додати: {x}" },
  c_remove: { en: "Remove", ro: "Elimină", ru: "Удалить", uk: "Видалити" },

  w_mw: { en: "Capacity, MW", ro: "Putere, MW", ru: "Мощность, МВт", uk: "Потужність, МВт" },
  w_turbines: { en: "Turbines", ro: "Turbine", ru: "Турбины", uk: "Турбіни" },
  w_hub: { en: "Hub height, m", ro: "Înălțimea butucului, m", ru: "Высота ступицы, м", uk: "Висота маточини, м" },
  w_shear: { en: "Wind shear exponent", ro: "Exponentul de forfecare", ru: "Показатель сдвига ветра", uk: "Показник зсуву вітру" },
  w_losses: { en: "Losses, %", ro: "Pierderi, %", ru: "Потери, %", uk: "Втрати, %" },
  w_rated: { en: "Rated speed of the curve, m/s", ro: "Viteza nominală a curbei, m/s", ru: "Номинальная скорость кривой, м/с", uk: "Номінальна швидкість кривої, м/с" },
  w_screen: { en: "Screen the wind here", ro: "Estimează vântul aici", ru: "Оценить ветер здесь", uk: "Оцінити вітер тут" },
  w_screen_again: { en: "Screen again", ro: "Estimează din nou", ru: "Оценить заново", uk: "Оцінити знову" },
  w_screening: {
    en: "Screening: {mwh} a year, capacity factor {cf}, mean wind at the hub {ws} ({src}, year {year}{clim}).",
    ro: "Estimare: {mwh} pe an, factor de capacitate {cf}, vânt mediu la butuc {ws} ({src}, anul {year}{clim}).",
    ru: "Оценка: {mwh} в год, коэффициент использования {cf}, средний ветер на ступице {ws} ({src}, год {year}{clim}).",
    uk: "Оцінка: {mwh} на рік, коефіцієнт використання {cf}, середній вітер на маточині {ws} ({src}, рік {year}{clim}).",
  },
  w_clim: { en: ", scaled to the 2001 to 2020 mean", ro: ", ajustat la media 2001 la 2020", ru: ", приведено к среднему за 2001 по 2020", uk: ", приведено до середнього за 2001 по 2020" },
  w_screen_note: {
    en: "A screening from reanalysis data on a grid of about 50 km and a generic power curve, uncertainty assumed at 15%. Banks lend on a measured study: enter its P50 and P90 below and they replace this.",
    ro: "O estimare din date de reanaliză pe o rețea de circa 50 km și o curbă de putere generică, cu incertitudine presupusă de 15%. Băncile creditează pe un studiu cu măsurători: introdu P50 și P90 din el mai jos și le înlocuiesc pe acestea.",
    ru: "Оценка по данным реанализа с сеткой около 50 км и типовой кривой мощности, неопределённость принята 15%. Банки кредитуют по исследованию с измерениями: введите его P50 и P90 ниже, и они заменят эту оценку.",
    uk: "Оцінка за даними реаналізу з сіткою близько 50 км і типовою кривою потужності, невизначеність прийнято 15%. Банки кредитують за дослідженням із вимірюваннями: введіть його P50 і P90 нижче, і вони замінять цю оцінку.",
  },
  // the same note for the bank's documents: said to the reader, not to the user filling the form
  w_screen_doc: {
    en: "The wind figures are a screening from reanalysis data on a grid of about 50 km with a generic power curve, uncertainty assumed at 15%. An independent study with on-site measurements will replace them.",
    ro: "Cifrele de vânt sunt o estimare din date de reanaliză pe o rețea de circa 50 km, cu o curbă de putere generică și o incertitudine presupusă de 15%. Un studiu independent cu măsurători pe amplasament le va înlocui.",
    ru: "Цифры ветра являются оценкой по данным реанализа с сеткой около 50 км и типовой кривой мощности, неопределённость принята 15%. Их заменит независимое исследование с измерениями на площадке.",
    uk: "Цифри вітру є оцінкою за даними реаналізу з сіткою близько 50 км і типовою кривою потужності, невизначеність прийнято 15%. Їх замінить незалежне дослідження з вимірюваннями на майданчику.",
  },
  w_no_data: { en: "No wind estimate yet.", ro: "Încă nu există o estimare a vântului.", ru: "Оценки ветра пока нет.", uk: "Оцінки вітру поки немає." },
  w_failed: { en: "The wind data did not answer; try again in a moment.", ro: "Datele de vânt nu au răspuns; încearcă din nou peste puțin timp.", ru: "Данные о ветре не ответили; повторите чуть позже.", uk: "Дані про вітер не відповіли; спробуйте трохи пізніше." },
  study_h: { en: "Independent study", ro: "Studiul independent", ru: "Независимое исследование", uk: "Незалежне дослідження" },
  s_p50: { en: "P50, MWh a year", ro: "P50, MWh pe an", ru: "P50, МВт·ч в год", uk: "P50, МВт·год на рік" },
  s_p90: { en: "P90, MWh a year", ro: "P90, MWh pe an", ru: "P90, МВт·ч в год", uk: "P90, МВт·год на рік" },
  s_by: { en: "Prepared by", ro: "Întocmit de", ru: "Подготовил", uk: "Підготував" },
  s_date: { en: "Date", ro: "Data", ru: "Дата", uk: "Дата" },
  s_used: { en: "The study's figures are used.", ro: "Se folosesc cifrele studiului.", ru: "Используются цифры исследования.", uk: "Використовуються цифри дослідження." },
  // ---- reading a study from its PDF (components/portfolio/StudyReader.jsx)
  rd_btn: { en: "Read the study from a PDF", ro: "Citește studiul din PDF", ru: "Прочитать исследование из PDF", uk: "Прочитати дослідження з PDF" },
  rd_hint: {
    en: "Your browser finds the pages with the energy results and only their text is sent to be read; the file itself is not stored. You check every value before it is used.",
    ro: "Browserul găsește paginile cu rezultatele de producție și doar textul lor este trimis spre citire; fișierul nu se păstrează. Verifici fiecare valoare înainte să fie folosită.",
    ru: "Браузер находит страницы с результатами выработки, и на чтение отправляется только их текст; сам файл не сохраняется. Вы проверяете каждое значение перед использованием.",
    uk: "Браузер знаходить сторінки з результатами генерації, і на читання надсилається лише їхній текст; сам файл не зберігається. Ви перевіряєте кожне значення перед використанням.",
  },
  rd_opening: { en: "Opening the PDF...", ro: "Se deschide PDF-ul...", ru: "Открывается PDF...", uk: "Відкривається PDF..." },
  rd_reading: { en: "Reading pages {pages} of {total}...", ro: "Se citesc paginile {pages} din {total}...", ru: "Читаются страницы {pages} из {total}...", uk: "Читаються сторінки {pages} з {total}..." },
  rd_scan: {
    en: "This PDF has no text layer (it is a scan). Type the pages with the energy results, for example 4-9:",
    ro: "Acest PDF nu are text (e scanat). Scrie paginile cu rezultatele de producție, de exemplu 4-9:",
    ru: "В этом PDF нет текста (это скан). Укажите страницы с результатами выработки, например 4-9:",
    uk: "У цьому PDF немає тексту (це скан). Вкажіть сторінки з результатами генерації, наприклад 4-9:",
  },
  rd_scan_go: { en: "Read these pages", ro: "Citește aceste pagini", ru: "Прочитать эти страницы", uk: "Прочитати ці сторінки" },
  rd_range_bad: {
    en: "Type pages like 4-9 or 4, 7, 12: at most 15, within the {total} of the file.",
    ro: "Scrie pagini ca 4-9 sau 4, 7, 12: cel mult 15, din cele {total} ale fișierului.",
    ru: "Укажите страницы вида 4-9 или 4, 7, 12: не более 15, в пределах {total} страниц файла.",
    uk: "Вкажіть сторінки на кшталт 4-9 або 4, 7, 12: не більше 15, у межах {total} сторінок файлу.",
  },
  rd_err_not_configured: { en: "Reading studies is not switched on yet: add ANTHROPIC_API_KEY in Vercel.", ro: "Citirea studiilor nu e pornită încă: adaugă ANTHROPIC_API_KEY în Vercel.", ru: "Чтение исследований ещё не включено: добавьте ANTHROPIC_API_KEY в Vercel.", uk: "Читання досліджень ще не ввімкнено: додайте ANTHROPIC_API_KEY у Vercel." },
  rd_err_not_study: { en: "This does not look like an energy yield study. Enter the figures by hand.", ro: "Nu pare a fi un studiu de producție. Introdu cifrele manual.", ru: "Это не похоже на исследование выработки. Введите цифры вручную.", uk: "Це не схоже на дослідження генерації. Введіть цифри вручну." },
  rd_err_no_p50: { en: "No net P50 was found in the pages read. If the results are elsewhere, enter them by hand.", ro: "Nu s-a găsit un P50 net în paginile citite. Dacă rezultatele sunt în altă parte, introdu-le manual.", ru: "В прочитанных страницах нет чистого P50. Если результаты в другом месте, введите их вручную.", uk: "У прочитаних сторінках немає чистого P50. Якщо результати в іншому місці, введіть їх вручну." },
  rd_err_too_large: { en: "Those pages are too large to send; choose fewer pages.", ro: "Paginile sunt prea mari pentru trimitere; alege mai puține pagini.", ru: "Страницы слишком велики для отправки; выберите меньше страниц.", uk: "Сторінки завеликі для надсилання; виберіть менше сторінок." },
  rd_err_rate: { en: "Too many readings at once; try again in a minute.", ro: "Prea multe citiri deodată; încearcă din nou peste un minut.", ru: "Слишком много чтений сразу; повторите через минуту.", uk: "Забагато читань одночасно; спробуйте за хвилину." },
  rd_err_auth: { en: "The AI key was rejected; check ANTHROPIC_API_KEY.", ro: "Cheia AI a fost respinsă; verifică ANTHROPIC_API_KEY.", ru: "Ключ AI отклонён; проверьте ANTHROPIC_API_KEY.", uk: "Ключ AI відхилено; перевірте ANTHROPIC_API_KEY." },
  rd_err_declined: { en: "The reader declined this file. Enter the figures by hand.", ro: "Cititorul a refuzat acest fișier. Introdu cifrele manual.", ru: "Файл не был прочитан. Введите цифры вручную.", uk: "Файл не було прочитано. Введіть цифри вручну." },
  rd_err_open: { en: "The PDF could not be opened. Is it protected by a password?", ro: "PDF-ul nu a putut fi deschis. Are parolă?", ru: "PDF не удалось открыть. Он защищён паролем?", uk: "PDF не вдалося відкрити. Він захищений паролем?" },
  rd_err_failed: { en: "The study could not be read this time; try again or enter the figures by hand.", ro: "Studiul nu a putut fi citit acum; încearcă din nou sau introdu cifrele manual.", ru: "Сейчас не удалось прочитать исследование; повторите или введите цифры вручную.", uk: "Зараз не вдалося прочитати дослідження; спробуйте ще раз або введіть цифри вручну." },
  rd_found: { en: "Read from {file}. Tick what to use; each value shows where it was found.", ro: "Citit din {file}. Bifează ce folosești; fiecare valoare arată unde a fost găsită.", ru: "Прочитано из {file}. Отметьте, что использовать; у каждого значения указано, где оно найдено.", uk: "Прочитано з {file}. Позначте, що використати; біля кожного значення вказано, де його знайдено." },
  rd_col_value: { en: "Value", ro: "Valoare", ru: "Значение", uk: "Значення" },
  rd_page: { en: "page {p}", ro: "pagina {p}", ru: "стр. {p}", uk: "стор. {p}" },
  rd_ok: { en: "quote found on the page", ro: "citat găsit pe pagină", ru: "цитата найдена на странице", uk: "цитату знайдено на сторінці" },
  rd_quote_only: { en: "quote found, but not this number: check it", ro: "citat găsit, dar nu și acest număr: verifică", ru: "цитата найдена, но без этого числа: проверьте", uk: "цитату знайдено, але без цього числа: перевірте" },
  rd_unverified: { en: "quote not found on that page: check it", ro: "citatul nu apare pe acea pagină: verifică", ru: "цитаты нет на этой странице: проверьте", uk: "цитати немає на цій сторінці: перевірте" },
  rd_scan_src: { en: "read from the scan: check it", ro: "citit din scan: verifică", ru: "прочитано со скана: проверьте", uk: "прочитано зі скану: перевірте" },
  rd_info: { en: "for information", ro: "informativ", ru: "для информации", uk: "для інформації" },
  rd_p90_pick: { en: "use this P90", ro: "folosește acest P90", ru: "использовать этот P90", uk: "використати цей P90" },
  rd_apply: { en: "Use the ticked values", ro: "Folosește valorile bifate", ru: "Использовать отмеченные", uk: "Використати позначені" },
  rd_cancel: { en: "Discard", ro: "Renunță", ru: "Отменить", uk: "Скасувати" },
  rd_applied: { en: "Applied: the study's figures now drive this plant's energy.", ro: "Aplicat: cifrele studiului dau acum producția centralei.", ru: "Применено: цифры исследования теперь задают выработку станции.", uk: "Застосовано: цифри дослідження тепер задають генерацію станції." },
  rd_notes: { en: "Reader's note: {x}", ro: "Nota cititorului: {x}", ru: "Примечание: {x}", uk: "Примітка: {x}" },
  rf_p50: { en: "Net P50, MWh a year", ro: "P50 net, MWh pe an", ru: "Чистый P50, МВт·ч в год", uk: "Чистий P50, МВт·год на рік" },
  rf_p90_1y: { en: "P90 over 1 year, MWh a year", ro: "P90 la 1 an, MWh pe an", ru: "P90 за 1 год, МВт·ч в год", uk: "P90 за 1 рік, МВт·год на рік" },
  rf_p90_10y: { en: "P90 over 10 years, MWh a year", ro: "P90 la 10 ani, MWh pe an", ru: "P90 за 10 лет, МВт·ч в год", uk: "P90 за 10 років, МВт·год на рік" },
  rf_capacity: { en: "Capacity in the study", ro: "Puterea din studiu", ru: "Мощность в исследовании", uk: "Потужність у дослідженні" },
  rf_meanWind: { en: "Mean wind at the hub, m/s", ro: "Vânt mediu la butuc, m/s", ru: "Средний ветер на ступице, м/с", uk: "Середній вітер на маточині, м/с" },
  rf_losses: { en: "Total losses, %", ro: "Pierderi totale, %", ru: "Общие потери, %", uk: "Загальні втрати, %" },
  rf_uncertainty: { en: "Total uncertainty over 1 year, %", ro: "Incertitudine totală la 1 an, %", ru: "Общая неопределённость за 1 год, %", uk: "Загальна невизначеність за 1 рік, %" },
  rf_model: { en: "Turbine model", ro: "Modelul turbinei", ru: "Модель турбины", uk: "Модель турбіни" },
  rf_measurement: { en: "On-site measurement", ro: "Măsurători pe amplasament", ru: "Измерения на площадке", uk: "Вимірювання на майданчику" },
  rw_p90_high: { en: "A P90 above the P50 was read; it was left out.", ro: "S-a citit un P90 mai mare decât P50; a fost lăsat deoparte.", ru: "Прочитан P90 выше P50; он не учтён.", uk: "Прочитано P90 вище за P50; його не враховано." },
  rw_tech: { en: "The document does not read as a study for this part of the plant: check it is the right file.", ro: "Documentul nu pare un studiu pentru această parte a centralei: verifică dacă e fișierul potrivit.", ru: "Документ не похож на исследование для этой части станции: проверьте файл.", uk: "Документ не схожий на дослідження для цієї частини станції: перевірте файл." },
  rw_cap: { en: "The study is for {s}; the plant is set at {p}. Check that it is the same layout.", ro: "Studiul este pentru {s}; centrala are setat {p}. Verifică dacă e aceeași configurație.", ru: "Исследование для {s}; у станции задано {p}. Проверьте, что это та же компоновка.", uk: "Дослідження для {s}; у станції задано {p}. Перевірте, що це та сама компоновка." },
  rw_cf: { en: "The P50 gives a capacity factor of {cf}, outside the usual {lo} to {hi}: check the unit and the page.", ro: "P50 dă un factor de capacitate de {cf}, în afara intervalului obișnuit {lo} la {hi}: verifică unitatea și pagina.", ru: "P50 даёт коэффициент использования {cf}, вне обычных {lo} до {hi}: проверьте единицы и страницу.", uk: "P50 дає коефіцієнт використання {cf}, поза звичними {lo} до {hi}: перевірте одиниці та сторінку." },
  rw_unchecked: { en: "{n} values could not be matched to their page: check them before using them.", ro: "{n} valori nu au putut fi potrivite cu pagina lor: verifică-le înainte să le folosești.", ru: "Значений, не сверенных со страницей: {n}. Проверьте их перед использованием.", uk: "Значень, не звірених зі сторінкою: {n}. Перевірте їх перед використанням." },
  rw_unchecked_one: { en: "1 value could not be matched to its page: check it before using it.", ro: "O valoare nu a putut fi potrivită cu pagina ei: verific-o înainte să o folosești.", ru: "Одно значение не сверено со страницей: проверьте его перед использованием.", uk: "Одне значення не звірено зі сторінкою: перевірте його перед використанням." },
  rw_no_p90: { en: "No P90 was found; the bank will ask for it.", ro: "Nu s-a găsit P90; banca îl va cere.", ru: "P90 не найден; банк его запросит.", uk: "P90 не знайдено; банк його запитає." },
  rw_scan: { en: "Read from a scan: there is no text to compare the quotes against, so check each value against the page.", ro: "Citit dintr-un scan: nu există text cu care să se compare citatele, deci verifică fiecare valoare pe pagină.", ru: "Прочитано со скана: сверить цитаты не с чем, поэтому проверьте каждое значение по странице.", uk: "Прочитано зі скану: звірити цитати немає з чим, тож перевірте кожне значення за сторінкою." },
  p90_basis_1y: { en: "P90 over 1 year", ro: "P90 la 1 an", ru: "P90 за 1 год", uk: "P90 за 1 рік" },
  p90_basis_10y: { en: "P90 over 10 years", ro: "P90 la 10 ani", ru: "P90 за 10 лет", uk: "P90 за 10 років" },
  sol_mwp: { en: "Capacity, MWp", ro: "Putere, MWp", ru: "Мощность, МВт пик", uk: "Потужність, МВт пік" },
  sol_yield: { en: "Yield, kWh per kWp a year", ro: "Randament, kWh pe kWp pe an", ru: "Выработка, кВт·ч на кВт пик в год", uk: "Генерація, кВт·год на кВт пік на рік" },
  sol_lookup: { en: "Look it up (PVGIS)", ro: "Caută-l (PVGIS)", ru: "Найти (PVGIS)", uk: "Знайти (PVGIS)" },
  sol_failed: { en: "PVGIS did not answer; try again in a moment.", ro: "PVGIS nu a răspuns; încearcă din nou peste puțin timp.", ru: "PVGIS не ответил; повторите чуть позже.", uk: "PVGIS не відповів; спробуйте трохи пізніше." },
  b_mw: { en: "Power, MW", ro: "Putere, MW", ru: "Мощность, МВт", uk: "Потужність, МВт" },
  b_mwh: { en: "Energy, MWh", ro: "Energie, MWh", ru: "Ёмкость, МВт·ч", uk: "Ємність, МВт·год" },
  b_rev: { en: "Contracted revenue, EUR per MW a year", ro: "Venit contractat, EUR pe MW pe an", ru: "Выручка по договору, EUR за МВт в год", uk: "Виручка за договором, EUR за МВт на рік" },
  b_years: { en: "Storage contract, years", ro: "Contractul stocării, ani", ru: "Договор накопителя, лет", uk: "Договір накопичувача, років" },
  b_years_v: { en: "{n} years", ro: "{n} ani", ru: "{n} г.", uk: "{n} р." },
  b_note: {
    en: "Storage earns only what a contract gives it (balancing or capacity), for the contract's years; no arbitrage is assumed.",
    ro: "Stocarea câștigă doar ce îi dă un contract (echilibrare sau capacitate), pe durata contractului; nu se presupune arbitraj.",
    ru: "Накопитель зарабатывает только то, что даёт договор (балансирование или мощность), на срок договора; арбитраж не предполагается.",
    uk: "Накопичувач заробляє лише те, що дає договір (балансування чи потужність), на строк договору; арбітраж не передбачається.",
  },

  rev_h: { en: "Revenue", ro: "Venit", ru: "Выручка", uk: "Виручка" },
  rev_kind: { en: "Sold under", ro: "Vândut prin", ru: "Продажа по", uk: "Продаж за" },
  rk_auction: { en: "Auction contract", ro: "Contract din licitație", ru: "Аукционный договор", uk: "Аукціонний договір" },
  rk_ppa: { en: "PPA", ro: "PPA", ru: "PPA", uk: "PPA" },
  rk_merchant: { en: "Market only", ro: "Doar piață", ru: "Только рынок", uk: "Лише ринок" },
  rev_price: { en: "Price, EUR/MWh", ro: "Preț, EUR/MWh", ru: "Цена, EUR/МВт·ч", uk: "Ціна, EUR/МВт·год" },
  rev_years: { en: "Contract years", ro: "Ani de contract", ru: "Лет по договору", uk: "Років за договором" },
  rev_index: { en: "Indexation, % a year", ro: "Indexare, % pe an", ru: "Индексация, % в год", uk: "Індексація, % на рік" },
  rev_after: { en: "After the contract, EUR/MWh (assumption)", ro: "După contract, EUR/MWh (ipoteză)", ru: "После договора, EUR/МВт·ч (допущение)", uk: "Після договору, EUR/МВт·год (припущення)" },
  rev_cur: { en: "Contract currency", ro: "Moneda contractului", ru: "Валюта договора", uk: "Валюта договору" },
  rev_local: { en: "Lei", ro: "Lei", ru: "Леи", uk: "Леї" },
  rev_hint: {
    en: "The second auction's weighted average was {p}; use the price you were awarded or signed.",
    ro: "Media ponderată a celei de-a doua licitații a fost {p}; folosește prețul atribuit sau semnat.",
    ru: "Средневзвешенная цена второго аукциона: {p}; используйте присуждённую или подписанную цену.",
    uk: "Середньозважена ціна другого аукціону: {p}; використайте присуджену або підписану ціну.",
  },

  cost_h: { en: "Costs (your assumptions until quotes arrive)", ro: "Costuri (ipotezele tale până vin ofertele)", ru: "Затраты (ваши допущения до получения предложений)", uk: "Витрати (ваші припущення до отримання пропозицій)" },
  k_wind: { en: "Wind, EUR per kW", ro: "Vânt, EUR pe kW", ru: "Ветер, EUR за кВт", uk: "Вітер, EUR за кВт" },
  k_solar: { en: "Solar, EUR per kWp", ro: "Solar, EUR pe kWp", ru: "Солнце, EUR за кВт пик", uk: "Сонце, EUR за кВт пік" },
  k_bess: { en: "Storage, EUR per kWh", ro: "Stocare, EUR pe kWh", ru: "Накопители, EUR за кВт·ч", uk: "Накопичувачі, EUR за кВт·год" },
  k_grid: { en: "Grid connection, EUR", ro: "Racordare, EUR", ru: "Подключение к сети, EUR", uk: "Приєднання до мережі, EUR" },
  k_dev: { en: "Development, % of the above", ro: "Dezvoltare, % din cele de mai sus", ru: "Разработка, % от суммы выше", uk: "Розробка, % від суми вище" },
  k_opw: { en: "Wind O&M, EUR per kW a year", ro: "Mentenanță vânt, EUR pe kW pe an", ru: "Обслуживание ветра, EUR за кВт в год", uk: "Обслуговування вітру, EUR за кВт на рік" },
  k_ops: { en: "Solar O&M, EUR per kWp a year", ro: "Mentenanță solar, EUR pe kWp pe an", ru: "Обслуживание солнца, EUR за кВт пик в год", uk: "Обслуговування сонця, EUR за кВт пік на рік" },
  k_opb: { en: "Storage O&M, EUR per kWh a year", ro: "Mentenanță stocare, EUR pe kWh pe an", ru: "Обслуживание накопителей, EUR за кВт·ч в год", uk: "Обслуговування накопичувачів, EUR за кВт·год на рік" },
  k_land: { en: "Land lease, EUR a year", ro: "Arenda terenului, EUR pe an", ru: "Аренда земли, EUR в год", uk: "Оренда землі, EUR на рік" },
  k_ins: { en: "Insurance, % of capex a year", ro: "Asigurare, % din capex pe an", ru: "Страхование, % капзатрат в год", uk: "Страхування, % капвитрат на рік" },

  res_h: { en: "What it comes to", ro: "Ce iese", ru: "Что получается", uk: "Що виходить" },
  r_energy: { en: "Energy a year, P50 and P90", ro: "Energie pe an, P50 și P90", ru: "Выработка в год, P50 и P90", uk: "Генерація на рік, P50 і P90" },
  r_capex: { en: "Capex", ro: "Capex", ru: "Капзатраты", uk: "Капвитрати" },
  r_lcoe: { en: "Cost per MWh produced (LCOE)", ro: "Cost pe MWh produs (LCOE)", ru: "Стоимость МВт·ч (LCOE)", uk: "Вартість МВт·год (LCOE)" },
  r_dscr: { en: "Lowest debt cover, P50", ro: "Cea mai mică acoperire a datoriei, P50", ru: "Минимальное покрытие долга, P50", uk: "Мінімальне покриття боргу, P50" },
  hr_energy_pos: { en: "Energy could fall {x} before cover reaches {t}.", ro: "Producția poate scădea cu {x} până când acoperirea ajunge la {t}.", ru: "Выработка может упасть на {x}, прежде чем покрытие дойдёт до {t}.", uk: "Генерація може впасти на {x}, перш ніж покриття дійде до {t}." },
  hr_energy_neg: { en: "Energy must be {x} higher for cover to reach {t}.", ro: "Producția trebuie să fie cu {x} mai mare ca acoperirea să ajungă la {t}.", ru: "Выработка должна быть на {x} выше, чтобы покрытие дошло до {t}.", uk: "Генерація має бути на {x} вищою, щоб покриття дійшло до {t}." },
  hr_capex_pos: { en: "Capex could rise {x} before cover reaches {t}.", ro: "Capex-ul poate crește cu {x} până când acoperirea ajunge la {t}.", ru: "Капзатраты могут вырасти на {x}, прежде чем покрытие дойдёт до {t}.", uk: "Капвитрати можуть зрости на {x}, перш ніж покриття дійде до {t}." },
  hr_capex_neg: { en: "Capex must be {x} lower for cover to reach {t}.", ro: "Capex-ul trebuie să fie cu {x} mai mic ca acoperirea să ajungă la {t}.", ru: "Капзатраты должны быть на {x} ниже, чтобы покрытие дошло до {t}.", uk: "Капвитрати мають бути на {x} нижчими, щоб покриття дійшло до {t}." },
  hr_none: { en: "No debt in this structure, so there is no cover test.", ro: "Structura nu are datorie, deci nu există test de acoperire.", ru: "В этой структуре нет долга, поэтому проверки покрытия нет.", uk: "У цій структурі немає боргу, тому перевірки покриття немає." },
  src_screening: { en: "screening", ro: "estimare", ru: "оценка", uk: "оцінка" },
  src_study: { en: "study", ro: "studiu", ru: "исследование", uk: "дослідження" },
  src_pvgis: { en: "PVGIS", ro: "PVGIS", ru: "PVGIS", uk: "PVGIS" },
  src_none: { en: "missing", ro: "lipsește", ru: "нет данных", uk: "немає даних" },

  // ---- permits, EVO-ready
  permits_h: { en: "Permits and papers, ready for EVO", ro: "Autorizații și acte, pregătite pentru EVO", ru: "Разрешения и документы, готовые к EVO", uk: "Дозволи та документи, готові до EVO" },
  permits_p: {
    en: "Each item has a status, a responsible person, a reference and dates, the way the EVO portal will track them. Items that do not wait on another can run in parallel.",
    ro: "Fiecare act are un stadiu, un responsabil, un număr și date, așa cum le va urmări portalul EVO. Actele care nu depind de altele pot merge în paralel.",
    ru: "У каждого пункта есть статус, ответственный, номер и даты, как их будет вести портал EVO. Пункты, не зависящие от других, идут параллельно.",
    uk: "Кожен пункт має статус, відповідального, номер і дати, як їх вестиме портал EVO. Пункти, що не залежать від інших, ідуть паралельно.",
  },
  p_progress: { en: "{done} of {total} done", ro: "{done} din {total} gata", ru: "готово {done} из {total}", uk: "готово {done} з {total}" },
  p_ready: { en: "Can start now: {x}", ro: "Pot începe acum: {x}", ru: "Можно начать сейчас: {x}", uk: "Можна почати зараз: {x}" },
  p_status: { en: "Status", ro: "Stadiu", ru: "Статус", uk: "Статус" },
  ps_todo: { en: "To do", ro: "De făcut", ru: "Сделать", uk: "Зробити" },
  ps_in_progress: { en: "In progress", ro: "În lucru", ru: "В работе", uk: "У роботі" },
  ps_done: { en: "Done", ro: "Gata", ru: "Готово", uk: "Готово" },
  ps_na: { en: "Not needed", ro: "Nu e necesar", ru: "Не требуется", uk: "Не потрібно" },
  p_waits: { en: "waits for {x}", ro: "așteaptă: {x}", ru: "ждёт: {x}", uk: "чекає: {x}" },
  p_ready_one: { en: "can start now", ro: "poate începe acum", ru: "можно начать", uk: "можна почати" },
  p_overdue: { en: "overdue", ro: "întârziat", ru: "просрочено", uk: "прострочено" },
  pf_by: { en: "Responsible", ro: "Responsabil", ru: "Ответственный", uk: "Відповідальний" },
  pf_ref: { en: "Reference no.", ro: "Număr", ru: "Номер", uk: "Номер" },
  pf_submitted: { en: "Submitted", ro: "Depus", ru: "Подано", uk: "Подано" },
  pf_due: { en: "Due", ro: "Termen", ru: "Срок", uk: "Строк" },
  pm_land: { en: "Land rights (ownership or lease)", ro: "Drepturi asupra terenului (proprietate sau arendă)", ru: "Права на землю (собственность или аренда)", uk: "Права на землю (власність або оренда)" },
  pm_other: { en: "Other documents", ro: "Alte documente", ru: "Другие документы", uk: "Інші документи" },
  pm_urbanism: { en: "Urban planning certificate", ro: "Certificat de urbanism", ru: "Градостроительный сертификат", uk: "Містобудівний сертифікат" },
  pm_eia: { en: "Environmental impact assessment and decision", ro: "Evaluarea impactului asupra mediului și decizia", ru: "Оценка воздействия на окружающую среду и решение", uk: "Оцінка впливу на довкілля та рішення" },
  pm_grid: { en: "Grid connection", ro: "Racordarea la rețea", ru: "Подключение к сети", uk: "Підключення до мережі" },
  pm_yield: { en: "Independent energy yield study (P50/P90)", ro: "Studiu independent de producție (P50/P90)", ru: "Независимое исследование выработки (P50/P90)", uk: "Незалежне дослідження генерації (P50/P90)" },
  pm_design: { en: "Technical design", ro: "Proiectul tehnic", ru: "Технический проект", uk: "Технічний проєкт" },
  pm_building: { en: "Construction permit", ro: "Autorizația de construire", ru: "Разрешение на строительство", uk: "Дозвіл на будівництво" },
  pm_licence: { en: "ANRE production licence, where required", ro: "Licența ANRE de producere, unde e cerută", ru: "Лицензия ANRE на производство, если требуется", uk: "Ліцензія ANRE на виробництво, якщо потрібна" },
  gs_request: { en: "Connection request", ro: "Cererea de racordare", ru: "Заявка на подключение", uk: "Заявка на підключення" },
  gs_approval: { en: "Connection approval (conditions and point)", ro: "Avizul de racordare (condiții și punct)", ru: "Разрешение на подключение (условия и точка)", uk: "Дозвіл на підключення (умови й точка)" },
  gs_contract: { en: "Connection contract", ro: "Contractul de racordare", ru: "Договор на подключение", uk: "Договір на підключення" },
  gs_works: { en: "Connection design and works", ro: "Proiectarea și lucrările de racordare", ru: "Проект и работы по подключению", uk: "Проєкт і роботи з підключення" },
  gs_energised: { en: "Energisation", ro: "Punerea sub tensiune", ru: "Подача напряжения", uk: "Подача напруги" },
  p_steps: { en: "Connection steps", ro: "Pașii racordării", ru: "Этапы подключения", uk: "Етапи підключення" },
  p_steps_h: { en: "The status follows the steps.", ro: "Stadiul urmează pașii.", ru: "Статус следует за этапами.", uk: "Статус іде за етапами." },
  pm_contract: { en: "Revenue contract (auction contract or PPA)", ro: "Contractul de vânzare (din licitație sau PPA)", ru: "Договор продажи (по аукциону или PPA)", uk: "Договір продажу (за аукціоном або PPA)" },
  pm_epc: { en: "EPC contract", ro: "Contractul EPC", ru: "Договор EPC", uk: "Договір EPC" },
  pm_om: { en: "O&M contract", ro: "Contractul de operare și mentenanță", ru: "Договор эксплуатации и обслуживания", uk: "Договір експлуатації та обслуговування" },
  pm_insurance: { en: "Insurance (construction and operation)", ro: "Asigurarea (construcție și exploatare)", ru: "Страхование (строительство и эксплуатация)", uk: "Страхування (будівництво та експлуатація)" },

  // ---- the asset table and the report
  r_tech_plants: {
    en: "Plants are modelled on their own (section {n}): each source's P50 and P90 come from its study, the public-data screening or PVGIS, with the uncertainty shown there.",
    ro: "Centralele sunt modelate separat (secțiunea {n}): P50 și P90 ale fiecărei surse vin din studiul ei, din estimarea pe date publice sau din PVGIS, cu incertitudinea arătată acolo.",
    ru: "Станции моделируются отдельно (раздел {n}): P50 и P90 каждого источника берутся из его исследования, оценки по открытым данным или PVGIS, с указанной там неопределённостью.",
    uk: "Станції моделюються окремо (розділ {n}): P50 і P90 кожного джерела беруться з його дослідження, оцінки за відкритими даними або PVGIS, з наведеною там невизначеністю.",
  },
  r_source: { en: "Source", ro: "Sursa", ru: "Источник", uk: "Джерело" },
  r_cap: { en: "Capacity", ro: "Putere", ru: "Мощность", uk: "Потужність" },
  hr_energy_k: { en: "Energy headroom", ro: "Marja de producție", ru: "Запас по выработке", uk: "Запас за генерацією" },
  hr_capex_k: { en: "Capex headroom", ro: "Marja de capex", ru: "Запас по капзатратам", uk: "Запас за капвитратами" },
  plant_tag: { en: "Plant", ro: "Centrală", ru: "Станция", uk: "Станція" },
  mix_line: { en: "{parts}", ro: "{parts}", ru: "{parts}", uk: "{parts}" },
  r_plants: { en: "Plants: technical basis, revenue and permits", ro: "Centrale: baza tehnică, venitul și autorizațiile", ru: "Станции: техническая основа, выручка и разрешения", uk: "Станції: технічна основа, виручка та дозволи" },
  r_map: { en: "Where the assets are", ro: "Unde sunt activele", ru: "Где находятся объекты", uk: "Де розташовані об’єкти" },
  r_map_list: { en: "Each number on the map is the asset's row below and in the asset table.", ro: "Fiecare număr de pe hartă este rândul activului de mai jos și din tabelul activelor.", ru: "Каждый номер на карте соответствует строке объекта ниже и в таблице объектов.", uk: "Кожен номер на мапі відповідає рядку об’єкта нижче та в таблиці об’єктів." },
  r_loc_approx: { en: "approximate", ro: "aproximativ", ru: "приблизительно", uk: "приблизно" },
  r_wind_src: { en: "Wind data: {src}.", ro: "Date de vânt: {src}.", ru: "Данные о ветре: {src}.", uk: "Дані про вітер: {src}." },
};

export const PT = T;

/** Where a study's figures come from, for a document: "DNV, 2026-05-01, page 23"; empty when nothing is recorded. */
export function studyCite(study, lang = "en") {
  if (!study) return "";
  const parts = [study.by, study.date].filter(Boolean);
  if (study.pages?.p50) parts.push(plt("rd_page", lang, { p: study.pages.p50 }));
  return parts.join(", ");
}

/** The P90 horizon the studies' figures are for, when every study of the plant states the same one. */
export function p90BasisNote(plant, lang = "en") {
  const bases = [plant?.wind?.study, plant?.solar?.study].filter((s) => s && s.p50Mwh > 0).map((s) => s.p90Basis || "");
  return bases.length && bases.every((b) => b && b === bases[0]) ? plt("p90_basis_" + bases[0], lang) : "";
}

export function plt(key, lang = "en", vars = null) {
  const e = (vars && Number(vars.n) === 1 && T[key + "_one"]) || T[key];
  let s = e ? (e[lang] ?? e.en) : key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split("{" + k + "}").join(String(v ?? ""));
  return s;
}
