// lib/portfolioText.js — every word of the portfolio module, in four languages,
// in one place: the page, the PDF report, the Excel workbook and the data room
// read the same table, so a label can never differ between them. Module-local
// (not lib/i18n.js) because this is a B2B surface that grows on its own.
//
// pt(key, lang, {n: 3}) fills {n}. Missing languages fall back to English; the
// test in lib/portfolioText.test.js fails if any key lacks one of the four.
const T = {
  // ---- navigation and lists
  nav: { en: "Portfolios", ro: "Portofolii", ru: "Портфели", uk: "Портфелі" },
  title: { en: "Portfolios", ro: "Portofolii", ru: "Портфели", uk: "Портфелі" },
  sub: { en: "Group quotes into one investment for a lender or fund: totals, blended return, debt cover under stress, and the papers a bank asks for.", ro: "Grupează ofertele într-o singură investiție pentru o bancă sau un fond: totaluri, randament combinat, acoperirea datoriei sub stres și actele cerute de bancă.", ru: "Объедините расчёты в одну инвестицию для банка или фонда: итоги, совокупная доходность, покрытие долга при стрессе и документы, которые просит банк.", uk: "Об’єднайте розрахунки в одну інвестицію для банку чи фонду: підсумки, сукупна дохідність, покриття боргу за стресу та документи, які просить банк." },
  new: { en: "New portfolio", ro: "Portofoliu nou", ru: "Новый портфель", uk: "Новий портфель" },
  new_name_ph: { en: "e.g. Odesa region, 10 sites", ro: "ex. Regiunea Odesa, 10 situri", ru: "напр. Одесская область, 10 объектов", uk: "напр. Одеська область, 10 об’єктів" },
  empty_list: { en: "No portfolios yet. Create one, then add the quotes that belong together.", ro: "Niciun portofoliu încă. Creează unul, apoi adaugă ofertele care merg împreună.", ru: "Портфелей пока нет. Создайте один и добавьте расчёты, которые идут вместе.", uk: "Портфелів поки немає. Створіть один і додайте розрахунки, які йдуть разом." },
  n_assets: { en: "{n} assets", ro: "{n} active", ru: "объектов: {n}", uk: "об’єктів: {n}" },
  back: { en: "Portfolios", ro: "Portofolii", ru: "Портфели", uk: "Портфелі" },
  needs_db: { en: "Portfolios need a database update: run supabase/add-portfolios.sql (it is part of run-pending-2026-09-29.sql).", ro: "Portofoliile cer o actualizare a bazei de date: rulează supabase/add-portfolios.sql (face parte din run-pending-2026-09-29.sql).", ru: "Для портфелей нужно обновить базу данных: выполните supabase/add-portfolios.sql (он входит в run-pending-2026-09-29.sql).", uk: "Для портфелів потрібно оновити базу даних: виконайте supabase/add-portfolios.sql (він входить до run-pending-2026-09-29.sql)." },
  not_found: { en: "Portfolio not found.", ro: "Portofoliul nu a fost găsit.", ru: "Портфель не найден.", uk: "Портфель не знайдено." },
  market: { en: "Market", ro: "Piață", ru: "Рынок", uk: "Ринок" },
  market_md: { en: "Moldova", ro: "Moldova", ru: "Молдова", uk: "Молдова" },
  market_ua: { en: "Ukraine", ro: "Ucraina", ru: "Украина", uk: "Україна" },
  all_eur: { en: "All figures in EUR.", ro: "Toate sumele în EUR.", ru: "Все суммы в EUR.", uk: "Усі суми в EUR." },
  saved: { en: "Saved", ro: "Salvat", ru: "Сохранено", uk: "Збережено" },
  saving: { en: "Saving", ro: "Se salvează", ru: "Сохранение", uk: "Збереження" },
  save_failed: { en: "Not saved. Check the connection.", ro: "Nesalvat. Verifică conexiunea.", ru: "Не сохранено. Проверьте соединение.", uk: "Не збережено. Перевірте з’єднання." },
  delete: { en: "Delete portfolio", ro: "Șterge portofoliul", ru: "Удалить портфель", uk: "Видалити портфель" },
  delete_ask: { en: "Delete this portfolio? The quotes stay.", ro: "Ștergi acest portofoliu? Ofertele rămân.", ru: "Удалить этот портфель? Расчёты останутся.", uk: "Видалити цей портфель? Розрахунки залишаться." },

  // ---- key figures
  k_assets: { en: "Assets", ro: "Active", ru: "Объекты", uk: "Об’єкти" },
  k_capacity: { en: "Capacity", ro: "Capacitate", ru: "Мощность", uk: "Потужність" },
  k_capex: { en: "Total investment", ro: "Investiție totală", ru: "Общие инвестиции", uk: "Загальні інвестиції" },
  k_debt: { en: "Debt", ro: "Datorie", ru: "Долг", uk: "Борг" },
  k_equity: { en: "Equity", ro: "Capital propriu", ru: "Собственный капитал", uk: "Власний капітал" },
  k_grant: { en: "Grant", ro: "Grant", ru: "Грант", uk: "Грант" },
  k_irr: { en: "Blended project IRR", ro: "IRR combinat al proiectelor", ru: "Совокупная IRR проектов", uk: "Сукупна IRR проєктів" },
  k_eirr: { en: "Equity IRR", ro: "IRR pe capital propriu", ru: "IRR на капитал", uk: "IRR на капітал" },
  k_npv: { en: "NPV", ro: "VAN", ru: "NPV", uk: "NPV" },
  k_dscr: { en: "Pooled DSCR, lowest year", ro: "DSCR agregat, anul cel mai slab", ru: "DSCR портфеля, худший год", uk: "DSCR портфеля, найгірший рік" },
  k_dscr_avg: { en: "Pooled DSCR, average", ro: "DSCR agregat, mediu", ru: "DSCR портфеля, средний", uk: "DSCR портфеля, середній" },
  k_weakest: { en: "Weakest asset", ro: "Cel mai slab activ", ru: "Самый слабый объект", uk: "Найслабший об’єкт" },
  k_payback: { en: "Payback", ro: "Recuperare", ru: "Окупаемость", uk: "Окупність" },
  k_energy: { en: "Energy, year 1", ro: "Energie, anul 1", ru: "Выработка, 1-й год", uk: "Генерація, 1-й рік" },
  k_co2: { en: "CO2 avoided per year", ro: "CO2 evitat pe an", ru: "CO2 за год (избежано)", uk: "CO2 за рік (уникнуто)" },
  k_readiness: { en: "Papers ready", ro: "Acte pregătite", ru: "Готовность документов", uk: "Готовність документів" },
  k_screening: { en: "E&S screening answered", ro: "Screening E&S completat", ru: "E&S скрининг заполнен", uk: "E&S скринінг заповнено" },
  years_w: { en: "yrs", ro: "ani", ru: "лет", uk: "р." },
  none: { en: "none", ro: "niciuna", ru: "нет", uk: "немає" },
  na: { en: "n/a", ro: "n/a", ru: "н/д", uk: "н/д" },
  no_debt: { en: "No debt in this case", ro: "Fără datorie în acest caz", ru: "В этом случае нет долга", uk: "У цьому випадку немає боргу" },
  irr_none: { en: "n/a: the cash flow never turns positive in the range", ro: "n/a: fluxul nu devine pozitiv în interval", ru: "н/д: поток не становится положительным в диапазоне", uk: "н/д: потік не стає додатним у діапазоні" },

  // ---- assets
  s_assets: { en: "Assets", ro: "Active", ru: "Объекты", uk: "Об’єкти" },
  add_quote: { en: "Add a quote", ro: "Adaugă o ofertă", ru: "Добавить расчёт", uk: "Додати розрахунок" },
  add_ph: { en: "Choose a quote to add", ro: "Alege o ofertă de adăugat", ru: "Выберите расчёт", uk: "Оберіть розрахунок" },
  no_quotes_left: { en: "Every Moldovan and Ukrainian quote is already in this portfolio.", ro: "Toate ofertele pentru Moldova și Ucraina sunt deja în acest portofoliu.", ru: "Все расчёты по Молдове и Украине уже в этом портфеле.", uk: "Усі розрахунки по Молдові та Україні вже в цьому портфелі." },
  remove: { en: "Remove from portfolio", ro: "Scoate din portofoliu", ru: "Убрать из портфеля", uk: "Прибрати з портфеля" },
  col_asset: { en: "Asset", ro: "Activ", ru: "Объект", uk: "Об’єкт" },
  col_area: { en: "Grid area", ro: "Zona rețelei", ru: "Зона сети", uk: "Зона мережі" },
  col_kwp: { en: "kWp", ro: "kWp", ru: "кВт", uk: "кВт" },
  col_capex: { en: "Capex", ro: "Capex", ru: "Капзатраты", uk: "Капвитрати" },
  col_irr: { en: "IRR", ro: "IRR", ru: "IRR", uk: "IRR" },
  col_npv: { en: "NPV", ro: "VAN", ru: "NPV", uk: "NPV" },
  col_dscr: { en: "Min DSCR", ro: "DSCR min.", ru: "Мин. DSCR", uk: "Мін. DSCR" },
  col_capex_override: { en: "Capex override, EUR", ro: "Capex propriu, EUR", ru: "Свои капзатраты, EUR", uk: "Власні капвитрати, EUR" },
  col_cons: { en: "Own use, kWh/yr", ro: "Consum propriu, kWh/an", ru: "Собственное потребление, кВт·ч/год", uk: "Власне споживання, кВт·год/рік" },
  col_cons_h: { en: "0 for a plant that sells everything to the grid", ro: "0 pentru o centrală care vinde tot în rețea", ru: "0 для станции, которая продаёт всё в сеть", uk: "0 для станції, що продає все в мережу" },
  assets_empty: { en: "Add quotes to see the portfolio.", ro: "Adaugă oferte ca să vezi portofoliul.", ru: "Добавьте расчёты, чтобы увидеть портфель.", uk: "Додайте розрахунки, щоб побачити портфель." },
  unsupported: { en: "{n} quote(s) in another market were left out: this module covers Moldova and Ukraine.", ro: "{n} ofertă(e) din altă piață au fost lăsate deoparte: acest modul acoperă Moldova și Ucraina.", ru: "Расчётов на другом рынке не учтено: {n}. Модуль охватывает Молдову и Украину.", uk: "Розрахунків на іншому ринку не враховано: {n}. Модуль охоплює Молдову та Україну." },
  missing: { en: "{n} quote(s) no longer exist and were skipped.", ro: "{n} ofertă(e) nu mai există și au fost sărite.", ru: "Расчётов больше нет, пропущено: {n}.", uk: "Розрахунків більше немає, пропущено: {n}." },
  by_area: { en: "Share of investment by grid area", ro: "Ponderea investiției pe zone de rețea", ru: "Доля инвестиций по зонам сети", uk: "Частка інвестицій за зонами мережі" },
  unknown_area: { en: "Not set from the address", ro: "Necunoscută după adresă", ru: "Не определена по адресу", uk: "Не визначено за адресою" },

  // ---- finance
  s_finance: { en: "Financing", ro: "Finanțare", ru: "Финансирование", uk: "Фінансування" },
  f_preset: { en: "Start from", ro: "Pornește de la", ru: "Начать с", uk: "Почати з" },
  f_preset_ph: { en: "Choose a starting point", ro: "Alege un punct de pornire", ru: "Выберите отправную точку", uk: "Оберіть відправну точку" },
  f_placeholder: { en: "Placeholder: replace with the bank's term sheet", ro: "Valoare provizorie: înlocuiește cu oferta băncii", ru: "Ориентир: замените условиями банка", uk: "Орієнтир: замініть умовами банку" },
  f_published: { en: "From a published description. Confirm with the bank.", ro: "Dintr-o descriere publicată. Confirmă cu banca.", ru: "Из опубликованного описания. Уточните в банке.", uk: "З опублікованого опису. Уточніть у банку." },
  f_source: { en: "Source", ro: "Sursă", ru: "Источник", uk: "Джерело" },
  f_gearing: { en: "Debt share, %", ro: "Ponderea datoriei, %", ru: "Доля долга, %", uk: "Частка боргу, %" },
  f_rate: { en: "Interest rate, %", ro: "Dobândă, %", ru: "Ставка, %", uk: "Ставка, %" },
  f_steps: { en: "Rate by year, % (optional)", ro: "Dobândă pe ani, % (opțional)", ru: "Ставка по годам, % (необязательно)", uk: "Ставка за роками, % (необов’язково)" },
  f_steps_h: { en: "e.g. 0, 5, 7: year 1, 2, 3; then the rate above", ro: "ex. 0, 5, 7: anii 1, 2, 3; apoi dobânda de sus", ru: "напр. 0, 5, 7: годы 1, 2, 3; затем ставка выше", uk: "напр. 0, 5, 7: роки 1, 2, 3; далі ставка вище" },
  f_tenor: { en: "Term, years", ro: "Durată, ani", ru: "Срок, лет", uk: "Строк, років" },
  f_disc: { en: "Discount rate, %", ro: "Rată de actualizare, %", ru: "Ставка дисконтирования, %", uk: "Ставка дисконтування, %" },
  f_currency: { en: "Loan currency", ro: "Moneda creditului", ru: "Валюта кредита", uk: "Валюта кредиту" },
  f_cur_eur: { en: "EUR", ro: "EUR", ru: "EUR", uk: "EUR" },
  f_cur_local: { en: "Local (lei or hryvnia)", ro: "Locală (lei sau grivne)", ru: "Местная (леи или гривны)", uk: "Місцева (леї або гривні)" },
  f_grant: { en: "Grant, % of capex", ro: "Grant, % din capex", ru: "Грант, % капзатрат", uk: "Грант, % капвитрат" },
  f_grant_cap: { en: "Grant cap, EUR", ro: "Plafon grant, EUR", ru: "Лимит гранта, EUR", uk: "Ліміт гранту, EUR" },
  f_comp: { en: "State repays of the loan, %", ro: "Statul rambursează din credit, %", ru: "Государство погашает кредита, %", uk: "Держава погашає кредиту, %" },
  f_comp_h: { en: "Once, after year 1", ro: "O dată, după anul 1", ru: "Один раз, после 1-го года", uk: "Один раз, після 1-го року" },
  f_note: { en: "Annual periods; debt service starts in year 1; before tax; grant at the start; compensation after year 1.", ro: "Perioade anuale; serviciul datoriei începe în anul 1; înainte de impozit; grantul la început; compensația după anul 1.", ru: "Годовые периоды; обслуживание долга с 1-го года; до налогов; грант в начале; компенсация после 1-го года.", uk: "Річні періоди; обслуговування боргу з 1-го року; до податків; грант на початку; компенсація після 1-го року." },

  // ---- scenario
  s_scenario: { en: "Base case and revenue", ro: "Scenariul de bază și venitul", ru: "Базовый сценарий и выручка", uk: "Базовий сценарій і виручка" },
  sc_h: { en: "These apply to every figure on the page. The stress cases below add to them.", ro: "Se aplică tuturor cifrelor din pagină. Cazurile de stres de mai jos se adaugă la ele.", ru: "Применяются ко всем цифрам на странице. Стресс-сценарии ниже накладываются сверху.", uk: "Застосовуються до всіх цифр на сторінці. Стрес-сценарії нижче накладаються зверху." },
  sc_tariff: { en: "Price paid, % of the quote's", ro: "Prețul plătit, % din cel al ofertei", ru: "Цена оплаты, % от цены расчёта", uk: "Ціна оплати, % від ціни розрахунку" },
  sc_esc: { en: "Yearly price escalation, %", ro: "Creșterea anuală a prețului, %", ru: "Ежегодный рост цены, %", uk: "Щорічне зростання ціни, %" },
  sc_esc_h: { en: "Empty keeps the engine's 3%", ro: "Gol păstrează 3% din motor", ru: "Пусто: остаётся 3% движка", uk: "Порожньо: лишається 3% рушія" },
  sc_esc_engine: { en: "3% (engine default)", ro: "3% (valoarea motorului)", ru: "3% (по умолчанию)", uk: "3% (за замовчуванням)" },
  sc_curt: { en: "Curtailment, % of exported energy", ro: "Limitare, % din energia exportată", ru: "Ограничение, % экспортируемой энергии", uk: "Обмеження, % експортованої енергії" },
  sc_delay: { en: "Construction delay, months", ro: "Întârziere la construcție, luni", ru: "Задержка строительства, мес.", uk: "Затримка будівництва, міс." },
  sc_dep: { en: "Net yearly loss of local currency vs EUR, %", ro: "Pierderea netă anuală a monedei locale față de EUR, %", ru: "Чистая годовая потеря местной валюты к EUR, %", uk: "Чиста річна втрата місцевої валюти до EUR, %" },
  sc_dep_h: { en: "After tariff indexation to local inflation", ro: "După indexarea tarifelor la inflația locală", ru: "После индексации тарифов на местную инфляцию", uk: "Після індексації тарифів на місцеву інфляцію" },
  sc_war: { en: "War-risk insurance, % of insured value per year", ro: "Asigurare de risc de război, % din valoarea asigurată pe an", ru: "Страхование военных рисков, % страховой стоимости в год", uk: "Страхування воєнних ризиків, % страхової вартості на рік" },
  sc_war_h: { en: "From a broker, MIGA or DFC quote. Left at 0 until you have one.", ro: "Dintr-o ofertă de la broker, MIGA sau DFC. Rămâne 0 până ai una.", ru: "Из предложения брокера, MIGA или DFC. Оставьте 0, пока нет предложения.", uk: "З пропозиції брокера, MIGA чи DFC. Залишайте 0, поки немає пропозиції." },
  sc_capex: { en: "Capex vs the estimate, %", ro: "Capex față de estimare, %", ru: "Капзатраты к оценке, %", uk: "Капвитрати до оцінки, %" },
  ppa_h: { en: "Fixed-price sale (PPA)", ro: "Vânzare cu preț fix (PPA)", ru: "Продажа по фиксированной цене (PPA)", uk: "Продаж за фіксованою ціною (PPA)" },
  ppa_share: { en: "Share of output, %", ro: "Ponderea din producție, %", ru: "Доля выработки, %", uk: "Частка генерації, %" },
  ppa_price: { en: "Price, EUR/MWh", ro: "Preț, EUR/MWh", ru: "Цена, EUR/МВт·ч", uk: "Ціна, EUR/МВт·год" },
  ppa_years: { en: "Term, years", ro: "Durată, ani", ru: "Срок, лет", uk: "Строк, років" },
  ppa_esc: { en: "Escalation, % a year", ro: "Indexare, % pe an", ru: "Индексация, % в год", uk: "Індексація, % на рік" },
  ppa_cur: { en: "Price currency", ro: "Moneda prețului", ru: "Валюта цены", uk: "Валюта ціни" },
  ppa_none: { en: "No PPA: output is valued as the quotes do.", ro: "Fără PPA: producția e evaluată ca în oferte.", ru: "Без PPA: выработка оценивается как в расчётах.", uk: "Без PPA: генерація оцінюється як у розрахунках." },

  // ---- stress
  s_stress: { en: "Stress tests", ro: "Teste de stres", ru: "Стресс-тесты", uk: "Стрес-тести" },
  st_h: { en: "Each case changes one thing from the base case, then the last combines the worst of them. The sizes of the shocks are illustrative round numbers, not forecasts.", ro: "Fiecare caz schimbă un singur lucru față de scenariul de bază, iar ultimul le combină pe cele mai rele. Mărimea șocurilor e orientativă, nu o prognoză.", ru: "Каждый сценарий меняет одно условие базового, последний соединяет худшие. Размеры шоков условные круглые числа, а не прогнозы.", uk: "Кожен сценарій змінює одну умову базового, останній поєднує найгірші. Розміри шоків умовні круглі числа, а не прогнози." },
  st_case: { en: "Case", ro: "Caz", ru: "Сценарий", uk: "Сценарій" },
  st_dnpv: { en: "NPV change", ro: "Schimbare VAN", ru: "Изменение NPV", uk: "Зміна NPV" },
  st_base: { en: "Base case (P50)", ro: "Scenariul de bază (P50)", ru: "Базовый сценарий (P50)", uk: "Базовий сценарій (P50)" },
  st_p90: { en: "Low yield (P90)", ro: "Producție scăzută (P90)", ru: "Низкая выработка (P90)", uk: "Низька генерація (P90)" },
  st_tariff: { en: "Price paid {n}% lower", ro: "Prețul plătit cu {n}% mai mic", ru: "Цена оплаты ниже на {n}%", uk: "Ціна оплати нижча на {n}%" },
  st_escalation: { en: "Price does not rise ({n}% a year)", ro: "Prețul nu crește ({n}% pe an)", ru: "Цена не растёт ({n}% в год)", uk: "Ціна не зростає ({n}% на рік)" },
  st_curtailment: { en: "Grid curtails {n}% of exports", ro: "Rețeaua limitează {n}% din export", ru: "Сеть ограничивает {n}% экспорта", uk: "Мережа обмежує {n}% експорту" },
  st_delay: { en: "Construction {n} months late", ro: "Construcția întârzie {n} luni", ru: "Стройка опаздывает на {n} мес.", uk: "Будівництво запізнюється на {n} міс." },
  st_currency: { en: "Local currency loses {n}% a year", ro: "Moneda locală pierde {n}% pe an", ru: "Местная валюта теряет {n}% в год", uk: "Місцева валюта втрачає {n}% на рік" },
  st_capex: { en: "Capex {n}% over", ro: "Capex cu {n}% peste", ru: "Капзатраты выше на {n}%", uk: "Капвитрати вищі на {n}%" },
  st_war: { en: "War-risk insurance {n}% a year", ro: "Asigurare de risc de război {n}% pe an", ru: "Страхование военных рисков {n}% в год", uk: "Страхування воєнних ризиків {n}% на рік" },
  st_combined: { en: "Combined downside", ro: "Scenariul combinat nefavorabil", ru: "Совокупный негативный сценарий", uk: "Сукупний негативний сценарій" },

  // ---- risk matrix
  s_risks: { en: "Risk matrix", ro: "Matricea de riscuri", ru: "Матрица рисков", uk: "Матриця ризиків" },
  rk_h: { en: "Each rating follows the rule shown. The DSCR levels are common rules of thumb: a lender sets its own.", ro: "Fiecare calificativ urmează regula afișată. Nivelurile DSCR sunt reguli uzuale: banca stabilește propriile praguri.", ru: "Каждая оценка следует показанному правилу. Уровни DSCR общепринятые ориентиры: банк задаёт свои.", uk: "Кожна оцінка йде за показаним правилом. Рівні DSCR загальноприйняті орієнтири: банк визначає свої." },
  rk_over: { en: "{n} above the scheme size", ro: "{n} peste dimensiunea schemei", ru: "выше лимита схемы: {n}", uk: "понад ліміт схеми: {n}" },
  lv_low: { en: "Low", ro: "Scăzut", ru: "Низкий", uk: "Низький" },
  lv_medium: { en: "Medium", ro: "Mediu", ru: "Средний", uk: "Середній" },
  lv_high: { en: "High", ro: "Ridicat", ru: "Высокий", uk: "Високий" },
  lv_unknown: { en: "Not rated", ro: "Neevaluat", ru: "Не оценён", uk: "Не оцінено" },
  rk_cover: { en: "Debt cover", ro: "Acoperirea datoriei", ru: "Покрытие долга", uk: "Покриття боргу" },
  rk_cover_r: { en: "Lowest pooled DSCR in the base case: 1.30 or more is low, 1.15 or more medium, below that high.", ro: "DSCR agregat minim în scenariul de bază: 1,30 sau mai mult e scăzut, 1,15 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR портфеля в базовом сценарии: от 1,30 низкий, от 1,15 средний, ниже высокий.", uk: "Найгірший DSCR портфеля в базовому сценарії: від 1,30 низький, від 1,15 середній, нижче високий." },
  rk_resource: { en: "Solar resource", ro: "Resursa solară", ru: "Солнечный ресурс", uk: "Сонячний ресурс" },
  rk_resource_r: { en: "Lowest DSCR at P90 yield: 1.15 or more low, 1.00 or more medium, below that high.", ro: "DSCR minim la producția P90: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при выработке P90: от 1,15 низкий, от 1,00 средний, ниже высокий.", uk: "Найгірший DSCR за генерації P90: від 1,15 низький, від 1,00 середній, нижче високий." },
  rk_tariff: { en: "Price and tariff", ro: "Preț și tarif", ru: "Цена и тариф", uk: "Ціна та тариф" },
  rk_tariff_r: { en: "Lowest DSCR with the price paid 20% lower: 1.15 or more low, 1.00 or more medium, below that high.", ro: "DSCR minim cu prețul plătit mai mic cu 20%: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при цене на 20% ниже: от 1,15 низкий, от 1,00 средний, ниже высокий.", uk: "Найгірший DSCR за ціни на 20% нижчої: від 1,15 низький, від 1,00 середній, нижче високий." },
  rk_curtailment: { en: "Grid curtailment", ro: "Limitarea de către rețea", ru: "Ограничение сетью", uk: "Обмеження мережею" },
  rk_curtailment_r: { en: "Lowest DSCR with exports curtailed: 1.15 or more low, 1.00 or more medium, below that high.", ro: "DSCR minim cu exportul limitat: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при ограничении экспорта: от 1,15 низкий, от 1,00 средний, ниже высокий.", uk: "Найгірший DSCR за обмеження експорту: від 1,15 низький, від 1,00 середній, нижче високий." },
  rk_currency: { en: "Currency", ro: "Valută", ru: "Валюта", uk: "Валюта" },
  rk_currency_r: { en: "Lowest DSCR with the local currency losing value: 1.15 or more low, 1.00 or more medium, below that high. A loan in the local currency counts as hedged: low.", ro: "DSCR minim cu pierderea valorii monedei locale: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat. Creditul în moneda locală se consideră acoperit: scăzut.", ru: "Худший DSCR при обесценении местной валюты: от 1,15 низкий, от 1,00 средний, ниже высокий. Кредит в местной валюте считается хеджированным: низкий.", uk: "Найгірший DSCR за знецінення місцевої валюти: від 1,15 низький, від 1,00 середній, нижче високий. Кредит у місцевій валюті вважається захеджованим: низький." },
  rk_construction: { en: "Construction delay", ro: "Întârziere la construcție", ru: "Задержка строительства", uk: "Затримка будівництва" },
  rk_construction_r: { en: "Lowest DSCR with a 6-month delay: 1.00 or more low, 0.60 or more medium, below that high.", ro: "DSCR minim cu 6 luni de întârziere: 1,00 sau mai mult scăzut, 0,60 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при задержке на 6 мес.: от 1,00 низкий, от 0,60 средний, ниже высокий.", uk: "Найгірший DSCR за затримки на 6 міс.: від 1,00 низький, від 0,60 середній, нижче високий." },
  rk_revenue: { en: "Revenue basis", ro: "Baza venitului", ru: "Основа выручки", uk: "Основа виручки" },
  rk_revenue_r: { en: "A fixed-price sale on the output: low. Otherwise medium, and high when an asset is above the size the market's tariff scheme covers.", ro: "Vânzare cu preț fix pe producție: scăzut. Altfel mediu, iar ridicat dacă un activ depășește dimensiunea acoperită de schema de tarife a pieței.", ru: "Фиксированная цена на выработку: низкий. Иначе средний, а высокий, если объект больше размера, который покрывает тарифная схема рынка.", uk: "Фіксована ціна на генерацію: низький. Інакше середній, а високий, якщо об’єкт більший за розмір, який покриває тарифна схема ринку." },
  rk_concentration: { en: "Concentration", ro: "Concentrare", ru: "Концентрация", uk: "Концентрація" },
  rk_concentration_r: { en: "Largest asset or grid area as a share of the investment: 33% or less low, 50% or less medium, above that high.", ro: "Cel mai mare activ sau zonă de rețea ca pondere din investiție: 33% sau mai puțin scăzut, 50% sau mai puțin mediu, peste e ridicat.", ru: "Крупнейший объект или зона сети в доле инвестиций: до 33% низкий, до 50% средний, выше высокий.", uk: "Найбільший об’єкт або зона мережі в частці інвестицій: до 33% низький, до 50% середній, вище високий." },
  rk_documents: { en: "Papers", ro: "Acte", ru: "Документы", uk: "Документи" },
  rk_documents_r: { en: "Share of the register ready (done = 1, draft = half): 80% or more low, 50% or more medium, below that high.", ro: "Ponderea registrului pregătită (gata = 1, ciornă = jumătate): 80% sau mai mult scăzut, 50% sau mai mult mediu, sub e ridicat.", ru: "Доля готового реестра (готово = 1, черновик = половина): от 80% низкий, от 50% средний, ниже высокий.", uk: "Частка готового реєстру (готово = 1, чернетка = половина): від 80% низький, від 50% середній, нижче високий." },

  // ---- documents register
  s_docs: { en: "Document register", ro: "Registrul de documente", ru: "Реестр документов", uk: "Реєстр документів" },
  dk_land: { en: "Land title or lease", ro: "Titlu de proprietate sau arendă", ru: "Право на землю или аренда", uk: "Право на землю чи оренда" },
  dk_grid: { en: "Grid connection terms or agreement", ro: "Condiții sau contract de racordare", ru: "Условия или договор на подключение", uk: "Умови чи договір на приєднання" },
  dk_permit: { en: "Construction permit or notification", ro: "Autorizație sau notificare de construcție", ru: "Разрешение или уведомление о строительстве", uk: "Дозвіл чи повідомлення про будівництво" },
  dk_design: { en: "Technical design", ro: "Proiect tehnic", ru: "Технический проект", uk: "Технічний проєкт" },
  dk_offtake: { en: "Offtake: PPA or tariff contract", ro: "Vânzare: PPA sau contract la tarif", ru: "Сбыт: PPA или договор по тарифу", uk: "Збут: PPA чи договір за тарифом" },
  dk_es: { en: "E&S screening for this site", ro: "Screening E&S pentru acest sit", ru: "E&S скрининг для этого объекта", uk: "E&S скринінг для цього об’єкта" },
  ds_missing: { en: "Missing", ro: "Lipsește", ru: "Нет", uk: "Немає" },
  ds_draft: { en: "Draft", ro: "Ciornă", ru: "Черновик", uk: "Чернетка" },
  ds_done: { en: "Done", ro: "Gata", ru: "Готово", uk: "Готово" },
  docs_h: { en: "A register of status, not a file store: keep the files themselves in your own folder and bring them to the data room.", ro: "Un registru de stare, nu un depozit de fișiere: păstrează fișierele în folderul tău și adu-le în data room.", ru: "Реестр статусов, а не хранилище файлов: храните сами файлы в своей папке и приносите их в data room.", uk: "Реєстр статусів, а не сховище файлів: зберігайте самі файли у своїй теці й приносьте їх у data room." },

  // ---- E&S
  s_es: { en: "Environmental and social screening", ro: "Screening de mediu și social", ru: "Экологический и социальный скрининг", uk: "Екологічний та соціальний скринінг" },
  es_h: { en: "A screening aid, not an impact assessment or a certificate of compliance. The questions follow the EBRD Performance Requirements and IFC Performance Standards in plain words. The answers are yours.", ro: "Un instrument de screening, nu o evaluare de impact sau un certificat de conformitate. Întrebările urmează Cerințele de Performanță BERD și Standardele de Performanță IFC, în cuvinte simple. Răspunsurile îți aparțin.", ru: "Вспомогательный скрининг, а не оценка воздействия и не сертификат соответствия. Вопросы следуют требованиям ЕБРР и стандартам IFC простыми словами. Ответы ваши.", uk: "Допоміжний скринінг, а не оцінка впливу і не сертифікат відповідності. Питання йдуть за вимогами ЄБРР і стандартами IFC простими словами. Відповіді ваші." },
  es_open: { en: "Open", ro: "Deschis", ru: "Не заполнено", uk: "Не заповнено" },
  es_yes: { en: "Yes", ro: "Da", ru: "Да", uk: "Так" },
  es_no: { en: "No", ro: "Nu", ru: "Нет", uk: "Ні" },
  es_na: { en: "Not applicable", ro: "Nu se aplică", ru: "Не применимо", uk: "Не застосовується" },
  es_note: { en: "Note or evidence", ro: "Notă sau dovadă", ru: "Примечание или подтверждение", uk: "Примітка чи підтвердження" },
  es_impact: { en: "Impact figures", ro: "Indicatori de impact", ru: "Показатели воздействия", uk: "Показники впливу" },
  es_impact_h: { en: "Jobs and gender figures are yours to enter: nothing here estimates them. Avoided CO2 uses the grid's emission factor.", ro: "Locurile de muncă și cifrele de gen le introduci tu: nimic de aici nu le estimează. CO2 evitat folosește factorul de emisie al rețelei.", ru: "Занятость и гендерные показатели вносите вы: здесь их не оценивают. Избежанный CO2 считается по коэффициенту выбросов сети.", uk: "Зайнятість і гендерні показники вносите ви: тут їх не оцінюють. Уникнутий CO2 рахується за коефіцієнтом викидів мережі." },
  es_jobs_c: { en: "Construction jobs", ro: "Locuri de muncă la construcție", ru: "Рабочие места на стройке", uk: "Робочі місця на будівництві" },
  es_jobs_p: { en: "Permanent jobs", ro: "Locuri de muncă permanente", ru: "Постоянные рабочие места", uk: "Постійні робочі місця" },
  es_women: { en: "Women among employees, %", ro: "Femei în rândul angajaților, %", ru: "Женщины среди работников, %", uk: "Жінки серед працівників, %" },
  es_co2_t: { en: "t a year", ro: "t pe an", ru: "т в год", uk: "т на рік" },
  es_co2_l: { en: "over the life", ro: "pe durata de viață", ru: "за срок службы", uk: "за строк служби" },
  es_factor: { en: "Emission factor", ro: "Factor de emisie", ru: "Коэффициент выбросов", uk: "Коефіцієнт викидів" },
  es_cbam: { en: "CBAM: the EU carbon border mechanism reaches your clients only as exporters of the goods it covers. Documenting avoided emissions helps them, but it is not a step this project must pass.", ro: "CBAM: mecanismul UE de ajustare a carbonului la frontieră îi privește pe clienții tăi doar ca exportatori ai bunurilor acoperite. Documentarea emisiilor evitate îi ajută, dar nu este un pas pe care proiectul trebuie să-l treacă.", ru: "CBAM: углеродный пограничный механизм ЕС касается ваших клиентов только как экспортёров охваченных товаров. Документирование избежанных выбросов им помогает, но это не шаг, который должен пройти проект.", uk: "CBAM: вуглецевий прикордонний механізм ЄС стосується ваших клієнтів лише як експортерів охоплених товарів. Документування уникнутих викидів їм допомагає, але це не крок, який має пройти проєкт." },

  // ---- exports
  s_export: { en: "Documents for the lender", ro: "Documente pentru finanțator", ru: "Документы для кредитора", uk: "Документи для кредитора" },
  ex_report: { en: "Bankability report (PDF)", ro: "Raport de bancabilitate (PDF)", ru: "Отчёт о банкабельности (PDF)", uk: "Звіт про банкабельність (PDF)" },
  ex_model: { en: "Financial model (Excel)", ro: "Model financiar (Excel)", ru: "Финансовая модель (Excel)", uk: "Фінансова модель (Excel)" },
  ex_room: { en: "Data room (ZIP)", ro: "Data room (ZIP)", ru: "Data room (ZIP)", uk: "Data room (ZIP)" },
  ex_lang: { en: "Document language", ro: "Limba documentelor", ru: "Язык документов", uk: "Мова документів" },
  ex_h: { en: "Lenders usually read English. The Excel model has live formulas, so an analyst can trace every number. The data room holds the report, the model, the registers and a manifest, not the files you keep yourself. What a given fund requires differs: ask it for its checklist.", ro: "Finanțatorii citesc de regulă engleza. Modelul Excel are formule vii, deci un analist poate urmări fiecare cifră. Data room conține raportul, modelul, registrele și un manifest, nu fișierele pe care le păstrezi tu. Cerințele diferă de la fond la fond: cere-i lista lui.", ru: "Кредиторы обычно читают по-английски. В модели Excel живые формулы, так что аналитик может проследить каждую цифру. В data room лежат отчёт, модель, реестры и манифест, а не файлы, которые вы храните сами. Требования у каждого фонда свои: запросите его чек-лист.", uk: "Кредитори зазвичай читають англійською. У моделі Excel живі формули, тож аналітик може простежити кожну цифру. У data room лежать звіт, модель, реєстри та маніфест, а не файли, які ви зберігаєте самі. Вимоги в кожного фонду свої: запросіть його чек-лист." },
  ex_pdf_fail: { en: "The report could not be built. Try again.", ro: "Raportul nu a putut fi generat. Încearcă din nou.", ru: "Не удалось построить отчёт. Попробуйте ещё раз.", uk: "Не вдалося побудувати звіт. Спробуйте ще раз." },

  // ---- report
  r_title: { en: "Bankability report", ro: "Raport de bancabilitate", ru: "Отчёт о банкабельности", uk: "Звіт про банкабельність" },
  r_prepared: { en: "Prepared by {co}", ro: "Pregătit de {co}", ru: "Подготовлено: {co}", uk: "Підготовлено: {co}" },
  r_summary: { en: "Summary", ro: "Rezumat", ru: "Резюме", uk: "Резюме" },
  r_projects: { en: "Projects", ro: "Proiecte", ru: "Проекты", uk: "Проєкти" },
  r_technical: { en: "Technical basis", ro: "Baza tehnică", ru: "Техническая основа", uk: "Технічна основа" },
  r_tech_p: { en: "Energy comes from the same engine as the quotes: a site yield (PVGIS where the roof was looked up), degradation, and an uncertainty budget of 7.1% that gives the P50 and P90 figures. P90 is the yield exceeded in 9 years out of 10.", ro: "Energia provine din același motor ca ofertele: producția specifică a sitului (PVGIS acolo unde acoperișul a fost căutat), degradarea și un buget de incertitudine de 7,1% din care rezultă valorile P50 și P90. P90 este producția depășită în 9 ani din 10.", ru: "Выработка считается тем же движком, что и расчёты: удельная выработка площадки (PVGIS там, где крыша искалась), деградация и бюджет неопределённости 7,1%, из которого получаются P50 и P90. P90 это выработка, которая превышается в 9 годах из 10.", uk: "Генерація рахується тим самим рушієм, що й розрахунки: питома генерація майданчика (PVGIS там, де дах шукали), деградація та бюджет невизначеності 7,1%, з якого виходять P50 і P90. P90 це генерація, яка перевищується в 9 роках із 10." },
  r_financial: { en: "Financial model", ro: "Model financiar", ru: "Финансовая модель", uk: "Фінансова модель" },
  r_cashflow: { en: "Cash flow by year", ro: "Flux de numerar pe ani", ru: "Денежный поток по годам", uk: "Грошовий потік за роками" },
  r_year: { en: "Year", ro: "An", ru: "Год", uk: "Рік" },
  r_cfads: { en: "Cash flow available for debt service", ro: "Flux disponibil pentru serviciul datoriei", ru: "Поток, доступный для обслуживания долга", uk: "Потік, доступний для обслуговування боргу" },
  r_ds: { en: "Debt service", ro: "Serviciul datoriei", ru: "Обслуживание долга", uk: "Обслуговування боргу" },
  r_assumptions: { en: "Assumptions", ro: "Ipoteze", ru: "Допущения", uk: "Припущення" },
  r_sensitivity: { en: "Sensitivity", ro: "Sensibilitate", ru: "Чувствительность", uk: "Чутливість" },
  r_risks: { en: "Risk matrix", ro: "Matricea de riscuri", ru: "Матрица рисков", uk: "Матриця ризиків" },
  r_es: { en: "Environmental and social screening", ro: "Screening de mediu și social", ru: "Экологический и социальный скрининг", uk: "Екологічний та соціальний скринінг" },
  r_docs: { en: "Document register", ro: "Registrul de documente", ru: "Реестр документов", uk: "Реєстр документів" },
  r_limits: { en: "What this report is not", ro: "Ce nu este acest raport", ru: "Чем этот отчёт не является", uk: "Чим цей звіт не є" },
  r_limits_p: { en: "It is a pre-feasibility analysis prepared with VoltMira, not a bank's credit approval, not an independent technical adviser's report and not an environmental and social impact assessment. Figures marked as placeholders or illustrative are assumptions to be replaced with term sheets, quotes and measurements. Tax is not modelled. The lender's own advisers should verify the technical and financial basis before any decision.", ro: "Este o analiză de pre-fezabilitate pregătită cu VoltMira, nu o aprobare de credit a unei bănci, nu raportul unui consultant tehnic independent și nu o evaluare a impactului asupra mediului și social. Cifrele marcate ca provizorii sau orientative sunt ipoteze care trebuie înlocuite cu oferte, devize și măsurători. Impozitul nu este modelat. Consultanții finanțatorului trebuie să verifice baza tehnică și financiară înainte de orice decizie.", ru: "Это предварительное технико-экономическое обоснование, подготовленное в VoltMira: не одобрение кредита банком, не отчёт независимого технического консультанта и не оценка экологического и социального воздействия. Цифры, помеченные как ориентировочные, это допущения, которые нужно заменить условиями банка, предложениями и измерениями. Налоги не моделируются. Консультанты кредитора должны проверить техническую и финансовую основу до любого решения.", uk: "Це попереднє техніко-економічне обґрунтування, підготовлене у VoltMira: не схвалення кредиту банком, не звіт незалежного технічного консультанта і не оцінка екологічного та соціального впливу. Цифри, позначені як орієнтовні, це припущення, які треба замінити умовами банку, пропозиціями та вимірюваннями. Податки не моделюються. Консультанти кредитора мають перевірити технічну та фінансову основу до будь-якого рішення." },
  r_page: { en: "Page", ro: "Pagina", ru: "Стр.", uk: "Стор." },
  r_status: { en: "Status", ro: "Stare", ru: "Статус", uk: "Статус" },
  r_print: { en: "Print or save as PDF", ro: "Tipărește sau salvează ca PDF", ru: "Печать или сохранить как PDF", uk: "Друк або зберегти як PDF" },
};

export const PT = T;

/** pt("st_tariff", "uk", { n: 20 }) */
export function pt(key, lang = "en", vars = null) {
  const e = T[key];
  let s = e ? (e[lang] ?? e.en) : key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split("{" + k + "}").join(String(v));
  return s;
}
