// lib/portfolioText.js — every word of the portfolio module, in four languages,
// in one place: the page, the PDF report, the Excel workbook and the data room
// read the same table, so a label can never differ between them. Module-local
// (not lib/i18n.js) because this is a B2B surface that grows on its own.
//
// pt(key, lang, {n: 3}) fills {n}. Missing languages fall back to English; the
// test in lib/portfolioText.test.js fails if any key lacks one of the four.
const T = {
  // ---- navigation and lists
  nav: { en: "Portfolios", ro: "Portofolii", ru: "Портфели", uk: "Портфелі" },
  title: { en: "Portfolios", ro: "Portofolii", ru: "Портфели", uk: "Портфелі" },
  sub: { en: "Group quotes into one investment for a lender or fund: totals, blended return, debt cover under stress, and the papers a bank asks for.", ro: "Grupează ofertele într-o singură investiție pentru o bancă sau un fond: totaluri, randament combinat, acoperirea datoriei sub stres și actele cerute de bancă.", ru: "Объедините расчёты в одну инвестицию для банка или фонда: итоги, совокупная доходность, покрытие долга при стрессе и документы, которые просит банк.", uk: "Об’єднайте розрахунки в одну інвестицію для банку чи фонду: підсумки, сукупна дохідність, покриття боргу за стресу та документи, які просить банк." },
  new: { en: "New portfolio", ro: "Portofoliu nou", ru: "Новый портфель", uk: "Новий портфель" },
  new_name_ph: { en: "e.g. Odesa region, 10 sites", ro: "ex. Regiunea Odesa, 10 situri", ru: "напр. Одесская область, 10 объектов", uk: "напр. Одеська область, 10 об’єктів" },
  empty_list: { en: "No portfolios yet. Create one, then add the quotes that belong together.", ro: "Niciun portofoliu încă. Creează unul, apoi adaugă ofertele care merg împreună.", ru: "Портфелей пока нет. Создайте один и добавьте расчёты, которые идут вместе.", uk: "Портфелів поки немає. Створіть один і додайте розрахунки, які йдуть разом." },
  n_assets: { en: "{n} assets", ro: "{n} active", ru: "объектов: {n}", uk: "об’єктів: {n}" },
  back: { en: "Portfolios", ro: "Portofolii", ru: "Портфели", uk: "Портфелі" },
  needs_db: { en: "Portfolios need a database update: run supabase/add-portfolios.sql (it is part of run-pending-2026-09-29.sql).", ro: "Portofoliile cer o actualizare a bazei de date: rulează supabase/add-portfolios.sql (face parte din run-pending-2026-09-29.sql).", ru: "Для портфелей нужно обновить базу данных: выполните supabase/add-portfolios.sql (он входит в run-pending-2026-09-29.sql).", uk: "Для портфелів потрібно оновити базу даних: виконайте supabase/add-portfolios.sql (він входить до run-pending-2026-09-29.sql)." },
  not_found: { en: "Portfolio not found.", ro: "Portofoliul nu a fost găsit.", ru: "Портфель не найден.", uk: "Портфель не знайдено." },
  market: { en: "Market", ro: "Piață", ru: "Рынок", uk: "Ринок" },
  market_md: { en: "Moldova", ro: "Moldova", ru: "Молдова", uk: "Молдова" },
  market_ua: { en: "Ukraine", ro: "Ucraina", ru: "Украина", uk: "Україна" },
  all_eur: { en: "All figures in EUR.", ro: "Toate sumele în EUR.", ru: "Все суммы в EUR.", uk: "Усі суми в EUR." },
  saved: { en: "Saved", ro: "Salvat", ru: "Сохранено", uk: "Збережено" },
  saving: { en: "Saving", ro: "Se salvează", ru: "Сохранение", uk: "Збереження" },
  save_failed: { en: "Not saved. Check the connection.", ro: "Nesalvat. Verifică conexiunea.", ru: "Не сохранено. Проверьте соединение.", uk: "Не збережено. Перевірте з’єднання." },
  delete: { en: "Delete portfolio", ro: "Șterge portofoliul", ru: "Удалить портфель", uk: "Видалити портфель" },
  delete_ask: { en: "Delete this portfolio? The quotes stay.", ro: "Ștergi acest portofoliu? Ofertele rămân.", ru: "Удалить этот портфель? Расчёты останутся.", uk: "Видалити цей портфель? Розрахунки залишаться." },

  // ---- key figures
  k_assets: { en: "Assets", ro: "Active", ru: "Объекты", uk: "Об’єкти" },
  k_capacity: { en: "Capacity", ro: "Capacitate", ru: "Мощность", uk: "Потужність" },
  k_capex: { en: "Total investment", ro: "Investiție totală", ru: "Общие инвестиции", uk: "Загальні інвестиції" },
  k_debt: { en: "Debt", ro: "Datorie", ru: "Долг", uk: "Борг" },
  k_equity: { en: "Equity", ro: "Capital propriu", ru: "Собственный капитал", uk: "Власний капітал" },
  k_grant: { en: "Grant", ro: "Grant", ru: "Грант", uk: "Грант" },
  k_irr: { en: "Blended project IRR", ro: "IRR combinat al proiectelor", ru: "Совокупная IRR проектов", uk: "Сукупна IRR проєктів" },
  k_eirr: { en: "Equity IRR", ro: "IRR pe capital propriu", ru: "IRR на капитал", uk: "IRR на капітал" },
  k_npv: { en: "NPV", ro: "VAN", ru: "NPV", uk: "NPV" },
  k_dscr: { en: "Pooled DSCR, lowest year", ro: "DSCR agregat, anul cel mai slab", ru: "DSCR портфеля, худший год", uk: "DSCR портфеля, найгірший рік" },
  k_dscr_avg: { en: "Pooled DSCR, average of the repayment years", ro: "DSCR agregat, media anilor de rambursare", ru: "DSCR портфеля, средний за годы погашения", uk: "DSCR портфеля, середній за роки погашення" },
  k_weakest: { en: "Weakest asset", ro: "Cel mai slab activ", ru: "Самый слабый объект", uk: "Найслабший об’єкт" },
  k_payback: { en: "Payback", ro: "Recuperare", ru: "Окупаемость", uk: "Окупність" },
  k_energy: { en: "Energy, year 1", ro: "Energie, anul 1", ru: "Выработка, 1-й год", uk: "Генерація, 1-й рік" },
  k_co2: { en: "CO2 avoided per year", ro: "CO2 evitat pe an", ru: "CO2 за год (избежано)", uk: "CO2 за рік (уникнуто)" },
  k_readiness: { en: "Papers ready", ro: "Acte pregătite", ru: "Готовность документов", uk: "Готовність документів" },
  k_screening: { en: "E&S screening answered", ro: "Screening E&S completat", ru: "E&S скрининг заполнен", uk: "E&S скринінг заповнено" },
  years_w: { en: "yrs", ro: "ani", ru: "лет", uk: "р." },
  none: { en: "none", ro: "niciuna", ru: "нет", uk: "немає" },
  na: { en: "n/a", ro: "n/a", ru: "н/д", uk: "н/д" },
  no_debt: { en: "No debt in this case", ro: "Fără datorie în acest caz", ru: "В этом случае нет долга", uk: "У цьому випадку немає боргу" },
  irr_none: { en: "n/a: the cash flow never turns positive in the range", ro: "n/a: fluxul nu devine pozitiv în interval", ru: "н/д: поток не становится положительным в диапазоне", uk: "н/д: потік не стає додатним у діапазоні" },

  // ---- assets
  s_assets: { en: "Assets", ro: "Active", ru: "Объекты", uk: "Об’єкти" },
  add_quote: { en: "Add a quote", ro: "Adaugă o ofertă", ru: "Добавить расчёт", uk: "Додати розрахунок" },
  add_ph: { en: "Choose a quote to add", ro: "Alege o ofertă de adăugat", ru: "Выберите расчёт", uk: "Оберіть розрахунок" },
  no_quotes_left: { en: "Every Moldovan and Ukrainian quote is already in this portfolio.", ro: "Toate ofertele pentru Moldova și Ucraina sunt deja în acest portofoliu.", ru: "Все расчёты по Молдове и Украине уже в этом портфеле.", uk: "Усі розрахунки по Молдові та Україні вже в цьому портфелі." },
  remove: { en: "Remove from portfolio", ro: "Scoate din portofoliu", ru: "Убрать из портфеля", uk: "Прибрати з портфеля" },
  col_asset: { en: "Asset", ro: "Activ", ru: "Объект", uk: "Об’єкт" },
  col_area: { en: "Grid area", ro: "Zona rețelei", ru: "Зона сети", uk: "Зона мережі" },
  col_kwp: { en: "kWp", ro: "kWp", ru: "кВт", uk: "кВт" },
  col_capex: { en: "Capex", ro: "Capex", ru: "Капзатраты", uk: "Капвитрати" },
  col_irr: { en: "IRR", ro: "IRR", ru: "IRR", uk: "IRR" },
  col_npv: { en: "NPV", ro: "VAN", ru: "NPV", uk: "NPV" },
  col_dscr: { en: "Min DSCR", ro: "DSCR min.", ru: "Мин. DSCR", uk: "Мін. DSCR" },
  col_capex_override: { en: "Capex override, EUR", ro: "Capex propriu, EUR", ru: "Свои капзатраты, EUR", uk: "Власні капвитрати, EUR" },
  col_cons: { en: "Own use, kWh/yr", ro: "Consum propriu, kWh/an", ru: "Собственное потребление, кВт·ч/год", uk: "Власне споживання, кВт·год/рік" },
  col_cons_h: { en: "0 for a plant that sells everything to the grid", ro: "0 pentru o centrală care vinde tot în rețea", ru: "0 для станции, которая продаёт всё в сеть", uk: "0 для станції, що продає все в мережу" },
  assets_empty: { en: "Add quotes to see the portfolio.", ro: "Adaugă oferte ca să vezi portofoliul.", ru: "Добавьте расчёты, чтобы увидеть портфель.", uk: "Додайте розрахунки, щоб побачити портфель." },
  unsupported: { en: "{n} quote(s) in another market were left out: this module covers Moldova and Ukraine.", ro: "{n} ofertă(e) din altă piață au fost lăsate deoparte: acest modul acoperă Moldova și Ucraina.", ru: "Расчётов на другом рынке не учтено: {n}. Модуль охватывает Молдову и Украину.", uk: "Розрахунків на іншому ринку не враховано: {n}. Модуль охоплює Молдову та Україну." },
  missing: { en: "{n} quote(s) no longer exist and were skipped.", ro: "{n} ofertă(e) nu mai există și au fost sărite.", ru: "Расчётов больше нет, пропущено: {n}.", uk: "Розрахунків більше немає, пропущено: {n}." },
  by_area: { en: "Share of investment by grid area", ro: "Ponderea investiției pe zone de rețea", ru: "Доля инвестиций по зонам сети", uk: "Частка інвестицій за зонами мережі" },
  unknown_area: { en: "Not set from the address", ro: "Necunoscută după adresă", ru: "Не определена по адресу", uk: "Не визначено за адресою" },

  // ---- finance
  s_finance: { en: "Financing", ro: "Finanțare", ru: "Финансирование", uk: "Фінансування" },
  f_preset: { en: "Start from", ro: "Pornește de la", ru: "Начать с", uk: "Почати з" },
  f_preset_ph: { en: "Choose a starting point", ro: "Alege un punct de pornire", ru: "Выберите отправную точку", uk: "Оберіть відправну точку" },
  f_placeholder: { en: "Placeholder: replace with the bank's term sheet", ro: "Valoare provizorie: înlocuiește cu oferta băncii", ru: "Ориентир: замените условиями банка", uk: "Орієнтир: замініть умовами банку" },
  f_published: { en: "From a published description. Confirm with the bank.", ro: "Dintr-o descriere publicată. Confirmă cu banca.", ru: "Из опубликованного описания. Уточните в банке.", uk: "З опублікованого опису. Уточніть у банку." },
  f_source: { en: "Source", ro: "Sursă", ru: "Источник", uk: "Джерело" },
  f_gearing: { en: "Debt share, %", ro: "Ponderea datoriei, %", ru: "Доля долга, %", uk: "Частка боргу, %" },
  f_rate: { en: "Interest rate, %", ro: "Dobândă, %", ru: "Ставка, %", uk: "Ставка, %" },
  f_steps: { en: "Rate by year, % (optional)", ro: "Dobândă pe ani, % (opțional)", ru: "Ставка по годам, % (необязательно)", uk: "Ставка за роками, % (необов’язково)" },
  f_steps_h: { en: "e.g. 0, 5, 7: year 1, 2, 3; then the rate above", ro: "ex. 0, 5, 7: anii 1, 2, 3; apoi dobânda de sus", ru: "напр. 0, 5, 7: годы 1, 2, 3; затем ставка выше", uk: "напр. 0, 5, 7: роки 1, 2, 3; далі ставка вище" },
  f_tenor: { en: "Term, years", ro: "Durată, ani", ru: "Срок, лет", uk: "Строк, років" },
  f_repay: { en: "Repayment", ro: "Rambursare", ru: "Погашение", uk: "Погашення" },
  f_build: { en: "Construction, months", ro: "Construcție, luni", ru: "Строительство, месяцев", uk: "Будівництво, місяців" },
  f_build_h: {
    en: "From financial close to commissioning. The interest on the loan drawn over these months is added to the loan.",
    ro: "De la închiderea finanțării până la punerea în funcțiune. Dobânda creditului tras în aceste luni se adaugă la credit.",
    ru: "От финансового закрытия до ввода в эксплуатацию. Проценты по кредиту, выбранному за эти месяцы, добавляются к кредиту.",
    uk: "Від фінансового закриття до введення в експлуатацію. Відсотки за кредитом, вибраним за ці місяці, додаються до кредиту.",
  },
  f_grace: { en: "Grace period, years (interest only)", ro: "Perioadă de grație, ani (doar dobândă)", ru: "Льготный период, лет (только проценты)", uk: "Пільговий період, років (лише відсотки)" },
  f_grace_h: {
    en: "Years after commissioning in which only interest is paid; they count inside the term.",
    ro: "Anii de după punerea în funcțiune în care se plătește doar dobânda; intră în durata creditului.",
    ru: "Годы после ввода, когда платятся только проценты; входят в срок кредита.",
    uk: "Роки після введення, коли сплачуються лише відсотки; входять у строк кредиту.",
  },
  f_dsra: { en: "Debt service reserve, months", ro: "Rezerva pentru serviciul datoriei, luni", ru: "Резерв на обслуживание долга, месяцев", uk: "Резерв на обслуговування боргу, місяців" },
  f_dsra_h: {
    en: "The sponsor sets aside this many months of debt service at commissioning; a short year draws on it, later surpluses refill it. Lenders often ask for 6.",
    ro: "Sponsorul pune deoparte atâtea luni de serviciu al datoriei la punerea în funcțiune; un an slab trage din ea, surplusurile o reîntregesc. Băncile cer des 6.",
    ru: "Спонсор откладывает столько месяцев обслуживания долга при вводе; слабый год берёт из резерва, излишки его пополняют. Банки часто просят 6.",
    uk: "Спонсор відкладає стільки місяців обслуговування боргу під час введення; слабкий рік бере з резерву, надлишки його поповнюють. Банки часто просять 6.",
  },
  f_repay_annuity: { en: "Equal instalments", ro: "Rate egale", ru: "Равными платежами", uk: "Рівними платежами" },
  f_repay_sculpted: { en: "Sculpted to the cash flow", ro: "Sculptată după fluxul de numerar", ru: "Под денежный поток", uk: "Під грошовий потік" },
  f_repay_h: {
    en: "Sculpted: each year's payment follows that year's cash flow, so the cover is the same in every repayment year; lenders to wind and solar plants usually set it this way. The shape is fixed on the base case, so a P90 year or a stress case shows the real cover.",
    ro: "Sculptată: plata fiecărui an urmează fluxul de numerar al anului, deci acoperirea e aceeași în fiecare an de rambursare; așa o stabilesc de obicei băncile pentru centralele eoliene și solare. Forma se fixează pe scenariul de bază, deci un an P90 sau un test de stres arată acoperirea reală.",
    ru: "Под денежный поток: платёж каждого года следует денежному потоку этого года, поэтому покрытие одинаково во все годы погашения; так обычно делают банки, кредитующие ветровые и солнечные станции. Форма фиксируется по базовому сценарию, поэтому год P90 или стресс-тест показывает реальное покрытие.",
    uk: "Під грошовий потік: платіж кожного року відповідає грошовому потоку цього року, тому покриття однакове в усі роки погашення; так зазвичай роблять банки, що кредитують вітрові та сонячні станції. Форма фіксується за базовим сценарієм, тому рік P90 або стрес-тест показує реальне покриття.",
  },
  f_disc: { en: "Discount rate, %", ro: "Rată de actualizare, %", ru: "Ставка дисконтирования, %", uk: "Ставка дисконтування, %" },
  f_currency: { en: "Loan currency", ro: "Moneda creditului", ru: "Валюта кредита", uk: "Валюта кредиту" },
  f_cur_eur: { en: "EUR", ro: "EUR", ru: "EUR", uk: "EUR" },
  f_cur_local: { en: "Local (lei or hryvnia)", ro: "Locală (lei sau grivne)", ru: "Местная (леи или гривны)", uk: "Місцева (леї або гривні)" },
  f_grant: { en: "Grant, % of capex", ro: "Grant, % din capex", ru: "Грант, % капзатрат", uk: "Грант, % капвитрат" },
  f_grant_cap: { en: "Grant cap, EUR", ro: "Plafon grant, EUR", ru: "Лимит гранта, EUR", uk: "Ліміт гранту, EUR" },
  f_comp: { en: "State repays of the loan, %", ro: "Statul rambursează din credit, %", ru: "Государство погашает кредита, %", uk: "Держава погашає кредиту, %" },
  f_comp_h: { en: "Once, after year 1", ro: "O dată, după anul 1", ru: "Один раз, после 1-го года", uk: "Один раз, після 1-го року" },
  f_note: { en: "Annual periods; debt service starts in year 1; after corporate income tax; grant at the start; compensation after year 1.", ro: "Perioade anuale; serviciul datoriei începe în anul 1; după impozitul pe venit; grantul la început; compensația după anul 1.", ru: "Годовые периоды; обслуживание долга с 1-го года; после налога на прибыль; грант в начале; компенсация после 1-го года.", uk: "Річні періоди; обслуговування боргу з 1-го року; після податку на прибуток; грант на початку; компенсація після 1-го року." },
  f_tax: { en: "Corporate income tax, %", ro: "Impozit pe venit, %", ru: "Налог на прибыль, %", uk: "Податок на прибуток, %" },
  f_tax_h: {
    en: "On the profit left after depreciation and the loan's interest. Moldova 12% (Tax Code art. 15), Ukraine 18% (art. 136). Set 0 for an exempt company.",
    ro: "Pe profitul rămas după amortizare și dobânda creditului. Moldova 12% (Codul fiscal, art. 15), Ucraina 18% (art. 136). Pune 0 pentru o companie scutită.",
    ru: "С прибыли после амортизации и процентов по кредиту. Молдова 12% (Налоговый кодекс, ст. 15), Украина 18% (ст. 136). 0 для освобождённой компании.",
    uk: "З прибутку після амортизації та відсотків за кредитом. Молдова 12% (Податковий кодекс, ст. 15), Україна 18% (ст. 136). 0 для звільненої компанії.",
  },
  f_tax_life: { en: "Tax depreciation, years", ro: "Amortizare fiscală, ani", ru: "Налоговая амортизация, лет", uk: "Податкова амортизація, років" },
  f_tax_life_h: {
    en: "Straight-line, of the cost after grant plus the interest during construction. Use the period your accountant applies.",
    ro: "Liniar, din costul după grant plus dobânda din perioada de construcție. Pune perioada pe care o aplică contabilul tău.",
    ru: "Линейно, от стоимости после гранта плюс проценты за период строительства. Укажите срок, который применяет бухгалтер.",
    uk: "Лінійно, від вартості після гранту плюс відсотки за період будівництва. Вкажіть строк, який застосовує бухгалтер.",
  },
  f_tax_loss: { en: "Tax loss carried forward, years", ro: "Reportarea pierderii fiscale, ani", ru: "Перенос налогового убытка, лет", uk: "Перенесення податкового збитку, років" },
  f_tax_loss_h: {
    en: "A loss lowers the next years' profits, oldest first, then lapses. Moldova 5 (art. 32), Ukraine without a limit (art. 140.4). 0 = no limit.",
    ro: "O pierdere reduce profiturile anilor următori, întâi cea mai veche, apoi se anulează. Moldova 5 (art. 32), Ucraina fără limită (art. 140.4). 0 = fără limită.",
    ru: "Убыток уменьшает прибыль следующих лет, начиная с самого старого, затем сгорает. Молдова 5 (ст. 32), Украина без ограничения (ст. 140.4). 0 = без ограничения.",
    uk: "Збиток зменшує прибуток наступних років, починаючи з найстарішого, потім згорає. Молдова 5 (ст. 32), Україна без обмеження (ст. 140.4). 0 = без обмеження.",
  },
  r_tax: { en: "Corporate income tax", ro: "Impozitul pe venit", ru: "Налог на прибыль", uk: "Податок на прибуток" },
  tax_line: { en: "{p}% of profit; straight-line over {y} years; {loss}", ro: "{p}% din profit; amortizare liniară pe {y} ani; {loss}", ru: "{p}% прибыли; линейная амортизация, {y} г.; {loss}", uk: "{p}% прибутку; лінійна амортизація, {y} р.; {loss}" },
  tax_loss_n: { en: "losses carried forward {n} years", ro: "pierderi reportate {n} ani", ru: "убытки переносятся {n} г.", uk: "збитки переносяться {n} р." },
  tax_loss_any: { en: "losses carried forward without a limit", ro: "pierderi reportate fără limită", ru: "убытки переносятся без ограничения", uk: "збитки переносяться без обмеження" },
  tax_none: { en: "not charged (0%)", ro: "nu se aplică (0%)", ru: "не начисляется (0%)", uk: "не нараховується (0%)" },

  // ---- scenario
  s_scenario: { en: "Base case and revenue", ro: "Scenariul de bază și venitul", ru: "Базовый сценарий и выручка", uk: "Базовий сценарій і виручка" },
  sc_h: { en: "These apply to every figure on the page. The stress cases below add to them.", ro: "Se aplică tuturor cifrelor din pagină. Cazurile de stres de mai jos se adaugă la ele.", ru: "Применяются ко всем цифрам на странице. Стресс-сценарии ниже накладываются сверху.", uk: "Застосовуються до всіх цифр на сторінці. Стрес-сценарії нижче накладаються зверху." },
  sc_tariff: { en: "Price paid, % of the quote's", ro: "Prețul plătit, % din cel al ofertei", ru: "Цена оплаты, % от цены расчёта", uk: "Ціна оплати, % від ціни розрахунку" },
  sc_esc: { en: "Yearly price escalation, %", ro: "Creșterea anuală a prețului, %", ru: "Ежегодный рост цены, %", uk: "Щорічне зростання ціни, %" },
  sc_esc_h: { en: "Empty keeps the engine's 3%", ro: "Gol păstrează 3% din motor", ru: "Пусто: остаётся 3% движка", uk: "Порожньо: лишається 3% рушія" },
  sc_esc_engine: { en: "3% (engine default)", ro: "3% (valoarea motorului)", ru: "3% (по умолчанию)", uk: "3% (за замовчуванням)" },
  sc_curt: { en: "Curtailment, % of exported energy", ro: "Limitare, % din energia exportată", ru: "Ограничение, % экспортируемой энергии", uk: "Обмеження, % експортованої енергії" },
  sc_delay: { en: "Construction delay, months", ro: "Întârziere la construcție, luni", ru: "Задержка строительства, мес.", uk: "Затримка будівництва, міс." },
  sc_dep: { en: "Net yearly loss of local currency vs EUR, %", ro: "Pierderea netă anuală a monedei locale față de EUR, %", ru: "Чистая годовая потеря местной валюты к EUR, %", uk: "Чиста річна втрата місцевої валюти до EUR, %" },
  sc_dep_h: { en: "After tariff indexation to local inflation", ro: "După indexarea tarifelor la inflația locală", ru: "После индексации тарифов на местную инфляцию", uk: "Після індексації тарифів на місцеву інфляцію" },
  sc_war: { en: "War-risk insurance, % of insured value per year", ro: "Asigurare de risc de război, % din valoarea asigurată pe an", ru: "Страхование военных рисков, % страховой стоимости в год", uk: "Страхування воєнних ризиків, % страхової вартості на рік" },
  sc_war_h: { en: "From a broker, MIGA or DFC quote. Left at 0 until you have one.", ro: "Dintr-o ofertă de la broker, MIGA sau DFC. Rămâne 0 până ai una.", ru: "Из предложения брокера, MIGA или DFC. Оставьте 0, пока нет предложения.", uk: "З пропозиції брокера, MIGA чи DFC. Залишайте 0, поки немає пропозиції." },
  sc_capex: { en: "Capex vs the estimate, %", ro: "Capex față de estimare, %", ru: "Капзатраты к оценке, %", uk: "Капвитрати до оцінки, %" },
  ppa_h: { en: "Fixed-price sale (PPA)", ro: "Vânzare cu preț fix (PPA)", ru: "Продажа по фиксированной цене (PPA)", uk: "Продаж за фіксованою ціною (PPA)" },
  ppa_share: { en: "Share of output, %", ro: "Ponderea din producție, %", ru: "Доля выработки, %", uk: "Частка генерації, %" },
  ppa_price: { en: "Price, EUR/MWh", ro: "Preț, EUR/MWh", ru: "Цена, EUR/МВт·ч", uk: "Ціна, EUR/МВт·год" },
  ppa_years: { en: "Term, years", ro: "Durată, ani", ru: "Срок, лет", uk: "Строк, років" },
  ppa_esc: { en: "Escalation, % a year", ro: "Indexare, % pe an", ru: "Индексация, % в год", uk: "Індексація, % на рік" },
  ppa_cur: { en: "Price currency", ro: "Moneda prețului", ru: "Валюта цены", uk: "Валюта ціни" },
  ppa_none: { en: "No PPA: output is valued as the quotes do.", ro: "Fără PPA: producția e evaluată ca în oferte.", ru: "Без PPA: выработка оценивается как в расчётах.", uk: "Без PPA: генерація оцінюється як у розрахунках." },

  // ---- stress
  s_stress: { en: "Stress tests", ro: "Teste de stres", ru: "Стресс-тесты", uk: "Стрес-тести" },
  st_h: { en: "Each case changes one thing from the base case, then the last combines the worst of them. The sizes of the shocks are illustrative round numbers, not forecasts.", ro: "Fiecare caz schimbă un singur lucru față de scenariul de bază, iar ultimul le combină pe cele mai rele. Mărimea șocurilor e orientativă, nu o prognoză.", ru: "Каждый сценарий меняет одно условие базового, последний соединяет худшие. Размеры шоков условные круглые числа, а не прогнозы.", uk: "Кожен сценарій змінює одну умову базового, останній поєднує найгірші. Розміри шоків умовні круглі числа, а не прогнози." },
  st_case: { en: "Case", ro: "Caz", ru: "Сценарий", uk: "Сценарій" },
  st_dnpv: { en: "NPV change", ro: "Schimbare VAN", ru: "Изменение NPV", uk: "Зміна NPV" },
  st_base: { en: "Base case (P50)", ro: "Scenariul de bază (P50)", ru: "Базовый сценарий (P50)", uk: "Базовий сценарій (P50)" },
  st_p90: { en: "Low yield (P90)", ro: "Producție scăzută (P90)", ru: "Низкая выработка (P90)", uk: "Низька генерація (P90)" },
  st_tariff: { en: "Price paid {n}% lower", ro: "Prețul plătit cu {n}% mai mic", ru: "Цена оплаты ниже на {n}%", uk: "Ціна оплати нижча на {n}%" },
  st_escalation: { en: "Price does not rise ({n}% a year)", ro: "Prețul nu crește ({n}% pe an)", ru: "Цена не растёт ({n}% в год)", uk: "Ціна не зростає ({n}% на рік)" },
  st_curtailment: { en: "Grid curtails {n}% of exports", ro: "Rețeaua limitează {n}% din export", ru: "Сеть ограничивает {n}% экспорта", uk: "Мережа обмежує {n}% експорту" },
  st_delay: { en: "Construction {n} months late", ro: "Construcția întârzie {n} luni", ru: "Стройка опаздывает на {n} мес.", uk: "Будівництво запізнюється на {n} міс." },
  st_currency: { en: "Local currency loses {n}% a year", ro: "Moneda locală pierde {n}% pe an", ru: "Местная валюта теряет {n}% в год", uk: "Місцева валюта втрачає {n}% на рік" },
  st_capex: { en: "Capex {n}% over", ro: "Capex cu {n}% peste", ru: "Капзатраты выше на {n}%", uk: "Капвитрати вищі на {n}%" },
  st_war: { en: "War-risk insurance {n}% a year", ro: "Asigurare de risc de război {n}% pe an", ru: "Страхование военных рисков {n}% в год", uk: "Страхування воєнних ризиків {n}% на рік" },
  st_combined: { en: "Combined downside", ro: "Scenariul combinat nefavorabil", ru: "Совокупный негативный сценарий", uk: "Сукупний негативний сценарій" },

  // ---- risk matrix
  s_risks: { en: "Risk matrix", ro: "Matricea de riscuri", ru: "Матрица рисков", uk: "Матриця ризиків" },
  rk_h: { en: "Each rating follows the rule shown. The DSCR levels are common rules of thumb: a lender sets its own.", ro: "Fiecare calificativ urmează regula afișată. Nivelurile DSCR sunt reguli uzuale: banca stabilește propriile praguri.", ru: "Каждая оценка следует показанному правилу. Уровни DSCR общепринятые ориентиры: банк задаёт свои.", uk: "Кожна оцінка йде за показаним правилом. Рівні DSCR загальноприйняті орієнтири: банк визначає свої." },
  rk_over: { en: "{n} above the scheme size", ro: "{n} peste dimensiunea schemei", ru: "выше лимита схемы: {n}", uk: "понад ліміт схеми: {n}" },
  lv_low: { en: "Low", ro: "Scăzut", ru: "Низкий", uk: "Низький" },
  lv_medium: { en: "Medium", ro: "Mediu", ru: "Средний", uk: "Середній" },
  lv_high: { en: "High", ro: "Ridicat", ru: "Высокий", uk: "Високий" },
  lv_unknown: { en: "Not rated", ro: "Neevaluat", ru: "Не оценён", uk: "Не оцінено" },
  rk_cover: { en: "Debt cover", ro: "Acoperirea datoriei", ru: "Покрытие долга", uk: "Покриття боргу" },
  rk_cover_r: { en: "Lowest pooled DSCR in the base case: 1.30 or more is low, 1.15 or more medium, below that high.", ro: "DSCR agregat minim în scenariul de bază: 1,30 sau mai mult e scăzut, 1,15 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR портфеля в базовом сценарии: от 1,30 низкий, от 1,15 средний, ниже высокий.", uk: "Найгірший DSCR портфеля в базовому сценарії: від 1,30 низький, від 1,15 середній, нижче високий." },
  rk_resource: { en: "Energy resource", ro: "Resursa energetică", ru: "Энергоресурс", uk: "Енергоресурс" },
  rk_resource_r: { en: "Lowest DSCR at P90 yield: 1.15 or more low, 1.00 or more medium, below that high.", ro: "DSCR minim la producția P90: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при выработке P90: от 1,15 низкий, от 1,00 средний, ниже высокий.", uk: "Найгірший DSCR за генерації P90: від 1,15 низький, від 1,00 середній, нижче високий." },
  rk_tariff: { en: "Price and tariff", ro: "Preț și tarif", ru: "Цена и тариф", uk: "Ціна та тариф" },
  rk_tariff_r: { en: "Lowest DSCR with the price paid 20% lower: 1.15 or more low, 1.00 or more medium, below that high.", ro: "DSCR minim cu prețul plătit mai mic cu 20%: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при цене на 20% ниже: от 1,15 низкий, от 1,00 средний, ниже высокий.", uk: "Найгірший DSCR за ціни на 20% нижчої: від 1,15 низький, від 1,00 середній, нижче високий." },
  rk_curtailment: { en: "Grid curtailment", ro: "Limitarea de către rețea", ru: "Ограничение сетью", uk: "Обмеження мережею" },
  rk_curtailment_r: { en: "Lowest DSCR with exports curtailed: 1.15 or more low, 1.00 or more medium, below that high.", ro: "DSCR minim cu exportul limitat: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при ограничении экспорта: от 1,15 низкий, от 1,00 средний, ниже высокий.", uk: "Найгірший DSCR за обмеження експорту: від 1,15 низький, від 1,00 середній, нижче високий." },
  rk_currency: { en: "Currency", ro: "Valută", ru: "Валюта", uk: "Валюта" },
  rk_currency_r: { en: "Lowest DSCR with the local currency losing value: 1.15 or more low, 1.00 or more medium, below that high. A loan in the local currency counts as hedged: low.", ro: "DSCR minim cu pierderea valorii monedei locale: 1,15 sau mai mult scăzut, 1,00 sau mai mult mediu, sub e ridicat. Creditul în moneda locală se consideră acoperit: scăzut.", ru: "Худший DSCR при обесценении местной валюты: от 1,15 низкий, от 1,00 средний, ниже высокий. Кредит в местной валюте считается хеджированным: низкий.", uk: "Найгірший DSCR за знецінення місцевої валюти: від 1,15 низький, від 1,00 середній, нижче високий. Кредит у місцевій валюті вважається захеджованим: низький." },
  rk_construction: { en: "Construction delay", ro: "Întârziere la construcție", ru: "Задержка строительства", uk: "Затримка будівництва" },
  rk_construction_r: { en: "Lowest DSCR with a 6-month delay: 1.00 or more low, 0.60 or more medium, below that high.", ro: "DSCR minim cu 6 luni de întârziere: 1,00 sau mai mult scăzut, 0,60 sau mai mult mediu, sub e ridicat.", ru: "Худший DSCR при задержке на 6 мес.: от 1,00 низкий, от 0,60 средний, ниже высокий.", uk: "Найгірший DSCR за затримки на 6 міс.: від 1,00 низький, від 0,60 середній, нижче високий." },
  rk_revenue: { en: "Revenue basis", ro: "Baza venitului", ru: "Основа выручки", uk: "Основа виручки" },
  rk_revenue_r: { en: "A fixed-price sale on the output: low. Otherwise medium, and high when an asset is above the size the market's tariff scheme covers.", ro: "Vânzare cu preț fix pe producție: scăzut. Altfel mediu, iar ridicat dacă un activ depășește dimensiunea acoperită de schema de tarife a pieței.", ru: "Фиксированная цена на выработку: низкий. Иначе средний, а высокий, если объект больше размера, который покрывает тарифная схема рынка.", uk: "Фіксована ціна на генерацію: низький. Інакше середній, а високий, якщо об’єкт більший за розмір, який покриває тарифна схема ринку." },
  rk_concentration: { en: "Concentration", ro: "Concentrare", ru: "Концентрация", uk: "Концентрація" },
  rk_concentration_r: { en: "Largest asset or grid area as a share of the investment: 33% or less low, 50% or less medium, above that high.", ro: "Cel mai mare activ sau zonă de rețea ca pondere din investiție: 33% sau mai puțin scăzut, 50% sau mai puțin mediu, peste e ridicat.", ru: "Крупнейший объект или зона сети в доле инвестиций: до 33% низкий, до 50% средний, выше высокий.", uk: "Найбільший об’єкт або зона мережі в частці інвестицій: до 33% низький, до 50% середній, вище високий." },
  rk_documents: { en: "Papers", ro: "Acte", ru: "Документы", uk: "Документи" },
  rk_documents_r: { en: "Share of the register ready (done = 1, draft = half): 80% or more low, 50% or more medium, below that high.", ro: "Ponderea registrului pregătită (gata = 1, ciornă = jumătate): 80% sau mai mult scăzut, 50% sau mai mult mediu, sub e ridicat.", ru: "Доля готового реестра (готово = 1, черновик = половина): от 80% низкий, от 50% средний, ниже высокий.", uk: "Частка готового реєстру (готово = 1, чернетка = половина): від 80% низький, від 50% середній, нижче високий." },

  // ---- documents register
  s_docs: { en: "Document register", ro: "Registrul de documente", ru: "Реестр документов", uk: "Реєстр документів" },
  dk_land: { en: "Land title or lease", ro: "Titlu de proprietate sau arendă", ru: "Право на землю или аренда", uk: "Право на землю чи оренда" },
  dk_grid: { en: "Grid connection terms or agreement", ro: "Condiții sau contract de racordare", ru: "Условия или договор на подключение", uk: "Умови чи договір на приєднання" },
  dk_permit: { en: "Construction permit or notification", ro: "Autorizație sau notificare de construcție", ru: "Разрешение или уведомление о строительстве", uk: "Дозвіл чи повідомлення про будівництво" },
  dk_design: { en: "Technical design", ro: "Proiect tehnic", ru: "Технический проект", uk: "Технічний проєкт" },
  dk_offtake: { en: "Offtake: PPA or tariff contract", ro: "Vânzare: PPA sau contract la tarif", ru: "Сбыт: PPA или договор по тарифу", uk: "Збут: PPA чи договір за тарифом" },
  dk_es: { en: "E&S screening for this site", ro: "Screening E&S pentru acest sit", ru: "E&S скрининг для этого объекта", uk: "E&S скринінг для цього об’єкта" },
  ds_missing: { en: "Missing", ro: "Lipsește", ru: "Нет", uk: "Немає" },
  ds_draft: { en: "Draft", ro: "Ciornă", ru: "Черновик", uk: "Чернетка" },
  ds_done: { en: "Done", ro: "Gata", ru: "Готово", uk: "Готово" },
  docs_h: { en: "A register of status, not a file store: keep the files themselves in your own folder and bring them to the data room.", ro: "Un registru de stare, nu un depozit de fișiere: păstrează fișierele în folderul tău și adu-le în data room.", ru: "Реестр статусов, а не хранилище файлов: храните сами файлы в своей папке и приносите их в data room.", uk: "Реєстр статусів, а не сховище файлів: зберігайте самі файли у своїй теці й приносьте їх у data room." },

  // ---- E&S
  s_es: { en: "Environmental and social screening", ro: "Screening de mediu și social", ru: "Экологический и социальный скрининг", uk: "Екологічний та соціальний скринінг" },
  es_h: { en: "A screening aid, not an impact assessment or a certificate of compliance. The questions follow the EBRD Performance Requirements and IFC Performance Standards in plain words. The answers are yours.", ro: "Un instrument de screening, nu o evaluare de impact sau un certificat de conformitate. Întrebările urmează Cerințele de Performanță BERD și Standardele de Performanță IFC, în cuvinte simple. Răspunsurile îți aparțin.", ru: "Вспомогательный скрининг, а не оценка воздействия и не сертификат соответствия. Вопросы следуют требованиям ЕБРР и стандартам IFC простыми словами. Ответы ваши.", uk: "Допоміжний скринінг, а не оцінка впливу і не сертифікат відповідності. Питання йдуть за вимогами ЄБРР і стандартами IFC простими словами. Відповіді ваші." },
  es_open: { en: "Open", ro: "Deschis", ru: "Не заполнено", uk: "Не заповнено" },
  es_yes: { en: "Yes", ro: "Da", ru: "Да", uk: "Так" },
  es_no: { en: "No", ro: "Nu", ru: "Нет", uk: "Ні" },
  es_na: { en: "Not applicable", ro: "Nu se aplică", ru: "Не применимо", uk: "Не застосовується" },
  es_note: { en: "Note or evidence", ro: "Notă sau dovadă", ru: "Примечание или подтверждение", uk: "Примітка чи підтвердження" },
  es_impact: { en: "Impact figures", ro: "Indicatori de impact", ru: "Показатели воздействия", uk: "Показники впливу" },
  es_impact_h: { en: "Jobs and gender figures are yours to enter: nothing here estimates them. Avoided CO2 uses the grid's emission factor.", ro: "Locurile de muncă și cifrele de gen le introduci tu: nimic de aici nu le estimează. CO2 evitat folosește factorul de emisie al rețelei.", ru: "Занятость и гендерные показатели вносите вы: здесь их не оценивают. Избежанный CO2 считается по коэффициенту выбросов сети.", uk: "Зайнятість і гендерні показники вносите ви: тут їх не оцінюють. Уникнутий CO2 рахується за коефіцієнтом викидів мережі." },
  es_jobs_c: { en: "Construction jobs", ro: "Locuri de muncă la construcție", ru: "Рабочие места на стройке", uk: "Робочі місця на будівництві" },
  es_jobs_p: { en: "Permanent jobs", ro: "Locuri de muncă permanente", ru: "Постоянные рабочие места", uk: "Постійні робочі місця" },
  es_women: { en: "Women among employees, %", ro: "Femei în rândul angajaților, %", ru: "Женщины среди работников, %", uk: "Жінки серед працівників, %" },
  es_co2_t: { en: "t a year", ro: "t pe an", ru: "т в год", uk: "т на рік" },
  es_co2_l: { en: "over the life", ro: "pe durata de viață", ru: "за срок службы", uk: "за строк служби" },
  es_factor: { en: "Emission factor", ro: "Factor de emisie", ru: "Коэффициент выбросов", uk: "Коефіцієнт викидів" },
  es_cbam: { en: "CBAM: the EU carbon border mechanism reaches your clients only as exporters of the goods it covers. Documenting avoided emissions helps them, but it is not a step this project must pass.", ro: "CBAM: mecanismul UE de ajustare a carbonului la frontieră îi privește pe clienții tăi doar ca exportatori ai bunurilor acoperite. Documentarea emisiilor evitate îi ajută, dar nu este un pas pe care proiectul trebuie să-l treacă.", ru: "CBAM: углеродный пограничный механизм ЕС касается ваших клиентов только как экспортёров охваченных товаров. Документирование избежанных выбросов им помогает, но это не шаг, который должен пройти проект.", uk: "CBAM: вуглецевий прикордонний механізм ЄС стосується ваших клієнтів лише як експортерів охоплених товарів. Документування уникнутих викидів їм допомагає, але це не крок, який має пройти проєкт." },

  // ---- exports
  s_export: { en: "Documents for the lender", ro: "Documente pentru finanțator", ru: "Документы для кредитора", uk: "Документи для кредитора" },
  ex_report: { en: "Bankability report (PDF)", ro: "Raport de bancabilitate (PDF)", ru: "Отчёт о банкабельности (PDF)", uk: "Звіт про банкабельність (PDF)" },
  ex_model: { en: "Financial model (Excel)", ro: "Model financiar (Excel)", ru: "Финансовая модель (Excel)", uk: "Фінансова модель (Excel)" },
  ex_room: { en: "Data room (ZIP)", ro: "Data room (ZIP)", ru: "Data room (ZIP)", uk: "Data room (ZIP)" },
  ex_lang: { en: "Document language", ro: "Limba documentelor", ru: "Язык документов", uk: "Мова документів" },
  ex_h: { en: "Lenders usually read English. The Excel model has live formulas, so an analyst can trace every number. The data room holds the report, the model, the registers and a manifest, not the files you keep yourself. What a given fund requires differs: ask it for its checklist.", ro: "Finanțatorii citesc de regulă engleza. Modelul Excel are formule vii, deci un analist poate urmări fiecare cifră. Data room conține raportul, modelul, registrele și un manifest, nu fișierele pe care le păstrezi tu. Cerințele diferă de la fond la fond: cere-i lista lui.", ru: "Кредиторы обычно читают по-английски. В модели Excel живые формулы, так что аналитик может проследить каждую цифру. В data room лежат отчёт, модель, реестры и манифест, а не файлы, которые вы храните сами. Требования у каждого фонда свои: запросите его чек-лист.", uk: "Кредитори зазвичай читають англійською. У моделі Excel живі формули, тож аналітик може простежити кожну цифру. У data room лежать звіт, модель, реєстри та маніфест, а не файли, які ви зберігаєте самі. Вимоги в кожного фонду свої: запросіть його чек-лист." },
  ex_pdf_fail: { en: "The report could not be built. Try again.", ro: "Raportul nu a putut fi generat. Încearcă din nou.", ru: "Не удалось построить отчёт. Попробуйте ещё раз.", uk: "Не вдалося побудувати звіт. Спробуйте ще раз." },

  // ---- report
  r_title: { en: "Bankability report", ro: "Raport de bancabilitate", ru: "Отчёт о банкабельности", uk: "Звіт про банкабельність" },
  r_prepared: { en: "Prepared by {co}", ro: "Pregătit de {co}", ru: "Подготовлено: {co}", uk: "Підготовлено: {co}" },
  r_summary: { en: "Summary", ro: "Rezumat", ru: "Резюме", uk: "Резюме" },
  r_projects: { en: "Projects", ro: "Proiecte", ru: "Проекты", uk: "Проєкти" },
  r_technical: { en: "Technical basis", ro: "Baza tehnică", ru: "Техническая основа", uk: "Технічна основа" },
  r_tech_p: { en: "Energy comes from the same engine as the quotes: a site yield (PVGIS where the roof was looked up), degradation, and an uncertainty budget of 7.1% that gives the P50 and P90 figures. P90 is the yield exceeded in 9 years out of 10.", ro: "Energia provine din același motor ca ofertele: producția specifică a sitului (PVGIS acolo unde acoperișul a fost căutat), degradarea și un buget de incertitudine de 7,1% din care rezultă valorile P50 și P90. P90 este producția depășită în 9 ani din 10.", ru: "Выработка считается тем же движком, что и расчёты: удельная выработка площадки (PVGIS там, где крыша искалась), деградация и бюджет неопределённости 7,1%, из которого получаются P50 и P90. P90 это выработка, которая превышается в 9 годах из 10.", uk: "Генерація рахується тим самим рушієм, що й розрахунки: питома генерація майданчика (PVGIS там, де дах шукали), деградація та бюджет невизначеності 7,1%, з якого виходять P50 і P90. P90 це генерація, яка перевищується в 9 роках із 10." },
  r_financial: { en: "Financial model", ro: "Model financiar", ru: "Финансовая модель", uk: "Фінансова модель" },
  r_cashflow: { en: "Cash flow by year", ro: "Flux de numerar pe ani", ru: "Денежный поток по годам", uk: "Грошовий потік за роками" },
  r_year: { en: "Year", ro: "An", ru: "Год", uk: "Рік" },
  r_cfads: { en: "Cash flow available for debt service", ro: "Flux disponibil pentru serviciul datoriei", ru: "Поток, доступный для обслуживания долга", uk: "Потік, доступний для обслуговування боргу" },
  r_ds: { en: "Debt service", ro: "Serviciul datoriei", ru: "Обслуживание долга", uk: "Обслуговування боргу" },
  r_assumptions: { en: "Assumptions", ro: "Ipoteze", ru: "Допущения", uk: "Припущення" },
  r_sensitivity: { en: "Sensitivity", ro: "Sensibilitate", ru: "Чувствительность", uk: "Чутливість" },
  r_risks: { en: "Risk matrix", ro: "Matricea de riscuri", ru: "Матрица рисков", uk: "Матриця ризиків" },
  r_es: { en: "Environmental and social screening", ro: "Screening de mediu și social", ru: "Экологический и социальный скрининг", uk: "Екологічний та соціальний скринінг" },
  r_docs: { en: "Document register", ro: "Registrul de documente", ru: "Реестр документов", uk: "Реєстр документів" },
  r_limits: { en: "What this report is not", ro: "Ce nu este acest raport", ru: "Чем этот отчёт не является", uk: "Чим цей звіт не є" },
  r_limits_p: { en: "It is a pre-feasibility analysis prepared with VoltMira, not a bank's credit approval, not an independent technical adviser's report and not an environmental and social impact assessment. Figures marked as placeholders or illustrative are assumptions to be replaced with term sheets, quotes and measurements. Corporate income tax is modelled at the stated rate; VAT and local taxes are not. The lender's own advisers should verify the technical and financial basis before any decision.", ro: "Este o analiză de pre-fezabilitate pregătită cu VoltMira, nu o aprobare de credit a unei bănci, nu raportul unui consultant tehnic independent și nu o evaluare a impactului asupra mediului și social. Cifrele marcate ca provizorii sau orientative sunt ipoteze care trebuie înlocuite cu oferte, devize și măsurători. Impozitul pe venit este modelat la cota indicată; TVA și taxele locale nu sunt modelate. Consultanții finanțatorului trebuie să verifice baza tehnică și financiară înainte de orice decizie.", ru: "Это предварительное технико-экономическое обоснование, подготовленное в VoltMira: не одобрение кредита банком, не отчёт независимого технического консультанта и не оценка экологического и социального воздействия. Цифры, помеченные как ориентировочные, это допущения, которые нужно заменить условиями банка, предложениями и измерениями. Налог на прибыль учтён по указанной ставке; НДС и местные налоги не моделируются. Консультанты кредитора должны проверить техническую и финансовую основу до любого решения.", uk: "Це попереднє техніко-економічне обґрунтування, підготовлене у VoltMira: не схвалення кредиту банком, не звіт незалежного технічного консультанта і не оцінка екологічного та соціального впливу. Цифри, позначені як орієнтовні, це припущення, які треба замінити умовами банку, пропозиціями та вимірюваннями. Податок на прибуток враховано за вказаною ставкою; ПДВ і місцеві податки не моделюються. Консультанти кредитора мають перевірити технічну та фінансову основу до будь-якого рішення." },
  r_page: { en: "Page", ro: "Pagina", ru: "Стр.", uk: "Стор." },
  r_status: { en: "Status", ro: "Stare", ru: "Статус", uk: "Статус" },
  r_pdf_fallback: { en: "The PDF could not be made on the server just now. Use Print below and choose Save as PDF: the document is the same.", ro: "PDF-ul nu a putut fi generat pe server acum. Folosește Tipărește mai jos și alege Salvează ca PDF: documentul e același.", ru: "Сейчас не удалось создать PDF на сервере. Нажмите «Печать» ниже и выберите «Сохранить как PDF»: документ тот же.", uk: "Зараз не вдалося створити PDF на сервері. Натисніть «Друк» нижче й оберіть «Зберегти як PDF»: документ той самий." },
  r_print: { en: "Print or save as PDF", ro: "Tipărește sau salvează ca PDF", ru: "Печать или сохранить как PDF", uk: "Друк або зберегти як PDF" },

  // ---- page flow: saving, duplicating, the empty state
  retry: { en: "Try again", ro: "Încearcă din nou", ru: "Повторить", uk: "Спробувати ще раз" },
  duplicate: { en: "Duplicate", ro: "Duplică", ru: "Дублировать", uk: "Дублювати" },
  duplicate_h: { en: "A copy with the same quotes and terms, to try another structure", ro: "O copie cu aceleași oferte și condiții, ca să încerci altă structură", ru: "Копия с теми же расчётами и условиями, чтобы попробовать другую структуру", uk: "Копія з тими самими розрахунками й умовами, щоб спробувати іншу структуру" },
  duplicate_name: { en: "{name} (copy)", ro: "{name} (copie)", ru: "{name} (копия)", uk: "{name} (копія)" },
  duplicate_failed: { en: "The copy could not be made. Try again.", ro: "Copia nu a putut fi făcută. Încearcă din nou.", ru: "Не удалось сделать копию. Попробуйте ещё раз.", uk: "Не вдалося зробити копію. Спробуйте ще раз." },
  duplicating: { en: "Copying", ro: "Se copiază", ru: "Копирование", uk: "Копіювання" },
  on_page: { en: "On this page", ro: "Pe această pagină", ru: "На этой странице", uk: "На цій сторінці" },
  nav_overview: { en: "Overview", ro: "Rezumat", ru: "Обзор", uk: "Огляд" },
  nav_debt: { en: "Debt", ro: "Datorie", ru: "Долг", uk: "Борг" },
  nav_cashflow: { en: "Cash flow", ro: "Flux", ru: "Поток", uk: "Потік" },
  nav_sensitivity: { en: "Sensitivity", ro: "Sensibilitate", ru: "Чувствительность", uk: "Чутливість" },
  nav_papers: { en: "Papers", ro: "Acte", ru: "Документы", uk: "Документи" },
  nav_es: { en: "E&S", ro: "E&S", ru: "E&S", uk: "E&S" },
  nav_export: { en: "Export", ro: "Export", ru: "Экспорт", uk: "Експорт" },
  empty_title: { en: "Start with the quotes that belong together", ro: "Pornește de la ofertele care merg împreună", ru: "Начните с расчётов, которые идут вместе", uk: "Почніть із розрахунків, які йдуть разом" },
  empty_body: { en: "Add the quotes a lender should see as one investment. The totals, the debt it supports, the stress tests and the papers to prepare appear as soon as there is one.", ro: "Adaugă ofertele pe care o bancă trebuie să le vadă ca o singură investiție. Totalurile, datoria pe care o susține, testele de stres și actele de pregătit apar imediat ce există una.", ru: "Добавьте расчёты, которые банк должен увидеть как одну инвестицию. Итоги, долг, который она выдерживает, стресс-тесты и документы для подготовки появятся сразу после первого.", uk: "Додайте розрахунки, які банк має побачити як одну інвестицію. Підсумки, борг, який вона витримує, стрес-тести та документи для підготовки з’являться одразу після першого." },
  add_won: { en: "Add all won or signed quotes in {m} ({n})", ro: "Adaugă toate ofertele câștigate sau semnate din {m} ({n})", ru: "Добавить все выигранные или подписанные расчёты: {m} ({n})", uk: "Додати всі виграні або підписані розрахунки: {m} ({n})" },
  add_won_none: { en: "No won or signed quote in {m} is left to add.", ro: "Nu mai e nicio ofertă câștigată sau semnată din {m} de adăugat.", ru: "Выигранных или подписанных расчётов ({m}) для добавления не осталось.", uk: "Виграних або підписаних розрахунків ({m}) для додавання не лишилося." },
  added_n: { en: "{n} quote(s) added", ro: "{n} ofertă(e) adăugată(e)", ru: "Добавлено расчётов: {n}", uk: "Додано розрахунків: {n}" },
  or_pick: { en: "Or pick one quote", ro: "Sau alege o ofertă", ru: "Или выберите один расчёт", uk: "Або оберіть один розрахунок" },
  no_quotes_market: { en: "There is no quote in Moldova or Ukraine yet. Make a quote first, then come back to group it.", ro: "Încă nu există nicio ofertă pentru Moldova sau Ucraina. Fă mai întâi o ofertă, apoi revino să o grupezi.", ru: "Расчётов по Молдове или Украине пока нет. Сначала сделайте расчёт, затем вернитесь, чтобы сгруппировать.", uk: "Розрахунків по Молдові чи Україні поки немає. Спершу зробіть розрахунок, потім поверніться, щоб згрупувати." },
  new_quote: { en: "Make a quote", ro: "Fă o ofertă", ru: "Сделать расчёт", uk: "Зробити розрахунок" },
  st_won: { en: "Won", ro: "Câștigată", ru: "Выигран", uk: "Виграно" },
  st_signed: { en: "Signed", ro: "Semnată", ru: "Подписан", uk: "Підписано" },
  st_sent: { en: "Sent", ro: "Trimisă", ru: "Отправлен", uk: "Надіслано" },
  st_draft: { en: "Draft", ro: "Ciornă", ru: "Черновик", uk: "Чернетка" },
  st_lost: { en: "Lost", ro: "Pierdută", ru: "Проигран", uk: "Програно" },
  list_steps: { en: "Name it and pick the market. Add the won or signed quotes. Size the debt, check the stress tests, and send the lender the report, the teaser and the model.", ro: "Dă-i un nume și alege piața. Adaugă ofertele câștigate sau semnate. Dimensionează datoria, verifică testele de stres și trimite finanțatorului raportul, prezentarea și modelul.", ru: "Назовите его и выберите рынок. Добавьте выигранные или подписанные расчёты. Рассчитайте долг, проверьте стресс-тесты и отправьте кредитору отчёт, тизер и модель.", uk: "Назвіть його й оберіть ринок. Додайте виграні або підписані розрахунки. Розрахуйте борг, перевірте стрес-тести й надішліть кредитору звіт, тизер і модель." },
  list_capacity: { en: "{kw} {u}", ro: "{kw} {u}", ru: "{kw} {u}", uk: "{kw} {u}" },

  // ---- display currency
  show_in: { en: "Show amounts in", ro: "Afișează sumele în", ru: "Показывать суммы в", uk: "Показувати суми в" },
  fx_note: { en: "Figures in {cur} at {rate} {cur} per EUR ({src}, {date}). The model runs in EUR.", ro: "Sume în {cur} la {rate} {cur} pentru un EUR ({src}, {date}). Modelul rulează în EUR.", ru: "Суммы в {cur} по курсу {rate} {cur} за EUR ({src}, {date}). Модель считается в EUR.", uk: "Суми в {cur} за курсом {rate} {cur} за EUR ({src}, {date}). Модель рахується в EUR." },
  fx_note_static: { en: "Figures in {cur} at a fixed reference rate of {rate} {cur} per EUR: the live rate was not available. The model runs in EUR.", ro: "Sume în {cur} la un curs fix de referință de {rate} {cur} pentru un EUR: cursul zilei nu a fost disponibil. Modelul rulează în EUR.", ru: "Суммы в {cur} по фиксированному справочному курсу {rate} {cur} за EUR: текущий курс недоступен. Модель считается в EUR.", uk: "Суми в {cur} за фіксованим довідковим курсом {rate} {cur} за EUR: поточний курс недоступний. Модель рахується в EUR." },
  inputs_eur: { en: "Inputs stay in EUR.", ro: "Datele introduse rămân în EUR.", ru: "Вводимые значения остаются в EUR.", uk: "Введені значення лишаються в EUR." },

  // ---- key figures added
  k_capacity_debt: { en: "Debt capacity", ro: "Capacitatea de îndatorare", ru: "Долговая ёмкость", uk: "Боргова спроможність" },
  k_capacity_sub: { en: "{pct}% of capex after grant; now {cur}", ro: "{pct}% din capex după grant; acum {cur}", ru: "{pct}% капзатрат после гранта; сейчас {cur}", uk: "{pct}% капвитрат після гранту; зараз {cur}" },
  k_dscr_p50: { en: "Lowest DSCR, P50", ro: "DSCR minim, P50", ru: "Мин. DSCR, P50", uk: "Мін. DSCR, P50" },
  k_dscr_p90: { en: "P90", ro: "P90", ru: "P90", uk: "P90" },
  k_investment_sub: { en: "{mw}, {mwh} {u} a year", ro: "{mw}, {mwh} {u} pe an", ru: "{mw}, {mwh} {u} в год", uk: "{mw}, {mwh} {u} на рік" },

  // ---- financing additions
  f_fee: { en: "Arrangement fee, % of the loan", ro: "Comision de acordare, % din credit", ru: "Комиссия за выдачу, % кредита", uk: "Комісія за видачу, % кредиту" },
  f_fee_h: { en: "Paid by the sponsor at signing; lowers the equity return only", ro: "Plătit de sponsor la semnare; reduce doar randamentul capitalului propriu", ru: "Платит спонсор при подписании; снижает только доходность капитала", uk: "Сплачує спонсор під час підписання; знижує лише дохідність капіталу" },
  f_termsheet: { en: "These terms come from a bank's offer or term sheet", ro: "Aceste condiții provin dintr-o ofertă sau un term sheet al băncii", ru: "Эти условия взяты из предложения или term sheet банка", uk: "Ці умови взято з пропозиції або term sheet банку" },
  f_termsheet_h: { en: "Tick it only when they do: the readiness score counts it.", ro: "Bifează doar dacă e adevărat: scorul de pregătire ține cont de asta.", ru: "Отмечайте, только если это так: оценка готовности это учитывает.", uk: "Позначайте, лише якщо це так: оцінка готовності це враховує." },
  f_also: { en: "Also", ro: "Vezi și", ru: "См. также", uk: "Див. також" },

  // ---- debt sizing
  s_debt: { en: "Debt sizing", ro: "Dimensionarea datoriei", ru: "Расчёт долга", uk: "Розрахунок боргу" },
  ds_h: { en: "The largest loan the cash flow covers, in every repayment year, by the target ratio on P50 energy and on P90 energy. The lowest of those two, and of the most a lender lends against the capex, is the capacity.", ro: "Cel mai mare credit pe care fluxul îl acoperă, în fiecare an de rambursare, cu raportul țintă la energia P50 și la energia P90. Cea mai mică dintre aceste două valori și plafonul pe care banca îl acordă față de capex este capacitatea.", ru: "Самый большой кредит, который поток покрывает в каждом году погашения с целевым коэффициентом при выработке P50 и при выработке P90. Меньшее из этих двух значений и предела, который банк даёт от капзатрат, и есть ёмкость.", uk: "Найбільший кредит, який потік покриває в кожному році погашення з цільовим коефіцієнтом за генерації P50 і за генерації P90. Менше з цих двох значень і межі, яку банк дає від капвитрат, і є спроможністю." },
  ds_p50: { en: "Target DSCR on P50", ro: "DSCR țintă la P50", ru: "Целевой DSCR при P50", uk: "Цільовий DSCR за P50" },
  ds_p90: { en: "Target DSCR on P90", ro: "DSCR țintă la P90", ru: "Целевой DSCR при P90", uk: "Цільовий DSCR за P90" },
  ds_cap: { en: "Most a lender lends, % of capex after grant", ro: "Maximul acordat de bancă, % din capex după grant", ru: "Максимум, который даёт банк, % капзатрат после гранта", uk: "Максимум, який дає банк, % капвитрат після гранту" },
  ds_targets_h: { en: "1.30x on P50 and 1.20x on P90 are common rules of thumb: a lender sets its own.", ro: "1,30x la P50 și 1,20x la P90 sunt reguli uzuale: banca stabilește propriile praguri.", ru: "1,30x при P50 и 1,20x при P90 общепринятые ориентиры: банк задаёт свои.", uk: "1,30x за P50 і 1,20x за P90 загальноприйняті орієнтири: банк визначає свої." },
  ds_capacity: { en: "Debt capacity", ro: "Capacitatea de îndatorare", ru: "Долговая ёмкость", uk: "Боргова спроможність" },
  ds_current: { en: "Debt in the model", ro: "Datoria din model", ru: "Долг в модели", uk: "Борг у моделі" },
  ds_headroom: { en: "Headroom", ro: "Rezervă", ru: "Запас", uk: "Запас" },
  ds_over: { en: "Over capacity", ro: "Peste capacitate", ru: "Сверх ёмкости", uk: "Понад спроможність" },
  ds_bind_p50: { en: "Set by the P50 test in year {y}", ro: "Stabilită de testul P50 în anul {y}", ru: "Определяет тест P50 в {y}-й год", uk: "Визначає тест P50 у {y}-й рік" },
  ds_bind_p50_s: { en: "Set by the P50 test, every year at the target", ro: "Stabilită de testul P50, în fiecare an la țintă", ru: "Определяет тест P50, каждый год на целевом уровне", uk: "Визначає тест P50, щороку на цільовому рівні" },
  ds_bind_p90_s: { en: "Set by the P90 test, every year at the target", ro: "Stabilită de testul P90, în fiecare an la țintă", ru: "Определяет тест P90, каждый год на целевом уровне", uk: "Визначає тест P90, щороку на цільовому рівні" },
  ds_level: { en: "With equal instalments it would be about {x}.", ro: "Cu rate egale ar fi circa {x}.", ru: "При равных платежах было бы около {x}.", uk: "За рівних платежів було б близько {x}." },
  ds_rule_s: {
    en: "Rule: in every repayment year, CFADS at least the target times the debt service. With sculpted repayments each year's service is that year's CFADS divided by the target, so the capacity is the present value of those amounts at the loan rate, on P50 and on P90.",
    ro: "Regula: în fiecare an de rambursare, CFADS cel puțin cât ținta înmulțită cu serviciul datoriei. Cu rambursare sculptată, serviciul fiecărui an este CFADS-ul anului împărțit la țintă, deci capacitatea este valoarea actualizată a acestor sume la dobânda creditului, pe P50 și pe P90.",
    ru: "Правило: в каждый год погашения CFADS не меньше целевого коэффициента, умноженного на обслуживание долга. При погашении под денежный поток обслуживание каждого года равно CFADS этого года, делённому на цель, поэтому ёмкость равна приведённой стоимости этих сумм по ставке кредита, по P50 и по P90.",
    uk: "Правило: у кожен рік погашення CFADS не менше за цільовий коефіцієнт, помножений на обслуговування боргу. За погашення під грошовий потік обслуговування кожного року дорівнює CFADS цього року, поділеному на ціль, тому спроможність дорівнює приведеній вартості цих сум за ставкою кредиту, за P50 і P90.",
  },
  ds_bind_p90: { en: "Set by the P90 test in year {y}", ro: "Stabilită de testul P90 în anul {y}", ru: "Определяет тест P90 в {y}-й год", uk: "Визначає тест P90 у {y}-й рік" },
  ds_bind_gearing: { en: "Set by the {n}% cap on the debt share", ro: "Stabilită de plafonul de {n}% al ponderii datoriei", ru: "Определяет предел доли долга {n}%", uk: "Визначає межа частки боргу {n}%" },
  ds_reco: { en: "Recommended debt share: {g}%", ro: "Ponderea recomandată a datoriei: {g}%", ru: "Рекомендуемая доля долга: {g}%", uk: "Рекомендована частка боргу: {g}%" },
  ds_reco_h: { en: "The capacity as a share of the capex after grant, rounded down to half a percent, so both tests pass.", ro: "Capacitatea ca pondere din capexul după grant, rotunjită în jos la jumătate de procent, ca ambele teste să treacă.", ru: "Ёмкость как доля капзатрат после гранта, округлённая вниз до половины процента, чтобы оба теста проходили.", uk: "Спроможність як частка капвитрат після гранту, округлена вниз до половини відсотка, щоб обидва тести проходили." },
  ds_apply: { en: "Use {g}%", ro: "Folosește {g}%", ru: "Применить {g}%", uk: "Застосувати {g}%" },
  ds_in_use: { en: "In use", ro: "Folosită", ru: "Применена", uk: "Застосовано" },
  ds_sculpted: { en: "If the lender sculpts repayments to the cash flow, about {x}. For information: the model repays in level instalments.", ro: "Dacă banca adaptează ratele la flux (sculpted), circa {x}. Informativ: modelul rambursează în rate egale.", ru: "Если банк подстроит погашение под поток (sculpted), около {x}. Для сведения: модель гасит равными платежами.", uk: "Якщо банк підлаштує погашення під потік (sculpted), близько {x}. Для довідки: модель гасить рівними платежами." },
  ds_tenor: { en: "Capacity by loan term", ro: "Capacitatea după durata creditului", ru: "Ёмкость по сроку кредита", uk: "Спроможність за строком кредиту" },
  ds_share: { en: "Share of capex after grant", ro: "Pondere din capex după grant", ru: "Доля капзатрат после гранта", uk: "Частка капвитрат після гранту" },
  ds_meter: { en: "Debt in the model against the capacity", ro: "Datoria din model față de capacitate", ru: "Долг в модели относительно ёмкости", uk: "Борг у моделі відносно спроможності" },
  ds_no_assets: { en: "Add quotes to size the debt.", ro: "Adaugă oferte ca să dimensionezi datoria.", ru: "Добавьте расчёты, чтобы рассчитать долг.", uk: "Додайте розрахунки, щоб розрахувати борг." },
  ds_rule_t: { en: "How the capacity is worked out", ro: "Cum se calculează capacitatea", ru: "Как считается ёмкость", uk: "Як рахується спроможність" },
  ds_rule: { en: "Rule: in every repayment year, CFADS at least the target times the debt service. With level repayments the service is proportional to the loan, so the capacity is the lowest, over those years, of CFADS / (target x service of 1 EUR borrowed).", ro: "Regula: în fiecare an de rambursare, CFADS cel puțin cât ținta înmulțită cu serviciul datoriei. La rate egale serviciul e proporțional cu creditul, deci capacitatea este minimul, pe acești ani, al CFADS / (țintă x serviciul pentru 1 EUR împrumutat).", ru: "Правило: в каждом году погашения CFADS не меньше цели, умноженной на обслуживание долга. При равных платежах обслуживание пропорционально кредиту, поэтому ёмкость это минимум за эти годы CFADS / (цель x обслуживание 1 EUR займа).", uk: "Правило: у кожному році погашення CFADS не менше за ціль, помножену на обслуговування боргу. За рівних платежів обслуговування пропорційне кредиту, тож спроможність це мінімум за ці роки CFADS / (ціль x обслуговування 1 EUR позики)." },

  // ---- sources and uses
  s_su: { en: "Sources and uses", ro: "Surse și utilizări", ru: "Источники и направления", uk: "Джерела та напрями" },
  su_uses: { en: "Uses", ro: "Utilizări", ru: "Направления", uk: "Напрями" },
  su_sources: { en: "Sources", ro: "Surse", ru: "Источники", uk: "Джерела" },
  su_capex: { en: "Plants, installed", ro: "Centrale, instalate", ru: "Станции под ключ", uk: "Станції під ключ" },
  su_fee: { en: "Arrangement fee", ro: "Comision de acordare", ru: "Комиссия за выдачу", uk: "Комісія за видачу" },
  su_total: { en: "Total", ro: "Total", ru: "Итого", uk: "Разом" },
  su_equity: { en: "Sponsor equity", ro: "Capitalul sponsorului", ru: "Капитал спонсора", uk: "Капітал спонсора" },
  su_share: { en: "Share", ro: "Pondere", ru: "Доля", uk: "Частка" },
  su_h: {
    en: "Up to commissioning. The interest during construction is lent with the debt; the arrangement fee and the reserve are paid by the sponsor. VAT is not modelled; development costs only where a plant's costs include them.",
    ro: "Până la punerea în funcțiune. Dobânda pe perioada construcției se creditează odată cu datoria; comisionul de acordare și rezerva le plătește sponsorul. TVA nu este modelată; costurile de dezvoltare doar unde costurile unei centrale le includ.",
    ru: "До ввода в эксплуатацию. Проценты в период строительства кредитуются вместе с долгом; комиссию за выдачу и резерв оплачивает спонсор. НДС не моделируется; затраты на разработку только там, где они входят в затраты станции.",
    uk: "До введення в експлуатацію. Відсотки в період будівництва кредитуються разом із боргом; комісію за видачу та резерв сплачує спонсор. ПДВ не моделюється; витрати на розробку лише там, де вони входять у витрати станції.",
  },
  su_idc: { en: "Interest during construction", ro: "Dobânda pe perioada construcției", ru: "Проценты в период строительства", uk: "Відсотки в період будівництва" },
  su_dsra: { en: "Debt service reserve", ro: "Rezerva pentru serviciul datoriei", ru: "Резерв на обслуживание долга", uk: "Резерв на обслуговування боргу" },
  ds_idc: { en: "Interest during construction, added to the loan: {x}.", ro: "Dobânda pe perioada construcției, adăugată la credit: {x}.", ru: "Проценты в период строительства, добавленные к кредиту: {x}.", uk: "Відсотки в період будівництва, додані до кредиту: {x}." },
  ds_dsra: { en: "Reserve the sponsor funds at commissioning: {x} ({m} months of debt service).", ro: "Rezerva finanțată de sponsor la punerea în funcțiune: {x} ({m} luni de serviciu al datoriei).", ru: "Резерв, который спонсор вносит при вводе: {x} ({m} мес. обслуживания долга).", uk: "Резерв, який спонсор вносить під час введення: {x} ({m} міс. обслуговування боргу)." },
  st_short: { en: "Shortfall on the loan payments", ro: "Lipsa la plata ratelor", ru: "Нехватка для платежей", uk: "Нестача для платежів" },
  st_short_dsra: { en: "Not covered by the reserve", ro: "Neacoperit de rezervă", ru: "Не покрыто резервом", uk: "Не покрито резервом" },
  st_short_h: {
    en: "The cash the loan payments lacked over the years of that case, which the sponsor would have to pay; a lender would treat it as a default.",
    ro: "Suma care a lipsit pentru plata ratelor în anii acelui caz, pe care ar trebui să o plătească sponsorul; banca ar considera-o neplată.",
    ru: "Сумма, которой не хватило для платежей по кредиту в этом сценарии; её пришлось бы внести спонсору, банк счёл бы это дефолтом.",
    uk: "Сума, якої забракло для платежів за кредитом у цьому сценарії; її довелося б внести спонсору, банк вважав би це дефолтом.",
  },
  st_short_dsra_h: {
    en: "What the reserve could not cover in that case, which the sponsor would have to pay; a lender would treat it as a default.",
    ro: "Ce nu a putut acoperi rezerva în acel caz, pe care ar trebui să o plătească sponsorul; banca ar considera-o neplată.",
    ru: "То, что резерв не покрыл в этом сценарии; это пришлось бы внести спонсору, банк счёл бы это дефолтом.",
    uk: "Те, що резерв не покрив у цьому сценарії; це довелося б внести спонсору, банк вважав би це дефолтом.",
  },

  // ---- charts
  ch_dscr: { en: "Debt cover by year", ro: "Acoperirea datoriei pe ani", ru: "Покрытие долга по годам", uk: "Покриття боргу за роками" },
  ch_dscr_h: { en: "Pooled DSCR in each repayment year on P50 and P90 energy, against the targets.", ro: "DSCR agregat în fiecare an de rambursare, la energia P50 și P90, față de ținte.", ru: "DSCR портфеля в каждом году погашения при выработке P50 и P90 относительно целей.", uk: "DSCR портфеля в кожному році погашення за генерації P50 і P90 відносно цілей." },
  ch_lowest: { en: "lowest {x}", ro: "minim {x}", ru: "минимум {x}", uk: "мінімум {x}" },
  ch_target: { en: "{x} {lvl} target", ro: "țintă {lvl} {x}", ru: "цель {lvl} {x}", uk: "ціль {lvl} {x}" },
  ch_nodebt: { en: "No debt in the model: set a debt share to see the cover.", ro: "Nicio datorie în model: setează o pondere a datoriei ca să vezi acoperirea.", ru: "В модели нет долга: задайте долю долга, чтобы увидеть покрытие.", uk: "У моделі немає боргу: задайте частку боргу, щоб побачити покриття." },
  ch_table: { en: "Show the numbers", ro: "Arată cifrele", ru: "Показать цифры", uk: "Показати цифри" },

  // ---- sensitivity (tornado)
  tor_title: { en: "What moves the result most", ro: "Ce influențează cel mai mult rezultatul", ru: "Что сильнее всего влияет на результат", uk: "Що найбільше впливає на результат" },
  tor_h: { en: "Each driver moved on its own, everything else at the base case, widest swing first. The ranges are illustrative and the same for every portfolio.", ro: "Fiecare factor e mișcat separat, restul rămâne ca în scenariul de bază, cel mai mare efect primul. Intervalele sunt orientative și aceleași pentru orice portofoliu.", ru: "Каждый фактор меняется отдельно, остальное как в базовом сценарии, сначала самый сильный. Диапазоны условные и одинаковые для любого портфеля.", uk: "Кожен чинник змінюється окремо, решта як у базовому сценарії, спершу найсильніший. Діапазони умовні й однакові для будь-якого портфеля." },
  tor_metric: { en: "Measure", ro: "Indicator", ru: "Показатель", uk: "Показник" },
  m_dscrMin: { en: "Lowest DSCR", ro: "DSCR minim", ru: "Мин. DSCR", uk: "Мін. DSCR" },
  m_equityIrr: { en: "Equity IRR", ro: "IRR pe capital propriu", ru: "IRR на капитал", uk: "IRR на капітал" },
  m_irr: { en: "Project IRR", ro: "IRR al proiectului", ru: "IRR проекта", uk: "IRR проєкту" },
  m_npv: { en: "NPV", ro: "VAN", ru: "NPV", uk: "NPV" },
  drv_yield: { en: "Energy yield ±{n}%", ro: "Producția de energie ±{n}%", ru: "Выработка ±{n}%", uk: "Генерація ±{n}%" },
  drv_price: { en: "Price paid ±{n}%", ro: "Prețul plătit ±{n}%", ru: "Цена оплаты ±{n}%", uk: "Ціна оплати ±{n}%" },
  drv_capex: { en: "Capex ±{n}%", ro: "Capex ±{n}%", ru: "Капзатраты ±{n}%", uk: "Капвитрати ±{n}%" },
  drv_opex: { en: "O&M cost ±{n}%", ro: "Costul O&M ±{n}%", ru: "Затраты на O&M ±{n}%", uk: "Витрати на O&M ±{n}%" },
  drv_rate: { en: "Interest rate ±{n} pp", ro: "Dobânda ±{n} pp", ru: "Ставка ±{n} п.п.", uk: "Ставка ±{n} в.п." },
  drv_escalation: { en: "Price escalation ±{n} pp a year", ro: "Creșterea prețului ±{n} pp pe an", ru: "Рост цены ±{n} п.п. в год", uk: "Зростання ціни ±{n} в.п. на рік" },
  drv_curtailment: { en: "Curtailment +{n} pp of exports", ro: "Limitare +{n} pp din export", ru: "Ограничение +{n} п.п. экспорта", uk: "Обмеження +{n} в.п. експорту" },
  drv_delay: { en: "Construction delay +{n} months", ro: "Întârziere la construcție +{n} luni", ru: "Задержка строительства +{n} мес.", uk: "Затримка будівництва +{n} міс." },
  tor_worse: { en: "Worse than base", ro: "Mai rău decât baza", ru: "Хуже базы", uk: "Гірше за базу" },
  tor_better: { en: "Better than base", ro: "Mai bine decât baza", ru: "Лучше базы", uk: "Краще за базу" },
  tor_base: { en: "Base {x}", ro: "Bază {x}", ru: "База {x}", uk: "База {x}" },
  tor_low: { en: "input down", ro: "intrare în jos", ru: "фактор ниже", uk: "чинник нижче" },
  tor_high: { en: "input up", ro: "intrare în sus", ru: "фактор выше", uk: "чинник вище" },
  tor_none: { en: "No driver moves this measure: with no debt there is no DSCR.", ro: "Niciun factor nu mișcă acest indicator: fără datorie nu există DSCR.", ru: "Ни один фактор не меняет этот показатель: без долга нет DSCR.", uk: "Жоден чинник не змінює цей показник: без боргу немає DSCR." },

  // ---- structures compared
  s_compare: { en: "Financing structures compared", ro: "Structuri de finanțare comparate", ru: "Сравнение структур финансирования", uk: "Порівняння структур фінансування" },
  cmp_h: { en: "The same assets and base case under each structure. Add a programme, or save the current terms as a variant before you change them.", ro: "Aceleași active și același scenariu de bază pentru fiecare structură. Adaugă un program sau salvează condițiile actuale ca variantă înainte să le schimbi.", ru: "Те же объекты и базовый сценарий в каждой структуре. Добавьте программу или сохраните текущие условия как вариант, прежде чем их менять.", uk: "Ті самі об’єкти й базовий сценарій у кожній структурі. Додайте програму або збережіть поточні умови як варіант, перш ніж їх змінювати." },
  cmp_current: { en: "Current", ro: "Actuală", ru: "Текущая", uk: "Поточна" },
  cmp_custom: { en: "Own terms", ro: "Condiții proprii", ru: "Свои условия", uk: "Власні умови" },
  cmp_add: { en: "Add a programme to compare", ro: "Adaugă un program de comparat", ru: "Добавить программу для сравнения", uk: "Додати програму для порівняння" },
  cmp_add_ph: { en: "Choose a programme", ro: "Alege un program", ru: "Выберите программу", uk: "Оберіть програму" },
  cmp_snapshot: { en: "Save current terms as a variant", ro: "Salvează condițiile actuale ca variantă", ru: "Сохранить текущие условия как вариант", uk: "Зберегти поточні умови як варіант" },
  cmp_variant: { en: "Variant {n}", ro: "Varianta {n}", ru: "Вариант {n}", uk: "Варіант {n}" },
  cmp_use: { en: "Use these terms", ro: "Folosește aceste condiții", ru: "Применить эти условия", uk: "Застосувати ці умови" },
  cmp_remove: { en: "Remove", ro: "Elimină", ru: "Убрать", uk: "Прибрати" },
  cmp_full: { en: "Four structures at most: remove one to add another.", ro: "Cel mult patru structuri: elimină una ca să adaugi alta.", ru: "Не больше четырёх структур: уберите одну, чтобы добавить другую.", uk: "Не більше чотирьох структур: приберіть одну, щоб додати іншу." },
  cmp_terms: { en: "Loan terms", ro: "Condițiile creditului", ru: "Условия кредита", uk: "Умови кредиту" },
  cmp_terms_v: { en: "{g}% at {r}%, {t} yrs", ro: "{g}% la {r}%, {t} ani", ru: "{g}% под {r}%, {t} лет", uk: "{g}% під {r}%, {t} р." },
  cmp_no_loan: { en: "No loan", ro: "Fără credit", ru: "Без кредита", uk: "Без кредиту" },
  cmp_within: { en: "Debt within capacity", ro: "Datoria în limita capacității", ru: "Долг в пределах ёмкости", uk: "Борг у межах спроможності" },
  yes: { en: "Yes", ro: "Da", ru: "Да", uk: "Так" },
  no: { en: "No", ro: "Nu", ru: "Нет", uk: "Ні" },
  steps_short: { en: "steps {s}", ro: "trepte {s}", ru: "ступени {s}", uk: "сходинки {s}" },
  build_short: { en: "{n} months to build", ro: "{n} luni de construcție", ru: "строительство {n} мес.", uk: "будівництво {n} міс." },
  grace_short: { en: "{n} years of grace", ro: "{n} ani de grație", ru: "льгота {n} г.", uk: "пільга {n} р." },
  dsra_short: { en: "reserve {n} months", ro: "rezervă {n} luni", ru: "резерв {n} мес.", uk: "резерв {n} міс." },
  build_short_one: { en: "{n} month to build", ro: "{n} lună de construcție", ru: "строительство {n} мес.", uk: "будівництво {n} міс." },
  grace_short_one: { en: "{n} year of grace", ro: "{n} an de grație", ru: "льгота {n} г.", uk: "пільга {n} р." },
  dsra_short_one: { en: "reserve {n} month", ro: "rezervă {n} lună", ru: "резерв {n} мес.", uk: "резерв {n} міс." },
  local_short: { en: "local currency", ro: "monedă locală", ru: "местная валюта", uk: "місцева валюта" },
  grant_short: { en: "grant {n}%", ro: "grant {n}%", ru: "грант {n}%", uk: "грант {n}%" },
  comp_short: { en: "{n}% repaid by the programme", ro: "{n}% rambursat de program", ru: "{n}% гасит программа", uk: "{n}% гасить програма" },

  // ---- readiness
  s_ready: { en: "Bankability readiness", ro: "Pregătirea pentru finanțare", ru: "Готовность к финансированию", uk: "Готовність до фінансування" },
  rd_h: { en: "A score from the data in this portfolio, and the steps that raise it, biggest gain first.", ro: "Un scor calculat din datele acestui portofoliu și pașii care îl cresc, cel mai mare câștig primul.", ru: "Оценка по данным этого портфеля и шаги, которые её повышают, сначала самые полезные.", uk: "Оцінка за даними цього портфеля та кроки, що її підвищують, спершу найкорисніші." },
  rd_of: { en: "of 100", ro: "din 100", ru: "из 100", uk: "зі 100" },
  rd_rule_t: { en: "How the score is made", ro: "Cum se calculează scorul", ru: "Как считается оценка", uk: "Як рахується оцінка" },
  rd_rule: { en: "Papers 35: the register, done 1, draft half. Debt cover 25: half for the lowest P50 DSCR at its target, half for P90. Screening 20: questions answered Yes or Not applicable. Inputs 20: site yield looked up, the contractor's capex, the site's location, terms from a published programme or a term sheet, and for Ukraine a war-risk insurance premium. A part that does not apply is left out and the rest rescale to 100. This is the tool's own checklist: a lender has its own.", ro: "Acte 35: registrul, gata 1, ciornă jumătate. Acoperirea datoriei 25: jumătate pentru DSCR minim P50 la țintă, jumătate pentru P90. Screening 20: întrebări cu răspuns Da sau Nu se aplică. Date 20: producția sitului căutată, capexul constructorului, locația sitului, condiții dintr-un program publicat sau un term sheet, iar pentru Ucraina o primă de asigurare de risc de război. O parte care nu se aplică e lăsată deoparte, iar restul se rescalează la 100. Este lista proprie a instrumentului: banca are propria listă.", ru: "Документы 35: реестр, готово 1, черновик половина. Покрытие долга 25: половина за мин. DSCR P50 на уровне цели, половина за P90. Скрининг 20: вопросы с ответом Да или Не применимо. Данные 20: выработка площадки найдена, капзатраты подрядчика, местоположение, условия из опубликованной программы или term sheet, а для Украины премия страхования военных рисков. Неприменимая часть не учитывается, остальные пересчитываются до 100. Это собственный перечень инструмента: у банка свой.", uk: "Документи 35: реєстр, готово 1, чернетка половина. Покриття боргу 25: половина за мін. DSCR P50 на рівні цілі, половина за P90. Скринінг 20: питання з відповіддю Так або Не застосовується. Дані 20: генерацію майданчика знайдено, капвитрати підрядника, розташування, умови з опублікованої програми чи term sheet, а для України премія страхування воєнних ризиків. Незастосовна частина не враховується, решта перераховується до 100. Це власний перелік інструмента: у банку свій." },
  part_papers: { en: "Papers", ro: "Acte", ru: "Документы", uk: "Документи" },
  part_cover: { en: "Debt cover", ro: "Acoperirea datoriei", ru: "Покрытие долга", uk: "Покриття боргу" },
  part_screening: { en: "E&S screening", ro: "Screening E&S", ru: "E&S скрининг", uk: "E&S скринінг" },
  part_inputs: { en: "Input quality", ro: "Calitatea datelor", ru: "Качество данных", uk: "Якість даних" },
  rd_points: { en: "{p} of {m}", ro: "{p} din {m}", ru: "{p} из {m}", uk: "{p} з {m}" },
  rd_not_counted: { en: "not counted", ro: "nu se numără", ru: "не учитывается", uk: "не враховується" },
  rd_next: { en: "Next steps", ro: "Pașii următori", ru: "Следующие шаги", uk: "Наступні кроки" },
  rd_gain: { en: "+{n}", ro: "+{n}", ru: "+{n}", uk: "+{n}" },
  rd_gain_h: { en: "points", ro: "puncte", ru: "баллов", uk: "балів" },
  rd_more: { en: "Show all {n} steps", ro: "Arată toți cei {n} pași", ru: "Показать все шаги: {n}", uk: "Показати всі кроки: {n}" },
  rd_less: { en: "Show fewer", ro: "Arată mai puține", ru: "Показать меньше", uk: "Показати менше" },
  rd_done: { en: "Nothing left on this list. A lender will still bring its own.", ro: "Nu a mai rămas nimic pe această listă. Banca va veni totuși cu propria listă.", ru: "В этом списке ничего не осталось. У банка всё равно будет свой.", uk: "У цьому списку нічого не лишилося. У банку все одно буде свій." },
  and: { en: "and", ro: "și", ru: "и", uk: "і" },
  names_more: { en: "{list} and {k} more", ro: "{list} și încă {k}", ru: "{list} и ещё {k}", uk: "{list} та ще {k}" },
  act_doc_land: { en: "Secure the land title or lease for {a}", ro: "Obține titlul de proprietate sau arenda pentru {a}", ru: "Оформите право на землю или аренду: {a}", uk: "Оформіть право на землю чи оренду: {a}" },
  act_doc_grid: { en: "Get the grid connection agreement for {a}", ro: "Obține contractul de racordare la rețea pentru {a}", ru: "Получите договор на подключение к сети: {a}", uk: "Отримайте договір на приєднання до мережі: {a}" },
  act_doc_permit: { en: "Obtain the construction permit or notification for {a}", ro: "Obține autorizația sau notificarea de construcție pentru {a}", ru: "Получите разрешение или уведомление о строительстве: {a}", uk: "Отримайте дозвіл чи повідомлення про будівництво: {a}" },
  act_doc_design: { en: "Complete the technical design for {a}", ro: "Finalizează proiectul tehnic pentru {a}", ru: "Подготовьте технический проект: {a}", uk: "Підготуйте технічний проєкт: {a}" },
  act_doc_offtake: { en: "Sign the offtake, a PPA or tariff contract, for {a}", ro: "Semnează vânzarea energiei, PPA sau contract la tarif, pentru {a}", ru: "Подпишите сбыт, PPA или договор по тарифу: {a}", uk: "Підпишіть збут, PPA чи договір за тарифом: {a}" },
  act_doc_es: { en: "Screen the site for environmental and social issues: {a}", ro: "Fă screeningul de mediu și social al sitului: {a}", ru: "Проведите экологический и социальный скрининг площадки: {a}", uk: "Проведіть екологічний і соціальний скринінг майданчика: {a}" },
  act_draft_land: { en: "Finalise the draft land title or lease for {a}", ro: "Finalizează ciorna titlului sau a arendei pentru {a}", ru: "Доведите черновик права на землю или аренды: {a}", uk: "Доведіть чернетку права на землю чи оренди: {a}" },
  act_draft_grid: { en: "Finalise the draft grid connection terms for {a}", ro: "Finalizează ciorna condițiilor de racordare pentru {a}", ru: "Доведите черновик условий подключения: {a}", uk: "Доведіть чернетку умов приєднання: {a}" },
  act_draft_permit: { en: "Finalise the draft permit or notification for {a}", ro: "Finalizează ciorna autorizației sau notificării pentru {a}", ru: "Доведите черновик разрешения или уведомления: {a}", uk: "Доведіть чернетку дозволу чи повідомлення: {a}" },
  act_draft_design: { en: "Finalise the draft technical design for {a}", ro: "Finalizează ciorna proiectului tehnic pentru {a}", ru: "Доведите черновик технического проекта: {a}", uk: "Доведіть чернетку технічного проєкту: {a}" },
  act_draft_offtake: { en: "Finalise the draft offtake contract for {a}", ro: "Finalizează ciorna contractului de vânzare pentru {a}", ru: "Доведите черновик договора сбыта: {a}", uk: "Доведіть чернетку договору збуту: {a}" },
  act_draft_es: { en: "Finalise the draft site screening for {a}", ro: "Finalizează ciorna screeningului sitului pentru {a}", ru: "Доведите черновик скрининга площадки: {a}", uk: "Доведіть чернетку скринінгу майданчика: {a}" },
  act_cover_p50: { en: "Lower the debt share to {g}% or lengthen the term: the lowest P50 cover is {x} against a {t} target", ro: "Coboară ponderea datoriei la {g}% sau prelungește durata: acoperirea minimă P50 este {x} față de ținta {t}", ru: "Снизьте долю долга до {g}% или удлините срок: мин. покрытие P50 {x} при цели {t}", uk: "Знизьте частку боргу до {g}% або подовжте строк: мін. покриття P50 {x} за цілі {t}" },
  act_cover_p90: { en: "Lower the debt share to {g}% or lengthen the term: the lowest P90 cover is {x} against a {t} target", ro: "Coboară ponderea datoriei la {g}% sau prelungește durata: acoperirea minimă P90 este {x} față de ținta {t}", ru: "Снизьте долю долга до {g}% или удлините срок: мин. покрытие P90 {x} при цели {t}", uk: "Знизьте частку боргу до {g}% або подовжте строк: мін. покриття P90 {x} за цілі {t}" },
  act_es_open: { en: "Answer {n} open screening questions", ro: "Răspunde la {n} întrebări de screening deschise", ru: "Ответьте на открытые вопросы скрининга: {n}", uk: "Дайте відповідь на відкриті питання скринінгу: {n}" },
  act_es_no: { en: "Resolve {n} screening answers marked No: add the mitigation and the evidence", ro: "Rezolvă {n} răspunsuri de screening marcate Nu: adaugă măsura de atenuare și dovada", ru: "Закройте ответы скрининга «Нет» ({n}): добавьте меры и подтверждение", uk: "Закрийте відповіді скринінгу «Ні» ({n}): додайте заходи та підтвердження" },
  act_in_yield: { en: "Look up the site yield (PVGIS) in the quote for {a}", ro: "Caută producția sitului (PVGIS) în oferta pentru {a}", ru: "Найдите выработку площадки (PVGIS) в расчёте: {a}", uk: "Знайдіть генерацію майданчика (PVGIS) у розрахунку: {a}" },
  act_in_capex: { en: "Enter the contractor's capex for {a}", ro: "Introdu capexul constructorului pentru {a}", ru: "Внесите капзатраты подрядчика: {a}", uk: "Внесіть капвитрати підрядника: {a}" },
  act_in_location: { en: "Set the location in the quote for {a}", ro: "Setează locația în oferta pentru {a}", ru: "Укажите местоположение в расчёте: {a}", uk: "Вкажіть розташування в розрахунку: {a}" },
  act_in_terms: { en: "Replace the placeholder loan terms with a bank's offer, then tick that they come from a term sheet", ro: "Înlocuiește condițiile provizorii cu oferta unei bănci, apoi bifează că provin dintr-un term sheet", ru: "Замените ориентировочные условия предложением банка и отметьте, что они из term sheet", uk: "Замініть орієнтовні умови пропозицією банку й позначте, що вони з term sheet" },
  act_in_war: { en: "Get a war-risk insurance quote (a broker, MIGA or DFC) and enter the premium", ro: "Obține o ofertă de asigurare de risc de război (broker, MIGA sau DFC) și introdu prima", ru: "Получите предложение по страхованию военных рисков (брокер, MIGA или DFC) и внесите премию", uk: "Отримайте пропозицію страхування воєнних ризиків (брокер, MIGA чи DFC) і внесіть премію" },

  // ---- map
  s_map: { en: "Where the assets are", ro: "Unde sunt activele", ru: "Где находятся объекты", uk: "Де розташовані об’єкти" },
  map_h: { en: "Circle area follows capacity. Positions come from the quotes, or from the address or the town when a quote has no pin.", ro: "Aria cercului urmează capacitatea. Pozițiile vin din oferte sau, când oferta nu are locația fixată, din adresă ori localitate.", ru: "Площадь круга соответствует мощности. Места берутся из расчётов, а если место не указано, по адресу или населённому пункту.", uk: "Площа кола відповідає потужності. Місця беруться з розрахунків, а якщо місце не вказано, за адресою або населеним пунктом." },
  map_missing: { en: "{n} asset(s) have no location yet: set it in the quote.", ro: "{n} activ(e) nu au încă locație: seteaz-o în ofertă.", ru: "Объектов без местоположения: {n}. Укажите его в расчёте.", uk: "Об’єктів без розташування: {n}. Вкажіть його в розрахунку." },
  map_none: { en: "No asset has a location yet. Set the address on the map in each quote and the sites appear here.", ro: "Niciun activ nu are încă locație. Setează adresa pe hartă în fiecare ofertă și siturile apar aici.", ru: "Ни у одного объекта нет местоположения. Укажите адрес на карте в каждом расчёте, и площадки появятся здесь.", uk: "Жоден об’єкт не має розташування. Вкажіть адресу на мапі в кожному розрахунку, і майданчики з’являться тут." },
  map_label: { en: "Map of the assets", ro: "Harta activelor", ru: "Карта объектов", uk: "Мапа об’єктів" },
  map_placing: { en: "Placing {done} of {n} on the map from the address or town", ro: "Se plasează pe hartă {done} din {n}, după adresă sau localitate", ru: "Размещаем на карте {done} из {n} по адресу или населённому пункту", uk: "Розміщуємо на мапі {done} з {n} за адресою або населеним пунктом" },
  map_notfound: { en: "{n} could not be found from the address or town: pin them in the quote.", ro: "{n} nu au putut fi găsite după adresă sau localitate: fixează-le locația în ofertă.", ru: "Не удалось найти по адресу или населённому пункту: {n}. Укажите место в расчёте.", uk: "Не вдалося знайти за адресою чи населеним пунктом: {n}. Вкажіть місце в розрахунку." },
  map_geofail: { en: "The address lookup is not answering right now; the rest are placed on your next visit.", ro: "Căutarea adreselor nu răspunde acum; restul se plasează la următoarea vizită.", ru: "Поиск адресов сейчас не отвечает; остальные разместятся при следующем визите.", uk: "Пошук адрес зараз не відповідає; решта розміститься під час наступного візиту." },
  map_loc_exact: { en: "Pinned in the quote", ro: "Fixat în ofertă", ru: "Указано в расчёте", uk: "Вказано в розрахунку" },
  map_loc_address: { en: "From the address", ro: "După adresă", ru: "По адресу", uk: "За адресою" },
  map_loc_locality: { en: "Approximate: town centre", ro: "Aproximativ: centrul localității", ru: "Приблизительно: центр населённого пункта", uk: "Приблизно: центр населеного пункту" },
  map_per_year: { en: "{x} a year", ro: "{x} pe an", ru: "{x} в год", uk: "{x} на рік" },
  map_place: { en: "Location", ro: "Locația", ru: "Местоположение", uk: "Місцезнаходження" },

  // ---- teaser
  ex_teaser: { en: "Investor teaser (PDF)", ro: "Prezentare pentru investitori (PDF)", ru: "Тизер для инвестора (PDF)", uk: "Тизер для інвестора (PDF)" },
  ex_teaser_h: { en: "Two pages for a first contact with a fund. The report and the model go after.", ro: "Două pagini pentru primul contact cu un fond. Raportul și modelul vin după.", ru: "Две страницы для первого контакта с фондом. Отчёт и модель потом.", uk: "Дві сторінки для першого контакту з фондом. Звіт і модель потім." },
  t_title: { en: "Investment opportunity", ro: "Oportunitate de investiție", ru: "Инвестиционная возможность", uk: "Інвестиційна можливість" },
  t_ask: { en: "{what} Total investment {capex}. Debt sought {debt}, sized at {t50} on P50 and {t90} on P90 over {y} years.", ro: "{what} Investiție totală {capex}. Datorie căutată {debt}, dimensionată la {t50} pe P50 și {t90} pe P90 pe {y} ani.", ru: "{what} Общие инвестиции {capex}. Искомый долг {debt}, рассчитан при {t50} на P50 и {t90} на P90 на {y} лет.", uk: "{what} Загальні інвестиції {capex}. Шуканий борг {debt}, розрахований за {t50} на P50 і {t90} на P90 на {y} р." },
  t_what_solar: { en: "Solar plants totalling {mw} in {m}.", ro: "Centrale solare însumând {mw} în {m}.", ru: "Солнечные станции общей мощностью {mw}, {m}.", uk: "Сонячні станції загальною потужністю {mw}, {m}." },
  t_what_solar_one: { en: "A solar plant of {mw} in {m}.", ro: "O centrală solară de {mw} în {m}.", ru: "Солнечная станция мощностью {mw}, {m}.", uk: "Сонячна станція потужністю {mw}, {m}." },
  t_what_mix: { en: "Renewable plants totalling {mw} in {m} ({kinds}).", ro: "Centrale regenerabile însumând {mw} în {m} ({kinds}).", ru: "Станции ВИЭ общей мощностью {mw}, {m} ({kinds}).", uk: "Станції ВДЕ загальною потужністю {mw}, {m} ({kinds})." },
  t_what_mix_one: { en: "A renewable plant of {mw} in {m} ({kinds}).", ro: "O centrală regenerabilă de {mw} în {m} ({kinds}).", ru: "Станция ВИЭ мощностью {mw}, {m} ({kinds}).", uk: "Станція ВДЕ потужністю {mw}, {m} ({kinds})." },
  t_over: { en: "The current terms set a loan of {x}, above what the cash flow supports; the sources and uses below are at the current terms.", ro: "Condițiile actuale stabilesc un credit de {x}, peste cât susține fluxul de numerar; sursele și utilizările de mai jos sunt la condițiile actuale.", ru: "Текущие условия задают кредит {x}, больше, чем выдерживает денежный поток; источники и использование ниже показаны при текущих условиях.", uk: "Поточні умови задають кредит {x}, більше, ніж витримує грошовий потік; джерела та використання нижче показано за поточних умов." },
  t_highlights: { en: "Key figures", ro: "Cifre cheie", ru: "Ключевые цифры", uk: "Ключові цифри" },
  t_assets: { en: "The assets", ro: "Activele", ru: "Объекты", uk: "Об’єкти" },
  t_more: { en: "and {n} more in the full report", ro: "și încă {n} în raportul complet", ru: "и ещё {n} в полном отчёте", uk: "і ще {n} у повному звіті" },
  t_risks: { en: "Main risks", ro: "Principalele riscuri", ru: "Основные риски", uk: "Основні ризики" },
  t_next: { en: "Ready to share", ro: "Disponibil la cerere", ru: "Готово к передаче", uk: "Готово до передачі" },
  t_next_p: { en: "The full bankability report, the Excel model with live formulas, and a data room with the document register and the screening.", ro: "Raportul complet de bancabilitate, modelul Excel cu formule vii și un data room cu registrul de documente și screeningul.", ru: "Полный отчёт о банкабельности, модель Excel с живыми формулами и data room с реестром документов и скринингом.", uk: "Повний звіт про банкабельність, модель Excel із живими формулами та data room із реєстром документів і скринінгом." },
  t_note: { en: "A first-contact summary prepared with VoltMira from the developer's own data. Pre-feasibility figures, not an offer and not a credit decision.", ro: "Un rezumat pentru primul contact, pregătit cu VoltMira din datele dezvoltatorului. Cifre de pre-fezabilitate, nu o ofertă și nu o decizie de credit.", ru: "Сводка для первого контакта, подготовленная в VoltMira по данным разработчика. Предварительные цифры, не оферта и не кредитное решение.", uk: "Зведення для першого контакту, підготовлене у VoltMira за даними розробника. Попередні цифри, не оферта й не кредитне рішення." },
  t_contact: { en: "Contact", ro: "Contact", ru: "Контакт", uk: "Контакт" },

  // ---- report structure
  r_contents: { en: "Contents", ro: "Cuprins", ru: "Содержание", uk: "Зміст" },
  r_keyfacts: { en: "Key facts", ro: "Date esențiale", ru: "Ключевые факты", uk: "Ключові факти" },
  r_messages: { en: "Key messages", ro: "Mesaje cheie", ru: "Главное", uk: "Головне" },
  r_assets: { en: "Portfolio and assets", ro: "Portofoliul și activele", ru: "Портфель и объекты", uk: "Портфель і об’єкти" },
  r_debt: { en: "Financing and debt sizing", ro: "Finanțarea și dimensionarea datoriei", ru: "Финансирование и расчёт долга", uk: "Фінансування та розрахунок боргу" },
  r_cover_cf: { en: "Cash flow and debt cover", ro: "Fluxul de numerar și acoperirea datoriei", ru: "Денежный поток и покрытие долга", uk: "Грошовий потік і покриття боргу" },
  r_ready: { en: "Readiness and documents", ro: "Pregătire și documente", ru: "Готовность и документы", uk: "Готовність і документи" },
  r_sources: { en: "Sources and limits", ro: "Surse și limite", ru: "Источники и ограничения", uk: "Джерела та обмеження" },
  r_of: { en: "of", ro: "din", ru: "из", uk: "з" },
  r_for: { en: "For discussion with lenders and investors", ro: "Pentru discuții cu finanțatori și investitori", ru: "Для обсуждения с кредиторами и инвесторами", uk: "Для обговорення з кредиторами та інвесторами" },
  msg_capacity: { en: "The cash flow supports debt of {x}, {pct}% of the capex after grant, at {t50} on P50 and {t90} on P90 over {y} years.", ro: "Fluxul susține o datorie de {x}, {pct}% din capexul după grant, la {t50} pe P50 și {t90} pe P90 pe {y} ani.", ru: "Поток выдерживает долг {x}, {pct}% капзатрат после гранта, при {t50} на P50 и {t90} на P90 на {y} лет.", uk: "Потік витримує борг {x}, {pct}% капвитрат після гранту, за {t50} на P50 і {t90} на P90 на {y} р." },
  msg_within: { en: "The modelled debt of {d} is within that capacity, with {h} of headroom.", ro: "Datoria modelată de {d} se încadrează în această capacitate, cu o rezervă de {h}.", ru: "Долг в модели {d} в пределах этой ёмкости, запас {h}.", uk: "Борг у моделі {d} у межах цієї спроможності, запас {h}." },
  msg_over: { en: "The modelled debt of {d} is above that capacity by {h}: the recommended debt share is {g}%.", ro: "Datoria modelată de {d} depășește această capacitate cu {h}: ponderea recomandată a datoriei este {g}%.", ru: "Долг в модели {d} превышает эту ёмкость на {h}: рекомендуемая доля долга {g}%.", uk: "Борг у моделі {d} перевищує цю спроможність на {h}: рекомендована частка боргу {g}%." },
  msg_nodebt: { en: "No debt is modelled; the cash flow would support {x} at those targets.", ro: "Nu este modelată nicio datorie; fluxul ar susține {x} la aceste ținte.", ru: "Долг не моделируется; поток выдержал бы {x} при этих целях.", uk: "Борг не моделюється; потік витримав би {x} за цих цілей." },
  msg_cover: { en: "Lowest pooled DSCR {p50} on P50 and {p90} on P90.", ro: "DSCR agregat minim {p50} pe P50 și {p90} pe P90.", ru: "Мин. DSCR портфеля {p50} на P50 и {p90} на P90.", uk: "Мін. DSCR портфеля {p50} на P50 і {p90} на P90." },
  msg_returns: { en: "Blended project IRR {irr}, equity IRR {eirr}, NPV {npv} at {d}%.", ro: "IRR combinat al proiectelor {irr}, IRR pe capital propriu {eirr}, VAN {npv} la {d}%.", ru: "Совокупная IRR проектов {irr}, IRR на капитал {eirr}, NPV {npv} при {d}%.", uk: "Сукупна IRR проєктів {irr}, IRR на капітал {eirr}, NPV {npv} за {d}%." },
  msg_stress: { en: "In the combined downside case the lowest DSCR is {x}.", ro: "În scenariul combinat nefavorabil, DSCR minim este {x}.", ru: "В совокупном негативном сценарии мин. DSCR {x}.", uk: "У сукупному негативному сценарії мін. DSCR {x}." },
  msg_ready: { en: "Readiness {s} of 100. Next: {a}.", ro: "Pregătire {s} din 100. Următorul pas: {a}.", ru: "Готовность {s} из 100. Дальше: {a}.", uk: "Готовність {s} зі 100. Далі: {a}." },
  r_sources_presets: { en: "Financing programme", ro: "Program de finanțare", ru: "Программа финансирования", uk: "Програма фінансування" },
  r_sources_fx: { en: "Exchange rate", ro: "Curs de schimb", ru: "Обменный курс", uk: "Обмінний курс" },
  r_sources_co2: { en: "Grid emission factors", ro: "Factori de emisie ai rețelei", ru: "Коэффициенты выбросов сети", uk: "Коефіцієнти викидів мережі" },
  r_sources_map: { en: "Map tiles", ro: "Hartă", ru: "Карта", uk: "Мапа" },
  r_no: { en: "No.", ro: "Nr.", ru: "№", uk: "№" },
};

export const PT = T;

/** pt("st_tariff", "uk", { n: 20 }) */
export function pt(key, lang = "en", vars = null) {
  // a "_one" key holds the singular, picked when {n} is 1
  const e = (vars && Number(vars.n) === 1 && T[key + "_one"]) || T[key];
  let s = e ? (e[lang] ?? e.en) : key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split("{" + k + "}").join(String(v));
  return s;
}
